NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 200
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 200
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 950
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 300
NDefines.NAir.AIR_WING_BOMB_DAMAGE_FACTOR = 5
NDefines.NAir.BIGGEST_AGILITY_FACTOR_DIFF = 3.0
NDefines.NAir.BIGGEST_SPEED_FACTOR_DIFF = 5.0
NDefines.NAir.COMBAT_BETTER_AGILITY_DAMAGE_REDUCTION = 0.65
NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_PLANE_CHANCE = 1.5
NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_PLANE_DAMAGE_FACTOR = 0.75
NDefines.NAir.BOMBING_DAMAGE_EXPERIENCE_SCALE = 0.0002
NDefines.NAir.WAR_SCORE_STRATEGIC_BOMBING_FACTOR = 0.1
NDefines.NAir.AIR_WING_XP_AIR_VS_AIR_COMBAT_GAIN = 1.5
NDefines.NAir.AIR_WING_XP_GROUND_MISSION_COMPLETED_GAIN = 1.2
NDefines.NAir.AIR_WING_XP_RECON_MISSION_COMPLETED_GAIN = 0.09


