-- aNCFO Defines
	Nlua = {
		NTopbar = {
			GAME_SPEED_LIMIT = 0,	-- Unlocks Speed to match as much as the proccessor can handle
			GAME_SPEED_STEPS = 5,	-- DONT CHANGE -- Deals with graphics and speed settings
			GAME_SPEED_ONE = 1,		-- DONT CHANGE --
			GAME_SPEED_TWO = 2,		-- DONT CHANGE --
			GAME_SPEED_THREE = 3,	-- DONT CHANGE --
			GAME_SPEED_FOUR = 4,	-- DONT CHANGE --
			GAME_SPEED_FIVE = 5,	-- DONT CHANGE --
		}
	}
	-- NGame
		NDefines.NGame.START_DATE = "1724.1.1.12"
		NDefines.NGame.END_DATE = "1936.1.1.1"
		-- Fyjuh Map Scale Calculation
		-- 1. Surface Area: 4 * pi * (7645.0^2) = 734,449,843.43 km^2
		-- 2. Areal Resolution (at 8192x4096): 734,449,843.43 / 33,554,432 = ~21.888311 km^2/px
		-- 3. Equatorial Circumference: 2 * pi * 7645.0 = 48,034.952 km
		-- 4. HOI4 Scale (Circumference / 5632 px wide): 48,034.952 / 5,632 = 8.528933...
		NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 8.529 -- Yes, I Choo_Choo_Oreo, did the math.
		NDefines.NGame.HANDS_OFF_START_TAG = "LLA"
		-- Optimization
			NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100
			NDefines.NGame.LAG_DAYS_FOR_PAUSE = 60
			NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36
			NDefines.NGame.GAME_SPEED_SECONDS = { 0.35, 0.15, 0.1, 0.035, 0.0 }

	-- NGeography
		NDefines.NGeography.MEDITERRANEAN_SEA_REGIONS = { 25, 26, 27, 28, 29, 30, 32, 34 }

	-- NDiplomacy
		NDefines.NDiplomacy.TENSION_STATE_VALUE = 0.05						-- Tension value gained by annexing one state
		NDefines.NDiplomacy.TENSION_NO_CB_WAR = 7.0							-- Amount of tension generated by a no-CB wargoal -- Was 7.0 changed to 3.5
		NDefines.NDiplomacy.TENSION_CB_WAR = 3.0							-- Amount of tension generated by a war with a CB -- Was 10.0 changed to 7.0
		NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 0.15					-- Amount of tension generated by annexing a state you don't have claims on -- Was 7.0 changed to 3.5
		NDefines.NDiplomacy.TENSION_ANNEX_CLAIM = 0.05						-- Amount of tension generated by annexing a state you DO have claims on
		NDefines.NDiplomacy.TENSION_ANNEX_CORE = -0.10						-- Amount of tension generated by annexing a state that is your core
		NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.02			-- Amount of tension generated for each sent division
		NDefines.NDiplomacy.TENSION_DECAY_DAILY = 0.01						-- Each day tension decays this much for Threat sources which are no longer relevant. Replaces TENSION_DECAY as of 1.12.0 -- Was 0.005 changed to 0.025
		NDefines.NDiplomacy.TENSION_SIZE_FACTOR = 1.0						-- All action tension values are multiplied by this value
		NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "1724.1.1.12"	-- Starting at this date, the tension values will be scaled down (will be equal to 1 before that)
		NDefines.NDiplomacy.TENSION_FACTION_JOIN = 1.0
		NDefines.NDiplomacy.TENSION_JOIN_ATTACKER = 0.5						-- scale of the amount of tension added when country joins attacker side -- Was 2 changed to 3
		NDefines.NDiplomacy.TENSION_GUARANTEE = -2.0
		NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 18				-- This many divisons are required for the country to be able to send volunteers.
		-- Optimization
			NDefines.NDiplomacy.DIPLOMACY_HOURS_BETWEEN_REQUESTS = 12
			NDefines.NDiplomacy.GUARANTEE_COST = 12
			NDefines.NDiplomacy.TRUCE_PERIOD_AFTER_KICKING_FROM_FACTION = 0
			NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_KICKING_NEW_MEMBERS_OF_FACTION = 0
			NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_REINVITE_KICKED_NATIONS = 0

	-- NCountry
		NDefines.NCountry.WAR_SUPPORT_OFFNSIVE_WAR = -0.20
		NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0.20
		NDefines.NCountry.WAR_SUPPORT_TENSION_IMPACT = 0.20
		NDefines.NCountry.WEEKLY_STABILITY_GAIN = 0.0
		NDefines.NCountry.WEEKLY_WAR_SUPPORT_GAIN = 0.0
		NDefines.NCountry.BUILDING_IMPORTANCE_FACTOR = 6.0		-- Default 3.0
		NDefines.NCountry.RESOURCE_IMPORTANCE_FACTOR = 2.0		-- Default 1.0
		NDefines.NCountry.STATE_VALUE_BUILDING_SLOTS_MULT = 8.0	-- Default 4.0
		NDefines.NCountry.DEFAULT_STABILITY = 0.50 	-- Could be the 'Middle' for modifers -- Default stability if not scripted otherwise.
		NDefines.NCountry.DEFAULT_WAR_SUPPORT = 0.50 	-- Could be the 'Middle' for modifers -- Default war support if not scripted otherwise.
		NDefines.NCountry.MIN_STABILITY = -0.50		-- 100% total negative, as -100% is nobody but -50% is vast majority.
		NDefines.NCountry.MAX_STABILITY = 1.0
		NDefines.NCountry.MIN_WAR_SUPPORT = -0.50	-- 100% total negative, as -100% is nobody but -50% is vast majority.
		NDefines.NCountry.MAX_WAR_SUPPORT = 1.0
		NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 1.0
		NDefines.NCountry.BASE_FUEL_GAIN = 1.0
		NDefines.NCountry.MAX_BOMBING_WAR_SUPPORT_IMPACT = -0.50
		NDefines.NCountry.MAX_HEROES_BEING_KILLED_WAR_SUPPORT_IMPACT = -0.50
		NDefines.NCountry.MAX_CONVOYS_BEING_RAIDED_WAR_SUPPORT_IMPACT = -0.70
		NDefines.NCountry.RADAR_RANGE_MAX = 240; -- 20% higher than base.
		-- Optimization
			NDefines.NCountry.EVENT_PROCESS_OFFSET = 30 -- Performance enhancer. --TW/WTT

	-- NResistance

	-- NProduction
		NDefines.NProduction.MAX_EQUIPMENT_RESOURCES_NEED = 6   			-- Default 3
		NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 10.0				-- Default 15.0
		NDefines.NProduction.EFFICIENCY_LOSS_PER_UNUSED_DAY = 2 			-- Default 1
		NDefines.NProduction.RESOURCE_TO_ENERGY_COEFFICIENT = 9.0			-- Default 9.0, How much energy per coal produces
		NDefines.NProduction.BASE_COUNTRY_ENERGY_PRODUCTION = 12.0			-- Default 10.0, The base energy production of a country
		NDefines.NProduction.ENERGY_SCALING_COST_BY_FACTORY_COUNT = 0.0225	-- Default 0.0225, do not use 0.03375, Scales energy cost based on the total number of factories
		NDefines.NProduction.BASE_ENERGY_COST = 0.25						-- Default 0.25, How much energy per factory consumes
		NDefines.NProduction.BASE_FACTORY_SPEED = 2.50						-- Default 5.00
		NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 4.5					-- Default 9.00
		NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 2.5					-- Default 5.00
		NDefines.NProduction.BASE_FACTORY_START_EFFICIENCY_FACTOR = 1		-- Default 10
		NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 10		-- Default 50
		NDefines.NCountry.BASE_MAX_COMMAND_POWER = 120.0					-- Default 80

	-- NMarket

	-- NTechnology
		NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 2 -- Consider Changing
		NDefines.NTechnology.MAX_TECH_SHARING_BONUS = 1.0

	-- NPolitics

	-- NBuildings
		NDefines.NBuildings.ANTI_AIR_SUPERIORITY_MULT = 5.0
		NDefines.NBuildings.SAM_MISSION_SUPERIORITY = 5.0

		NDefines.NBuildings.BASE_FACTORY_REPAIR = 1.0				-- Default 1.0
		NDefines.NBuildings.BASE_FACTORY_REPAIR_FACTOR = 1.0		-- Default 2.0

		NDefines.NBuildings.MAX_BUILDING_LEVELS = 66
		NDefines.NBuildings.MAX_SHARED_SLOTS = 66
		NDefines.NBuildings.DESTRUCTION_COOLDOWN_IN_WAR = 90		-- Default 30

		NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.12	-- Was 0.15, we increase this to improve industrialization.
		NDefines.NBuildings.SUPPLY_ROUTE_RESOURCE_BONUS = 0.20		-- Was 0.20, we increase this to improve industrialization.

	-- NDeployment

	-- NMilitary
		NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
		NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
		NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999

		NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 18	-- how many divisions a corps commander is limited to. 0 = inf  < 0 = blocked
		NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 4			-- how many armies a field marshall is limited to. 0 = inf, < 0 = blocked	
		NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 18		-- how many divisions a field marshall is limited to. 0 = inf  < 0 = blocked
		NDefines.NPolitics.ARMY_LEADER_COST = 3					-- command power cost for recruiting new leaders, 'this value' * number_of_existing_leaders_of_type	
		NDefines.NMilitary.RELIABILITY_WEATHER = 6.0			-- how much reliability is afffecting weather impact
		NDefines.NMilitary.BASE_FORT_PENALTY = -0.10			-- fort penalty
		NDefines.NMilitary.UNIT_UPKEEP_ATTRITION = 0.03 		-- Constant attrition value applied to armies.

		NDefines.NMilitary.ARMY_FUEL_COST_MULT = 0.250			-- fuel cost multiplier for all army related stuff

	-- NAir
		NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 1000			-- 10x higher than base.
		NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 1000			-- 10x higher than base.
		NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 1000			-- 10x higher than base.
		NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 8000			-- 10x higher than base.
		NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 1000			-- 10x higher than base.
		NDefines.NAir.DETECT_CHANCE_FROM_RADARS = 0.60			-- 20% higher than base.
		NDefines.NAir.DETECT_EFFICIENCY_FROM_RADAR = 0.84		-- 20% higher than base.

		NDefines.NAir.FUEL_COST_MULT = 0.175					-- fuel multiplier for all air missions

		NDefines.NAir.MAX_QUICK_WING_SELECTION = 5				-- Max possible selection for airwing quick deploy


	-- NNavy
		NDefines.NNavy.MAX_CAPITALS_PER_AUTO_TASK_FORCE = 10
		NDefines.NNavy.BEST_CAPITALS_TO_CARRIER_RATIO = 2

		NDefines.NNavy.FUEL_COST_MULT = 0.100		-- fuel multiplier for all naval missions

	-- NRailwayGun

	-- NTrade
		NDefines.NTrade.BASE_LAND_TRADE_RANGE = 200 -- 5x lower than base.

	-- NAI
		-- Days between Updates Start --
			NDefines.NAI.AI_UPDATE_ROLES_FREQUENCY_HOURS = 168 				-- Default 48
			NDefines.NAI.UPDATE_SUPPLY_BOTTLENECKS_FREQUENCY_HOURS = 168 	-- Default 168
			NDefines.NAI.UPDATE_SUPPLY_MOTORIZATION_FREQUENCY_HOURS = 168 	-- Default 52

			NDefines.NAI.EQUIPMENT_MARKET_BASE_MARKET_RATIO = 0.35
			NDefines.NAI.EQUIPMENT_MARKET_UPDATE_FREQUENCY_DAYS = 30 		-- Default 11

			NDefines.NAI.FIX_SUPPLY_BOTTLENECK_SATURATION_THRESHOLD = 0.75
		-- DBU End --
		NDefines.NAI.CONSTRUCTION_PRIO_INFRASTRUCTURE = 0.20
		NDefines.NAI.CONSTRUCTION_PRIO_CIV_FACTORY = 0.80
		NDefines.NAI.CONSTRUCTION_PRIO_MIL_FACTORY = 0.70
		NDefines.NAI.CONSTRUCTION_PRIO_RAILWAY_GUN_REPAIR = 15.00
		NDefines.NAI.CONSTRUCTION_PRIO_UNSPECIFIED = 0.50
		NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_OCCUPIED_TERRITORY = 0.50
		NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_REPAIRING = 0.60			-- Default 0.30

		NDefines.NAI.AREA_DEFENSE_SETTING_VP = false
		NDefines.NAI.AREA_DEFENSE_SETTING_PORTS = true
		NDefines.NAI.AREA_DEFENSE_SETTING_AIRBASES = false
		NDefines.NAI.AREA_DEFENSE_SETTING_BORDERS = false
		NDefines.NAI.AREA_DEFENSE_SETTING_FORTS = true					-- Default false
		NDefines.NAI.AREA_DEFENSE_SETTING_COASTLINES = true
		NDefines.NAI.AREA_DEFENSE_SETTING_RAILWAYS = false
		NDefines.NAI.AREA_DEFENSE_SETTING_FACILITY = false
		-- Optimization
			NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_BASE = 100
			NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0
			NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_PENALTY = 0
			NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROLLED = 0
			NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROL_DIFF = 0

		---------------------------
		-- aNCFO AI
		---------------------------
			--------------------------------------------------------------------------------------------------------------
			-- AGGRESSIVENESS
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.AGGRESSIVENESS_CHECK_BASE = 1.4               -- Encourages more aggressive stance overall
			NDefines.NAI.AGGRESSIVENESS_CHECK_EASY_TARGET = -0.7       -- Makes AI take bigger risks vs weak nations
			NDefines.NAI.AGGRESSIVENESS_CHECK_CAREFUL = 0.8            -- More willing to stop being cautious
			NDefines.NAI.AGGRESSIVENESS_CHECK_PARTLY_FORTIFIED = 1.8  -- Requires less strength to attempt balanced attack
			NDefines.NAI.AGGRESSIVENESS_CHECK_PARTLY_FORTIFIED_WEAK_POINTS = 0.6 -- Encourages exploiting weaknesses more
			NDefines.NAI.AGGRESSIVENESS_CHECK_FULLY_FORTIFIED = 8.0    -- Less conservative vs strongholds
			NDefines.NAI.AGGRESSIVENESS_CHECK_FULLY_FORTIFIED_POCKET = 2.0 -- Pushes AI to kill off encircled enemies sooner

			--------------------------------------------------------------------------------------------------------------
			-- RESEARCH
			--------------------------------------------------------------------------------------------------------------

			NDefines.NAI.XP_RATIO_REQUIRED_TO_RESEARCH_WITH_XP = 3.0		-- AI will at least need this amount of xp compared to cost of a tech to reserch it with XP			
			NDefines.NAI.RESEARCH_WITH_XP_AI_WEIGHT_MULT = 1.5 				-- AI will bump score of a research with this mult if it can use XP

			NDefines.NAI.RESEARCH_NAVAL_DOCTRINE_NEED_GAIN_FACTOR = 0.075 -- Multiplies value based on relative naval industry size / country size.

			NDefines.NAI.RESEARCH_NEW_WEIGHT_FACTOR = 0.5 			-- Impact of previously unexplored tech weights. Higher means more random exploration.
			NDefines.NAI.RESEARCH_BASE_DAYS = 60					-- AI adds a base number of days when weighting completion time for techs to ensure it doesn't only research quick techs


			NDefines.NAI.RESEARCH_LAND_DOCTRINE_NEED_GAIN_FACTOR = 0.12 -- Multiplies value based on relative military industry size / country size.

			NDefines.NAI.RESEARCH_BONUS_FACTOR = 2.0

			---------------------------------------------------------------------------------------------
			-- DESIGNS
			---------------------------------------------------------------------------------------------


			-- The AI uses the below values when selecting which design to make among the types that use the tank designer
			-- (the tank designer DLC feature must be active). For each role, the highest priority AI design that can be
			-- created, if any, is assigned a weight. Any design with a weight of zero or a weight that falls below the
			-- cutoff is dropped. A random design is then picked from the remaining.
			-- Weight is calculated as AlternativeFactor * DemandFactor.
			-- An "alternative" is a producible design of the same archetype (each specialized type is its own archetype).

			NDefines.NAI.LAND_DESIGN_ALTERNATIVE_ABSENT = 1000000
			NDefines.NAI.LAND_DESIGN_ALTERNATIVE_OF_LESSER_TECH = 10000
			NDefines.NAI.LAND_DESIGN_ALTERNATIVE_OF_EQUAL_TECH = 100
			NDefines.NAI.LAND_DESIGN_ALTERNATIVE_OF_GREATER_TECH = 1

			-- If a template may be reinforced with the archetype it's considered to be "demanded". If multiple conditions
			-- are met, e.g. it's both in the field and in training, the largest value is used.

			NDefines.NAI.LAND_DESIGN_DEMAND_FIELD_DIVISION = 20
			NDefines.NAI.LAND_DESIGN_DEMAND_TRAINING_DIVISION = 15
			NDefines.NAI.LAND_DESIGN_DEMAND_GARRISON_DIVISION = 10
			NDefines.NAI.LAND_DESIGN_DEMAND_UNUSED_TEMPLATE = 1
			NDefines.NAI.LAND_DESIGN_DEMAND_ABSENT = 1

			-- If a design with a weight when divided by the largest weight falls below this value it's excluded from the
			-- selection. Valid values are in the range [0, 1] inclusive.

			--------------------------------------------------------------------------------------------------------------
			-- DIVISION PRODUCTION & UPGRADES
			--------------------------------------------------------------------------------------------------------------

			NDefines.NAI.DEPLOYED_UNIT_MANPOWER_RATIO_TO_BUFFER_WARTIME = 0.2 				-- deployment will try to buffer a ratio of deployed manpower (for reinforcements) during war time
			NDefines.NAI.DEPLOYED_UNIT_MANPOWER_RATIO_TO_BUFFER_PEACETIME = 0.1     		-- deployment will try to buffer a ratio of deployed manpower (for reinforcements) during peace time

				-- Calculating wanted nr of divisions
			NDefines.NAI.WANTED_UNITS_THREAT_BASE = 0.7                             -- If no threat, multiply min wanted units by this
			NDefines.NAI.WANTED_UNITS_WAR_THREAT_FACTOR = 1.5                       -- Factor threat with this if country is at war. this value is overriden by the value in ideology database if that value exceedes this.
			NDefines.NAI.WANTED_UNITS_WEIGHT_MANPOWER = 0.75                         -- Weight of manpower availability when computing final nr wanted units
				-- End of calculating wanted nr of divisions


			NDefines.NAI.WANTED_UNITS_MAX_WANTED_CAP = 1000



			NDefines.NAI.MIN_MANPOWER_TO_BUILD_UNITS = 0.7

			--------------------------------------------------------------------------------------------------------------
			-- EQUIPMENT PRODUCTION
			--------------------------------------------------------------------------------------------------------------

			NDefines.NAI.NEEDED_NAVAL_FACTORIES_EXPENSIVE_SHIP_BONUS = 1000
			NDefines.NAI.PRODUCTION_WAIT_TO_FINISH_IF_CHEAP = 0.75

			NDefines.NAI.NAVAL_BASES_SHIP_FACTOR = 1000				-- The extent to which number of naval bases play into amount of sips a nation wants
			NDefines.NAI.NAVAL_STATES_SHIP_FACTOR = 1000			-- The extent to which number of states play into amount of sips a nation wants

			NDefines.NAI.PRODUCTION_UNAVAILABLE_RESORCE_FACTORY_FACTOR = 0.5


			--------------------------------------------------------------------------------------------------------------
			-- FUEL
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_ARMY_MAX_CONSUMPTION = 120
			NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_NAVY_MAX_CONSUMPTION = 120

			--------------------------------------------------------------------------------------------------------------
			-- DIPLOMACY
			--------------------------------------------------------------------------------------------------------------

			NDefines.NAI.DIPLOMACY_SEND_MAX_FACTION = 0.0
			NDefines.NAI.MAX_REQUEST_EXPEDITIONARIES_ARMY_RATIO = 0.0
			NDefines.NAI.GENERATE_WARGOAL_THREAT_BASELINE = 0.6
			NDefines.NAI.DIPLOMACY_REJECTED_WAIT_MONTHS_BASE = 1	-- AI will not repeat offers until at least this time has passed, and at most the double

			---------------Volunteers Stuff---------------
			NDefines.NAI.SEND_VOLUNTEER_EVAL_BASE_DISTANCE = 175.0  -- How far away it will evaluate sending volunteers if not a major power
			NDefines.NAI.SEND_VOLUNTEER_EVAL_MAJOER_POWER = 1.0 	-- How willing major powers are to send volunteers.
			NDefines.NAI.SEND_VOLUNTEER_EVAL_CONTAINMENT_FACTOR = 0.2 -- How much AI containment factors into its evaluation of sending volunteers.

			NDefines.NAI.DIPLO_PREFER_OTHER_FACTION = -400		-- The country has yet to ask some other faction it would prefer to be a part of.
			NDefines.NDiplomacy.NOT_READY_FOR_WAR_BASE = -500 -- AI should be unwilling to enter accept a call to war if not ready ---for war against the relevant enemies. vanilla -50 - suggested define by SensitiveDannyBoi
				
			--------------------------------------------------------------------------------------------------------------
			-- PP
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.NEW_LEADER_EXTRA_PP_FACTOR = 1 --2.0								 -- Country must have at least this many times extra PP to get new admirals or army leaders
			NDefines.NAI.DIPLOMACY_IMPROVE_RELATION_COST_FACTOR = 7.0                       -- Desire to boost relations subtracts the cost multiplied by this

			--------------------------------------------------------------------------------------------------------------
			-- LAND AI
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.EASY_TARGET_FRONT_IMPORTANCE = 7.5


			NDefines.NAI.ASSIGN_TANKS_TO_WAR_FRONT = 12.0 -- Vanilla 6.0
			NDefines.NAI.ASSIGN_TANKS_TO_NON_WAR_FRONT = 0.1 -- Vanilla 0.4

			NDefines.NAI.UPDATE_SUPPLY_MOTORIZATION_FREQUENCY_HOURS = 20 				-- Vanilla is 52  Check if activating motorization would improve supply situation this often.

			NDefines.NAI.SCARY_LEVEL_AVERAGE_DEFENSE = -1.0                               -- average front defense modifier to make it consider it as a PITA to go for

			NDefines.NAI.CANCEL_COMBAT_DISADVANTAGE_RATIO = 1.25	-- Vanilla 1.5                     -- If the enemy's advantage ratio over us during (normal) combat is more than <value>, allow canceling the attack
			NDefines.NAI.CANCEL_COMBAT_MIN_DURATION_HOURS = 60	-- Vanilla 48 						-- Only allow canceling (normal) combat if at least <value> hours have passed
			NDefines.NAI.CANCEL_INVASION_COMBAT_DISADVANTAGE_RATIO = 2.8	-- Vanilla 3.5 			-- If the enemy's advantage ratio over us during invasion combat is more than <value>, allow canceling the attack
			NDefines.NAI.CANCEL_INVASION_COMBAT_MIN_DURATION_HOURS = 72	-- Vanilla 120			-- Only allow canceling invasion combat if at least <value> hours have passed

			NDefines.NAI.REDEPLOY_DISTANCE_VS_ORDER_SIZE = 0.9 			                -- Factor applied to the path length of a unit compared to length of an order to determine if it should use strategic redeployment

			NDefines.NAI.FRONT_TERRAIN_DEFENSE_FACTOR = 7.0			-- Multiplier applied to unit defense modifier for terrain on front province multiplied by terrain importance
			NDefines.NAI.FRONT_TERRAIN_ATTACK_FACTOR = 7.0			-- Multiplier applied to unit attack modifier for terrain on enemy front province multiplied by terrain importance

			NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.60						-- Minimum org % for a unit to actively attack an enemy unit when executing a plan	
			NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.85						-- Minimum strength  % for a unit to actively attack an enemy unit when executing a plan

			NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.40						-- (LOW,MED,HIGH) corresponds to the plan execution agressiveness level.
			NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.60

			NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.30	
			NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.45	

			NDefines.NAI.PLAN_FACTION_STRONG_TO_EXECUTE = 0.35 -- Vanilla -0.5		        -- % or more of units in an order to consider ececuting the plan
			NDefines.NAI.PLAN_FACTION_NORMAL_TO_EXECUTE = 0.3  -- Vanilla -0.65					 -- % or more of units in an order to consider ececuting the plan
			NDefines.NAI.PLAN_FACTION_WEAK_TO_ABORT = 0.30  -- Vanilla -0.65		        -- % or more of units in an order to consider ececuting the plan
			NDefines.NAI.PLAN_AVG_PREPARATION_TO_EXECUTE = 0.4	-- Vanilla -0.5	            -- % or more average plan preparation before executing

			NDefines.NAI.FORTIFIED_RATIO_TO_CONSIDER_A_FRONT_FORTIFIED = 0.35
			NDefines.NAI.HEAVILY_FORTIFIED_RATIO_TO_CONSIDER_A_FRONT_FORTIFIED = 0.5

			NDefines.NAI.PLAN_ACTIVATION_SUPERIORITY_AGGRO = 10.0 --default 1.0		-- How aggressive a country is in activating a plan based on how superiour their force is.

			NDefines.NAI.DYNAMIC_STRATEGIES_THREAT_FACTOR = 8.0
			NDefines.NAI.BASE_DISTANCE_TO_CARE = 400.0

			NDefines.NAI.ASSIGN_MOUNTAINEERS_TO_MOUNTAINS = 50.0

			------ AI Superchargers -----------
			-- These 4 defines below genuinely make the AI somehow smarter and supercharges it with the right values
			NDefines.NAI.FRONT_EVAL_PERCENT_TO_ASSIST_ALLY_FRONT = 0.75  -- Vanilla 0.5  percentage of how many units the AI thinks it should have compared to an ally before considering sending units
			NDefines.NAITheatre.FRONT_EVAL_UNIT_SUPPLY_AND_ORG_LACK_IMPACT = 1.5	-- Vanilla 1.0; scale how painful the AI thinks a combined lack of supply and organization is for units	

			NDefines.NAI.MIN_AI_UNITS_PER_TILE_FOR_STANDARD_COHESION = 1.5

			NDefines.NAI.FRONT_CUTOFF_MIN_EDGE_PROXIMITY = 2	--- vanilla 2; Minimum number of provinces to the front edge to determine for cutoff oportunity.	

			NDefines.NAI.GARRISON_FRACTION = 0.0					-- DONT CHANGE THIS AS THIS FUCKS WITH VOLUNTEERS AND MAKE EM DO NOTHING AND BE PASSIVE How large part of a front should always be holding the line rather than advancing at the enemy
			NDefines.NAI.PLAN_ACTIVATION_MAJOR_WEIGHT_FACTOR = 1

			NDefines.NAI.ASSIGN_FRONT_ARMY_SOFT_ATTACK_FACTOR = 0.1                 -- Importance of unit's ARMY_SOFT_ATTACK stat when assigning to a front
			NDefines.NAI.ASSIGN_FRONT_ARMY_HARD_ATTACK_FACTOR = 0.1                -- Importance of unit's ARMY_HARD_ATTACK stat when assigning to a front
			NDefines.NAI.ASSIGN_FRONT_ARMY_BREAKTHROUGH_FACTOR = 0.1               -- Importance of unit's ARMY_BREAKTHROUGH stat when assigning to a front
			NDefines.NAI.ASSIGN_DEFENSE_ARMY_DEFENSE_FACTOR = 3.0                -- Importance of unit's ARMY_DEFENSE stat when assigning to an area defense order
			NDefines.NAI.ASSIGN_DEFENSE_ARMY_ENTRENCHMENT_FACTOR = 2.0              -- Importance of unit's ARMY_ENTRENCHMENT stat when assigning to an area defense order
			NDefines.NAI.ASSIGN_DEFENSE_TEMPLATE_CLASS_SCORE = 3.0                  -- Importance of unit's AI template class (AREA_DEFENSE, CAVALRY) when assigning to an area defense order
			NDefines.NAI.ASSIGN_INVASION_AMPHIBIOUS_ATTACK_FACTOR = 50.0            -- Importance of unit's amphibious attack adjuster when assigning to an invasion order
			NDefines.NAI.ORDER_ASSIGNMENT_DISTANCE_FACTOR = 100.0                     -- When the AI assigns units to orders, how much should distance be taken into account?
			NDefines.NAI.UNIT_ASSIGNMENT_STATS_IMPORTANCE = 2.0                     -- Stats score for units are multiplied by this when the AI is deciding which front they should be assigned to

			NDefines.NAI.ASSIGN_FRONT_TERRAIN_ATTACK_FACTOR = 0.1                   -- Importance of unit's terrain adjusted attack stat when assigning to a front
			NDefines.NAI.ASSIGN_FRONT_TERRAIN_DEFENSE_FACTOR = 0.1                 -- Importance of unit's terrain adjusted defense stat when assigning to a front
			NDefines.NAI.ASSIGN_FRONT_TERRAIN_MOVEMENT_FACTOR = 0.1                 -- Importance of unit's terrain adjusted movement stat when assigning to a front
			NDefines.NAI.ASSIGN_DEFENSE_TERRAIN_ATTACK_FACTOR = 0.5                 -- Importance of unit's terrain adjusted attack stat when assigning to an area defense order
			NDefines.NAI.ASSIGN_DEFENSE_TERRAIN_DEFENSE_FACTOR = 4.0               -- Importance of unit's terrain adjusted defense stat when assigning to an area defense order
			NDefines.NAI.ASSIGN_DEFENSE_TERRAIN_MOVEMENT_FACTOR = 0.5               -- Importance of unit's terrain adjusted movement stat when assigning to an area defense order

			NDefines.NAI.ENEMY_FORTIFICATION_FACTOR_FOR_FRONT_REQUESTS = 1.0		-- front unit request factor at max enemy fortification
			NDefines.NAI.ENEMY_FORTIFICATION_FACTOR_FOR_FRONT_REQUESTS_MAX = 0.1 	-- max factor that can be added by enemy fortification

			NDefines.NAI.FRONT_REASSIGN_DISTANCE = 250.0



			NDefines.NAI.AREA_DEFENSE_BASE_IMPORTANCE = 4.0



			NDefines.NAI.MIN_INVASION_ORG_FACTOR_TO_EXECUTE = 0.8
			NDefines.NAI.PLAN_FRONT_SECTION_MAX_LENGTH = 10
			NDefines.NAI.PLAN_FRONT_SECTION_MIN_LENGTH = 5

			NDefines.NAI.MAX_UNITS_FACTOR_FRONT_ORDER = 3.0
			NDefines.NAI.DESIRED_UNITS_FACTOR_FRONT_ORDER = 3.0

			NDefines.NAI.MIN_UNITS_FACTOR_FRONT_ORDER = 2.0
			NDefines.NAI.MAX_UNITS_FACTOR_INVASION_ORDER = 1.3

			NDefines.NAI.DESIRED_UNITS_FACTOR_INVASION_ORDER = 1.3
			NDefines.NAI.MIN_UNITS_FACTOR_INVASION_ORDER = 1.2

			NDefines.NAI.MANPOWER_RATIO_CAREFULNESS_THRESHOLD = 0.25	-- Vanilla 0.05 -- if manpower ratio (available/used-by-army) is less than this, start being more careful with plan execution (i.e. don't throw your men into the meat grinder if you're running out of manpower)

			NDefines.NAI.DEFAULT_SUPPLY_TRUCK_BUFFER_RATIO = 2.0	-- -- Vanilla 1.5 -- ai will set to truck buffer ratio to this. can be modified by wanted_supply_trucks min_wanted_supply_trucks ai strats

			NDefines.NAI.FORT_LEVEL_TO_CONSIDER_HIGHLY_FORTIFIED = 4

			------ Changing Careful AI -----------

			-- So I don't know a single person who actually uses the careful attack plan. Therefore i'm gonna heavily change it for the AI use.

			NDefines.NAI.PLAN_EXECUTE_CAREFUL_LIMIT = 5                -- When looking for an attack target, this score limit is required in the battle plan to consider province for attack
			NDefines.NAI.PLAN_EXECUTE_CAREFUL_MAX_FORT = 7				-- If execution mode is set to careful, units will not attack provinces with fort levels greater than or equal to this
			NDefines.NAI.PLAN_EXECUTE_SUPPLY_CHECK = { 0.5, 0.4, 0.5, 1.0, 0.6 }
			--                                                      ^^^ changed from 0.7
			--------------------------------------------------------------------------------------------------------------
			-- BATTLEPLANNER AI (KILL ME)
			--------------------------------------------------------------------------------------------------------------
			NDefines.NMilitary.PLAN_PORVINCE_PORT_BASE_IMPORTANCE = 15.0	-- Vanilla 12.0		-- Added importance for area defense province with a port
			NDefines.NMilitary.PLAN_PORVINCE_PORT_LEVEL_FACTOR = 2.5	-- Vanilla 1.5			-- Bonus factor for port level

			NDefines.NMilitary.PLAN_PROVINCE_BASE_IMPORTANCE = 2.0	-- Vanilla 2.0

			NDefines.NMilitary.PLAN_PORVINCE_AIRFIELD_BASE_IMPORTANCE = 3.0 	-- Vanilla 3.0	-- Added importance for area defense province with air field
			NDefines.NMilitary.PLAN_PORVINCE_AIRFIELD_POPULATED_FACTOR = 1.5 	-- Vanilla 1.5	-- Bonus factor when an airfield has planes on it
			NDefines.NMilitary.PLAN_PORVINCE_AIRFIELD_LEVEL_FACTOR = 0.25		-- Bonus factor for airfield level
			NDefines.NMilitary.PLAN_PORVINCE_RESISTANCE_BASE_IMPORTANCE = 10.0 -- Used when calculating the calue of defense area provinces for the battle plan system (factored by resistance level)

			NDefines.NMilitary.PLAN_AREA_DEFENSE_ENEMY_UNIT_FACTOR = -1.5	-- Vanilla -2.0		-- Factor applied to province score in area defense order per enemy unit in that province
			NDefines.NMilitary.PLAN_AREA_DEFENSE_FORT_IMPORTANCE = 0.30		-- Vanilla 0.25		-- Used when calculating the calue of defense area provinces for the battle plan system, works as multipliers on the rest
			NDefines.NMilitary.PLAN_AREA_DEFENSE_COASTAL_FORT_IMPORTANCE = 5.0		-- Vanilla 3.0	-- Used when calculating the calue of defense area provinces for the battle plan system
			NDefines.NMilitary.PLAN_AREA_DEFENSE_COAST_NO_FORT_IMPORTANCE = 2.0		-- Vanilla 1.1	-- Used when calculating the calue of defense area provinces for the battle plan system

			NDefines.NMilitary.PLAN_STICKINESS_FACTOR = 90	-- Vanilla 100.0					-- downed from 100; Factor used in unitcontroller when prioritizing units for locations
					
			NDefines.NMilitary.PLAN_BLITZ_OPTIMISM = 0.3	-- Vanilla 0.2; Additional combat balance value in favor of blitzing side when considering targets (not a combat bonus, just offsets planning)
			NDefines.NMilitary.MIN_BALANCE_SCORE_TO_PROCEED_ATTACK = 0.15	-- Vanilla 0.2; A combat balance score of less than this will prevent auto attacking

			NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 300 -- 300.0 -- (was 12.0)	-- The higher the value, the less it should crowd provinces with multiple attacks.		#WICHTIG
			NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 10		-- (was 2) -- The battle plan system will only automatically attack provinces in pockets that has no resistance and are no bigger than these many provinces
			NDefines.NMilitary.FRONTLINE_EXPANSION_FACTOR = 0.0 -- #MOD was 0.0 -- was 0.6,				-- When attacking along a frontline, how much should units spread out as they advance. 0.0 means head (more or less) directly to the drawn frontline, with no distractions
			NDefines.NMilitary.FRONT_MIN_PATH_TO_REDEPLOY = 4 --#MOD -- was 8,					-- If a units path is at least this long to reach its front location, it will strategically redeploy.

			NDefines.NAI.FALLBACK_LOSING_FACTOR = 2.0 		-- Vanilla 1.0 -- The lower this number, the longer the AI will hold the line before sending them to the fallback line

			NDefines.NMilitary.PLAN_PROVINCE_LOW_VP_IMPORTANCE_AREA = 4.0
			NDefines.NMilitary.PLAN_PROVINCE_MEDIUM_VP_IMPORTANCE_AREA = 6.0
			NDefines.NMilitary.PLAN_PROVINCE_HIGH_VP_IMPORTANCE_AREA = 20.0
			NDefines.NMilitary.PLAN_PROVINCE_LOW_VP_IMPORTANCE_FRONT = 4.0
			NDefines.NMilitary.PLAN_PROVINCE_MEDIUM_VP_IMPORTANCE_FRONT = 6.0
			NDefines.NMilitary.PLAN_PROVINCE_HIGH_VP_IMPORTANCE_FRONT = 8.0
			NDefines.NMilitary.PLAN_AREA_DEFENSE_ENEMY_CONTROLLER_SCORE = 30.0
			NDefines.NMilitary.PLAN_MAX_PROGRESS_TO_JOIN = 0.60

			NDefines.NMilitary.PLAN_PROVINCE_PORT_BASE_IMPORTANCE = 15.0		-- increased from 9.0 ; Added importance for area defense province with a port
			NDefines.NMilitary.PLAN_PROVINCE_PORT_LEVEL_FACTOR = 0.5			-- Bonus factor for port level
			NDefines.NMilitary.PLAN_PROVINCE_AIRFIELD_BASE_IMPORTANCE = 3.0	-- Added importance for area defense province with air field
			NDefines.NMilitary.PLAN_PROVINCE_AIRFIELD_POPULATED_FACTOR = 1.5	-- Bonus factor when an airfield has planes on it
			NDefines.NMilitary.PLAN_PROVINCE_AIRFIELD_LEVEL_FACTOR = 0.25		-- Bonus factor for airfield level
			NDefines.NMilitary.PLAN_PROVINCE_RESISTANCE_BASE_IMPORTANCE = 10.0 -- Used when calculating the calue of defense area provinces for the battle plan system (factored by resistance level)

			NDefines.NMilitary.PLAN_PROVINCE_LOW_VP_DEFENSE_IMPORTANCE = 4.0
			NDefines.NMilitary.PLAN_PROVINCE_MEDIUM_VP_DEFENSE_IMPORTANCE = 6.0
			NDefines.NMilitary.PLAN_PROVINCE_HIGH_VP_DEFENSE_IMPORTANCE = 20.0

			--------------------------------------------------------------------------------------------------------------
			-- GARRISON AI
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.AREA_DEFENSE_SETTING_VP = true								-- Vanilla is false
			NDefines.NAI.AREA_DEFENSE_SETTING_PORTS = true								-- Vanilla is true
			NDefines.NAI.AREA_DEFENSE_SETTING_AIRBASES = false							-- Vanilla is false
			NDefines.NAI.AREA_DEFENSE_SETTING_BORDERS = false							-- Vanilla is false
			NDefines.NAI.AREA_DEFENSE_SETTING_FORTS = false								-- Vanilla is false
			NDefines.NAI.AREA_DEFENSE_SETTING_COASTLINES = false						        -- Vanilla is true
			NDefines.NAI.AREA_DEFENSE_SETTING_RAILWAYS = false							-- Vanilla is false
			NDefines.NAI.AREA_DEFENSE_SETTING_FACILITY = false							-- Vanilla is false

			NDefines.NAI.MAX_UNITS_FACTOR_AREA_ORDER = 2.0 --vanilla 0.75 -- Factor for max number of units to assign to area defense orders
			NDefines.NAI.DESIRED_UNITS_FACTOR_AREA_ORDER = 1.5 --vanilla 0.7 -- Factor for desired number of units to assign to area defense orders
			NDefines.NAI.MIN_UNITS_FACTOR_AREA_ORDER = 1.0 --vanilla 1.0 -- Factor for min number of units to assign to area defense orders

			-- VP weights (Peacetime / Medium Threat / High Threat)
			NDefines.NAI.AREA_DEFENSE_CAPITAL_PEACE_VP_WEIGHT = { 1.0, 1.0, 1.0 }  -- Keep capital important
			NDefines.NAI.AREA_DEFENSE_CAPITAL_VP_WEIGHT = { 0.0, 0.5, 1.0 }        -- CHANGED: Reduced from 1.5/2.0
			NDefines.NAI.AREA_DEFENSE_HOME_VP_WEIGHT = { 0.0, 0.25, 0.5 }          -- CHANGED: Reduced from 0.75/1.0
			NDefines.NAI.AREA_DEFENSE_OTHER_VP_WEIGHT = { 0.0, 0.1, 0.3 }          -- CHANGED: Reduced from 0.5/1.0

			-- Coast weights (mostly disabled now since COASTLINES = false)
			NDefines.NAI.AREA_DEFENSE_CAPITAL_PEACE_COAST_WEIGHT = { 0.0, 0.0, 0.0 }
			NDefines.NAI.AREA_DEFENSE_CAPITAL_COAST_WEIGHT = { 0.0, 0.1, 0.3 }
			NDefines.NAI.AREA_DEFENSE_HOME_COAST_WEIGHT = { 0.0, 0.05, 0.15 }
			NDefines.NAI.AREA_DEFENSE_OTHER_COAST_WEIGHT = { 0.0, 0.0, 0.0 }

			-- Base weights
			NDefines.NAI.AREA_DEFENSE_CAPITAL_PEACE_BASE_WEIGHT = { 0.0, 0.0, 0.0 }
			NDefines.NAI.AREA_DEFENSE_CAPITAL_BASE_WEIGHT = { 0.5, 1.0, 1.5 }     -- CHANGED: Reduced high-threat
			NDefines.NAI.AREA_DEFENSE_HOME_BASE_WEIGHT = { 0.5, 0.75, 1.0 }       -- CHANGED: Reduced high-threat
			NDefines.NAI.AREA_DEFENSE_OTHER_BASE_WEIGHT = { 0.5, 0.5, 0.75 }      -- CHANGED: Reduced high-threat

			NDefines.NAI.AREA_DEFENSE_CIVIL_WAR_IMPORTANCE = 1.0                  -- CHANGED: Treat civil wars as normal wars

			--------------------------------------------------------------------------------------------------------------
			-- NAVY AI
			--------------------------------------------------------------------------------------------------------------
			NDefines.NNavy.MAX_CAPITALS_PER_AUTO_TASK_FORCE = 24 -- 5							-- maximum number of capital ships the auto-task force creation will put together when designing SurfaceActionGroup
			NDefines.NNavy.MAX_SUBMARINES_PER_AUTO_TASK_FORCE = 96 -- 30						-- maximum number of submarines the auto-task force creation will put together when designing wolfpack
			NDefines.NNavy.BEST_CAPITALS_TO_SCREENS_RATIO = 0.5 -- 0.25 							-- capitals / screens ratio used for creating FEX groups in naval combat

			NDefines.NAI.CAPITALS_TO_CARRIER_RATIO = 1				-- capital to carrier count in carrier taskfoces 원래 1.5

			NDefines.NAI.MIN_SUPPORT_SHIP_RATIO = 0.5 -- 0.7                   -- if support ship ratio is below this, steal other ships.
			NDefines.NAI.MIN_MAIN_SHIP_RATIO_TO_REINFORCE = 0.5         -- the main ships will be tried to reinforce this level.
			NDefines.NAI.MIN_SUPPORT_SHIP_RATIO_TO_REINFORCE = 0.5 -- 0.9      -- the support ships will be tried to reinforce this level.
			NDefines.NAI.MIN_MAIN_SHIP_TO_SPARE = 0.5 -- 0.7                   -- can only steal ships from a task force if their main ship ratio is above this.
			NDefines.NAI.MIN_SUPPORT_SHIP_TO_SPARE = 0.5 -- 1.0                -- can only steal ships from a task force if their support ship ratio is above this.
			NDefines.NAI.MIN_MAIN_SHIP_RATIO_TO_MERGE = 0.5 -- 0.7             -- try merge task force if main ship ratio is lower than this.
			NDefines.NAI.MAX_MAIN_SHIP_RATIO_TO_MERGE = 1.0 -- 1.001           -- if resulting main ship ratio would be at most this, allow merging into this task force.

			NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO_MAX_MINES = 250 -- highest mines for highest prio for mine missions

			NDefines.NAI.MISSING_CONVOYS_BOOST_FACTOR = 75.0

			NDefines.NAI.NAVAL_SHIP_AIR_IMPORTANCE = 5
			NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_PATROLLING = 50

			NDefines.NAI.NAVAL_MISSION_MINES_PLANTING_NEAR_OWNED = 80000
			NDefines.NAI.NAVAL_MISSION_MINES_SWEEPING_NEAR_OWNED = 100000

			-------------------------
			-- naval invasions
			-------------------------
			NDefines.NAI.ENEMY_NAVY_STRENGTH_DONT_BOTHER = 1.5							-- If the enemy has a navy at least these many times stronger that the own, don't bother invading

			NDefines.NAI.MIN_INVASION_AREA_SIZE_FOR_FLOATING_HARBORS = 2 -- vanilla 15   -- AI will consider using floating harbors for naval invasion if invasion area is larger than this many provinces
			NDefines.NAI.MAX_DISTANCE_NAVAL_INVASION = 400 -- 200				 -- AI is extremely unwilling to plan naval invasions above this naval distance limit.
			NDefines.NAI.INVASION_COASTAL_PROVS_PER_ORDER = 6 --24								-- AI will consider one extra invasion per number of provinces stated here (num orders = total coast / this)

			-------------------------
			-- convoy escorts
			-------------------------
			NDefines.NAI.REGION_THREAT_LEVEL_TO_AVOID_REGION = 25 * 5 -- 25 * 10		-- How much threat must be generated in region ( by REGION_THREAT_PER_SUNK_CONVOY ) so the AI
			NDefines.NAI.REGION_THREAT_LEVEL_TO_BLOCK_REGION = 25 * 200 -- 25 * 100		-- How much threat must be generated in region ( by REGION_THREAT_PER_SUNK_CONVOY ) so the AI will decide to mark the region as avoid

			NDefines.NAI.CONVOY_ESCORT_MUL_FROM_NO_CONVOYS = 0 -- score multiplier when no convoys are around

			NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_CONVOY_DEFENSE_MAX_CONVOY_THREAT = 500 -- 1500 -- AI will increase screen assignment for escort missions as threate increases

			NDefines.NAI.MAX_SCREEN_FORCES_FOR_INVASION_SUPPORT = 0.2 -- 0 -- max ratio of screens forces to be used in naval invasion missions
			NDefines.NAI.MAX_CAPITAL_FORCES_FOR_INVASION_SUPPORT = 0.2 -- 0 -- max ratio of capital forces to be used in naval invasion missions
			NDefines.NAI.MAX_PATROL_TO_STRIKE_FORCE_RATIO = 8.0 -- 4.0	-- maximum patrol/strike force ratio

			NDefines.NAI.PATROL_FLEETS_PER_INVASION_REGION_ON_PATH = 4 -- 2			-- How many STL patrol fleet templates should the AI try to use when generating dominance
			NDefines.NAI.DANGEROUS_DISTANCE_TO_CAPITAL = 500.0 -- 1000.0					-- Distance in pixels from the target province to capital location where the AI will add the naval invasion defense importance


			NDefines.NAI.ESTIMATED_CONVOYS_PER_DIVISION = 18 -- Not always correct, but mainly used to make sure AI does not go crazy vanilla 6
			NDefines.NAI.NAVAL_MISSION_INVASION_BASE = 30000 -- 1000 -- Base score for region with naval invasion (modified dynamically by prioritizing orders)

			--------------------------------------------------------------------------------------------------------------
			-- AIR AI
			--------------------------------------------------------------------------------------------------------------
			-------------------------
			-- Land combat
			-------------------------
			NDefines.NAir.AI_ALLOWED_PLANES_KEPT_IN_RESERVE = 0.0

			NDefines.NAI.LAND_COMBAT_CAS_PER_COMBAT = 110
			NDefines.NAI.LAND_COMBAT_CAS_PER_ENEMY_ARMY = 20
			NDefines.NAI.LAND_COMBAT_ANTI_LOGISTICS_PER_ENEMY_ARMY = 0.10

			NDefines.NAI.AI_FRACTION_OF_FIGHTERS_RESERVED_FOR_INTERCEPTION = 0
			NDefines.NAI.LAND_COMBAT_AIR_SUPERIORITY_IMPORTANCE = 1
			NDefines.NAI.LAND_DEFENSE_INTERCEPTORS_PER_BOMBERS = 1.4

			NDefines.NAI.LAND_COMBAT_ENEMY_LAND_FORTS_AIR_IMPORTANCE = 10
			NDefines.NAI.LAND_COMBAT_BOMBERS_PER_COASTAL_FORT_LEVEL = 10

			NDefines.NAI.LAND_COMBAT_IMPORTANCE_SCALE = 2.5

			-------------------------
			-- Defense
			-------------------------
			NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_BOMBERS = 1.0		-- Original = 1 Amount of air interceptor planes requested per enemy bomber
			NDefines.NAI.LAND_DEFENSE_CIVIL_FACTORY_IMPORTANCE = 50 -- 50			-- Strategic importance of civil factories
			NDefines.NAI.LAND_DEFENSE_MILITARY_FACTORY_IMPORTANCE = 70 -- 70		-- Strategic importance of military factories
			NDefines.NAI.LAND_DEFENSE_NAVAL_FACTORY_IMPORTANCE = 30 -- 30			-- Strategic importance of naval factories


			NDefines.NAI.LAND_DEFENSE_AIR_SUPERIORITY_IMPORTANCE = 0.8
			NDefines.NAI.LAND_DEFENSE_INTERSEPTORS_PER_PLANE = 0
			NDefines.NAI.LAND_DEFENSE_AA_IMPORTANCE_FACTOR = 1.0
			NDefines.NAI.LAND_DEFENSE_INFRA_IMPORTANCE_FACTOR = 0.7

			-------------------------
			-- Str bombing
			-------------------------
			NDefines.NAI.STR_BOMB_AIR_SUPERIORITY_IMPORTANCE = 0.5
			NDefines.NAI.STR_BOMB_FIGHTERS_PER_PLANE = 1.5

			-------------------------
			-- Naval air
			-------------------------
			NDefines.NAI.NAVAL_IMPORTANCE_SCALE = 1.2 --0.65						-- Naval total importance scale (every naval score get's multiplied by it)
			NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_RAIDING = 40 --10.0		-- Amount of naval patrol planes per ship on a convoy raid mission
			NDefines.NAI.NAVAL_SHIP_AIR_IMPORTANCE = 2.0
			NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_RAIDING = 30.0
			NDefines.NAI.NAVAL_COMBAT_TRANSFER_AIR_IMPORTANCE = 500.0

			--------------------------------------------------------------------------------------------------------------
			-- AMRS MARKET AI
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.EQUIPMENT_MARKET_MAX_CIVS_FOR_PURCHASES_RATIO = 0.2            -- Ratio of available civilian factories to max use for equipment purchases (0.2 = 20 %, so 50 available civs would mean max ca 10 civs to spend on purchases at any one time). Gets modified by equipment_market_spend_factories AI strategy.
			NDefines.NAI.EQUIPMENT_MARKET_NR_DELIVERIES_SOFT_MAX = 7                   -- AI tries to adjust assigned factories and amount of equipment to keep nr deliveries at max this
				
			--------------------------------------------------------------------------------------------------------------
			-- LEND LEASE AI
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.DIPLOMACY_LEND_LEASE_MONTHS_TO_CANCEL = 16

			NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0


			NDefines.NAI.MINIMUM_FUEL_DAYS_TO_ASK_LEND_LEASE = 60								-- AI will accept to lend lease fuel only if the player have less fuel than this number multiply by his max daily consumption.
			NDefines.NAI.MINIMUM_FUEL_DAYS_TO_ACCEPT_LEND_LEASE = 60					 		-- AI will accept to lend lease fuel only if they have more fuel than this number multiply by their max daily consumption. Note that for a GiE asking to its host, we divide this number by 2.

			NDefines.NAI.PROPOSE_LEND_LEASE_AIDESIRE_SAME_IDEOLOGY_CIVIL_WAR = 50	-- Vanilla 25; Added to AI desire to propose lend lease if recipent is same ideology and they are currently in civil war

			--------------------------------------------------------------------------------------------------------------
			-- INTELLIGENCE AGENCY AI
			--------------------------------------------------------------------------------------------------------------
			NDefines.NOperatives.AGENCY_AI_BASE_NUM_FACTORIES = 10.0 --25.0
			NDefines.NOperatives.AGENCY_AI_PER_UPGRADE_FACTORIES = 2.0 --6.0

			--------------------------------------------------------------------------------------------------------------
			-- AI SUPPLY/LOGISTICS DEFINES 
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.MAX_DIST_PORT_RUSH = 40.0	--default 20.0			-- If a unit is in enemy territory with no supply it will consider nearby ports within this distance.

			NDefines.NAI.AVERAGE_SUPPLY_USE_PESSIMISM = 2.0  -- Increased multiplier to reflect realistic supply usage.


			--------------------------------------------------------------------------------------------------------------
			-- UNIT ASSIGNMENT & FRONT MANAGEMENT
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.REVISITED_PROV_BOOST_FACTOR = 6   -- Vanilla 4 --When the AI picks units for a front, it prioritises units already nearby.	
			NDefines.NAI.REASSIGN_TO_ANOTHER_FRONT_IF_IN_COMBAT_FACTOR = 0.05 -- Vanilla 0.2	--Factor for reassigning to another front if in combat. 0.0 < X < 1.0 means reluctant, X > 1.0 means want to.
			NDefines.NAI.REASSIGN_TO_ANOTHER_FRONT_FACTOR = 0.3  -- Vanilla 0.5	--Factor for reassigning to another front. 0.0 < X < 1.0 means reluctant, X > 1.0 means want to.	
			NDefines.NAI.PLAN_VALUE_BONUS_FOR_MOVING_UNITS = 0.45	-- Vanilla 0.35  --AI plans gets a bonus when units are not moving and ready to fight
			NDefines.NAI.PLAN_FRONTUNIT_DISTANCE_FACTOR	= 8.0	-- Vanilla 10.0  --Factor for candidate units distance to front positions.

			--------------------------------------------------------------------------------------------------------------
			-- LEADER ASSIGNMENT
			--------------------------------------------------------------------------------------------------------------
			NDefines.NAI.ARMY_LEADER_ASSIGN_EMPTYNESS_MALUS	= 0.3	-- Vanilla 0.2 ---Factor for avoiding assigning leaders that can lead large armies to small armies (a value of 0.2 reduces the score by max 20 %)
			NDefines.NAI.ARMY_LEADER_ASSIGN_ARMY_ARMOR_SPEED_FACTOR	= 30.0	-- Vanilla 20.0 --Importance of general's ARMY_ARMOR_SPEED_FACTOR modifier (proportional to armor ratio in the army)	
			NDefines.NAI.ARMY_LEADER_ASSIGN_ARMY_ARMOR_ATTACK_FACTOR = 30.0		-- Vanilla 20.0 ---Importance of general's ARMY_ARMOR_ATTACK_FACTOR modifier (proportional to armor ratio in the army)	
			NDefines.NAI.ARMY_LEADER_ASSIGN_BOOST_ARMOR_SKILL = 25.0	-- Vanilla 20.0	---Importance of general's trait where armor skill is boosted, e.g. armor_officer which boosts panzer_leader (proportional to armor ratio in the army)	
			NDefines.NAI.ARMY_LEADER_ASSIGN_ARMOR_LEADER_IF_NO_ARMOR = -1.0		-- Vanilla -0.5   ---Avoid assigning a general with armor skills to an army with no armor (can be negative)
			NDefines.NAI.ARMY_LEADER_ASSIGN_AMPHIBIOUS_INVASION	= 6.0	 -- Vanilla 1.0 --If involved in invasion, importance of general's AMPHIBIOUS_INVASION modifier	
			NDefines.NAI.ARMY_LEADER_ASSIGN_NAVAL_INVASION_PREPARATION = 6.0	-- Vanilla 1.0 --If involved in invasion, importance of general's NAVAL_INVASION_PREPARATION modifier
			NDefines.NAI.ARMY_LEADER_ASSIGN_KEEP_CURRENT_LEADER_FACTOR = 2.0		-- Vanilla 1.2        -- Boosts the score for keeping the current leader. Value > 1.0 favors the current leader.
			NDefines.NAI.ARMY_LEADER_ASSIGN_DONT_STEAL_OTHER_FACTOR = 0.25		-- Vanilla 0.75          -- Reduces the score for leaders assigned elsewhere. Value < 1.0 discourages reassigning these leaders.

			--------------------------------------------------------------------------------------------------------------
			-- AI FORCE CONCENTRATION DEFINES
			--------------------------------------------------------------------------------------------------------------
			-- AIFC stands for "AI Force Concentration". Using acronym to keep define names shorter.
			NDefines.NAI.AIFC_FRESHNESS_BASE_VALUE = 35.0	-- Vanilla 45.0                           -- AIFC fronts have a "freshness value" which decreases if no progress is made. When it reaches zero, it will give up on the current target and try another.
			NDefines.NAI.AIFC_UNIT_RATIO_BASE = 0.05	-- Vanilla 0.15           mod 0.10                     -- After fulfilling minimum front unit needs, this ratio of the "extra"/desired units can be allocated to AI force concentration duty
			NDefines.NAI.AIFC_MAX_NR_FRONTS = 4                                     -- The X (this) fronts with highest AIFC score are considered for AI force concentration
			NDefines.NAI.AIFC_OFFENSIVE_DEACTIVATION_DAYS_THRESHOLD = 5             -- Deactivate the offensive order only if the conditions have been unfulfilled for this many days.
				-- Unit offensiveness score factors for AIFC. Division stats are factored by this before adding up to total score.
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_BREAKTHROUGH = 12.0	-- Vanilla 11.0
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_PIERCING = 8.0
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_SPEED = 15.0
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_INITIATIVE = 5.0
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_ORGANISATION = 1.0    -- Slightly positive: no more AI using garbage
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_HITPOINTS = 0.5
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_DEFENSE = -0.2
			NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_ENTRENCHMENT = -0.5
				-- End of unit offensiveness score factors for AIFC
				-- Strategic target scoring for AIFC
			NDefines.NAI.AIFC_TARGET_IGNORE_VP_THRESHOLD = 10                       -- VP target needs at leas this many victory points to be considered a target
			NDefines.NAI.AIFC_TARGET_VP_SCORE_FACTOR = 1.0                          -- Score for VPs increases by this for every victory point
			NDefines.NAI.AIFC_TARGET_CAPITAL_SCORE_EXTRA = 10.0		-- Vanilla 5.0                   -- Extra score for Capitals (in addition to VP score)
			NDefines.NAI.AIFC_TARGET_PERSISTED_FACTOR = 35.0   		-- Vanilla 30.0                     -- Bonus factor for persisted targets (used to incentivize AI to select target again after e.g. front lines have reformed or save file is loaded)
				-- End of strategic target scoring for AIFC
				
				-- Offensive path scoring (cost multipliers) for AIFC
			NDefines.NAI.AIFC_PATH_MAX_COST = 5.0	-- Vanilla 7.0                                  -- Only allow paths with total cost <= this. WARNING: increasing this value may cause stuttering and other performance issues (since AIFC will evaluate larger areas)
			NDefines.NAI.AIFC_PATH_COST_ADJ_NORMAL = 1.0
			NDefines.NAI.AIFC_PATH_COST_ADJ_STRAIT = 4.0
			NDefines.NAI.AIFC_PATH_COST_TRN_DESERT = 1.5
			NDefines.NAI.AIFC_PATH_COST_TRN_HILLS = 1.2
			NDefines.NAI.AIFC_PATH_COST_TRN_JUNGLE = 3.5 		-- Vanilla 3.0
			NDefines.NAI.AIFC_PATH_COST_TRN_PLAINS = 1.0		-- Vanilla 0.8
			NDefines.NAI.AIFC_PATH_COST_PER_FORT_LEVEL = 0.4                        -- This multiplier is calculated as: 1.0 + <define>*fort_level    (only for fort levels > 0)
			NDefines.NAI.AIFC_PATH_COST_HAS_NAVAL_BASE = 0.25	-- Vanilla 0.5                         -- If the province we're entering has a naval base
				-- End of offensive path scoring for AIFC

			--------------------------------------------------------------------------------------------------------------
			-- CONSTRUCTION AI
			--------------------------------------------------------------------------------------------------------------

			-------------------------------------------------------------------------------------------------------------------------------------------------
			-- AMINE'S PERSONAL TEST DEFINES
			-------------------------------------------------------------------------------------------------------------------------------------------------
			--------------------------------------
			------ Fort Behavior, Front Cohesion, War Readiness -----------
			--------------------------------------
			NDefines.NAI.DECLARE_WAR_MIN_FRONT_SIZE_TO_CONSIDER_FOR_NOT_READY = 0.08    -- vanilla 0.04
			NDefines.NAI.MIN_FRONT_SIZE_TO_CONSIDER_STANDARD_COHESION = 12              -- vanilla 8
			NDefines.NAI.FORTIFIED_MIN_ORG_FACTOR_TO_CONSIDER_A_FRONT_FORTIFIED = 0.55  -- vanilla 0.45
			NDefines.NAI.PLAN_VALUE_FORTIFICATION_LEVEL_MAX_PENALTY = 0.85              -- vanilla 1.0
			NDefines.NAI.AREA_DEFENSE_IMPORTANCE_FACTOR = 1.35                          -- vanilla 1.0

			--------------------------------------
			------ Supply-Aware AI & Training Sanity -----------
			--------------------------------------
			NDefines.NAI.DEFAULT_SUPPLY_TRAIN_NEED_FACTOR = 1.15          -- vanilla 1.0
			NDefines.NAI.START_TRAINING_SUPPLY_LEVEL = 0.55               -- vanilla 0.40
			NDefines.NAI.STOP_TRAINING_SUPPLY_LEVEL = 0.45                -- vanilla 0.30
			NDefines.NAI.MIN_SUPPLY_USE_SANITY_CAP = 150                  -- vanilla 100
			NDefines.NAI.STR_BOMB_SUPPLY_HUB_IMPORTANCE = 20              -- vanilla 10

			--------------------------------------
			------ Combat Evaluation / Targeting Logic -----------
			--------------------------------------
			NDefines.NMilitary.COMBAT_VALUE_ORG_IMPORTANCE = 1.1     -- vanilla 1
			NDefines.NMilitary.COMBAT_VALUE_STR_IMPORTANCE = 1.0      -- vanilla 1
			NDefines.NMilitary.SOFT_ATTACK_TARGETING_FACTOR = 1.15    -- vanilla 1.0
			NDefines.NMilitary.HARD_ATTACK_TARGETING_FACTOR = 1.35    -- vanilla 1.2

			--------------------------------------
			------ Theatre Generation, Merging & Unit Distribution -----------
			--------------------------------------
			NDefines.NAITheatre.AI_THEATRE_AI_FRONT_MIN_DESIRED_RATIO = 0.65         -- vanilla 0.5
			NDefines.NAITheatre.AI_THEATRE_DISTRIBUTION_MAX_SCORE = 2.4              -- vanilla 2.0
			NDefines.NAITheatre.AI_THEATRE_DISTRIBUTION_PERCENTAGE_OF_MINIMUM_UNITS_TO_KEEP = 0.35  -- vanilla 0.25
			NDefines.NAITheatre.AI_THEATRE_DISTRIBUTION_SAME_THEATRE_SCORE_MODIFIER = 0.35          -- vanilla 0.25

			NDefines.NAITheatre.AI_THEATRE_GENERATION_MINIMUM_STATE_COUNT = 4        -- vanilla 3
			NDefines.NAITheatre.AI_THEATRE_GENERATION_MAX_DISTANCE_TO_MERGE = 250   -- vanilla 200
			NDefines.NAITheatre.AI_THEATRE_BREAKDOWN_MAX_DISTANCE_TO_MERGE = 350    -- new, consistent with above
			NDefines.NAITheatre.AI_THEATRE_GENERATION_BORDER_SIZE_RESTRICTION = 9    -- vanilla 7

			--------------------------------------
			------ Air Logic -----------
			--------------------------------------
			NDefines.NAI.AIR_SUPERIORITY_FACTOR = 2.0                 -- vanilla 1.5
			NDefines.NAI.AIR_SUPERIORITY_FOR_FRIENDLY_CAS_RATIO = 0.65 -- vanilla 0.5
			NDefines.NAI.MAX_AIR_REGIONS_TO_CARE_ABOUT = 10            -- vanilla 5
			NDefines.NAI.LAND_COMBAT_ENEMY_ARMIES_AIR_IMPORTANCE = 8  -- vanilla 10
			NDefines.NAI.LAND_DEFENSE_MIN_FACTORIES_FOR_AIR_IMPORTANCE = 12 -- vanilla 8

			NDefines.NAI.NAVAL_AIR_SUPERIORITY_IMPORTANCE = 4.0        -- vanilla 3.0
			NDefines.NAI.NAVAL_COMBAT_AIR_IMPORTANCE = 20              -- vanilla 15
			NDefines.NAI.NAVAL_SHIP_IN_PORT_AIR_IMPORTANCE = 12        -- vanilla 8

			NDefines.NAI.AIR_DESIGN_ALTERNATIVE_ABSENT = 1000000            -- vanilla 1000000 in your file (insane)
			NDefines.NAI.AIR_DESIGN_ALTERNATIVE_OF_EQUAL_TECH = 100     -- vanilla 100
			NDefines.NAI.AIR_DESIGN_ALTERNATIVE_OF_GREATER_TECH = 1   -- vanilla 1
			NDefines.NAI.AIR_DESIGN_ALTERNATIVE_OF_LESSER_TECH = 10000     -- vanilla 10000

			--NDefines.NAI.AIR_DESIGN_CUTOFF_AS_PERCENTAGE_OF_MAX = 0.15 -- vanilla 0.25

			--------------------------------------
			------ Macro-Strategy: Guarantees, Calling Allies, War Entry ----------
			--------------------------------------
			NDefines.NAI.AI_GUARANTEE_DESIRE_WITH_PRESSURE_MODIFIER = -0.35   -- vanilla 0 (less spam guarantees)
			NDefines.NAI.TENSION_MIN_FOR_GUARANTEE_VS_MINOR = 10.0            -- vanilla 0.25

			NDefines.NAI.CALL_ALLY_BASE_DESIRE = 40                           -- vanilla 50
			NDefines.NAI.CALL_ALLY_WAR_LENGTH_NR_MONTHS = 6                   -- vanilla 3
			NDefines.NAI.CALL_ALLY_RELATIVE_ARMY_STRENGTH_THRESHOLD = 0.7     -- vanilla 0.5
			NDefines.NAI.CALL_ALLY_RELATIVE_INDUSTRY_STRENGTH_THRESHOLD = 0.7 -- vanilla 0.5
			NDefines.NAI.CALL_ALLY_LOSING_WAR_THRESHOLD = 0.15                -- vanilla 0.3

			NDefines.NAI.DIPLOMACY_CALL_ALLY_VALIDITY_DURATION = 75           -- vanilla 60
			NDefines.NAI.JOIN_FACTION_BOTH_LOSING = -15                       -- vanilla -30

			NDefines.NAI.MIN_DELIVERED_TRADE_FRACTION = 0.85               -- AI will cancel trade deals that are not able to deliver more than this fraction of the agreed amount   
			NDefines.NAI.MIN_AI_SCORE_TO_ECONOMY_LAW_OVERRIDE_HARD_CODED_SCORE = -100.0

			NDefines.NAI.MAX_VOLUNTEER_ARMY_FRACTION = 0.10
			NDefines.NAI.DIPLOMACY_ACCEPT_VOLUNTEERS_BASE = 150
			NDefines.NAI.DAYS_FUEL_REMAINING_TO_ENTER_FUEL_SAVING_MODE = 10
			--NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_NAVY_TRAINING = 0.60
			NDefines.NAI.TRADEABLE_FACTORIES_FRACTION = 1.0	

			NDefines.NAI.RESOURCE_WANT_PER_MISSING_BALANCE = 1.0
			NDefines.NAI.RESOURCE_WANT_PER_CONSUMED = 0.15

			--------------------------------------
			------ Supply & Front Deployment (NSupply) -----------
			--------------------------------------
			NDefines.NSupply.AI_FRONT_MAX_UNITS_ENEMY_COUNT_FACTOR = 1.05     -- vanilla 1.2
			NDefines.NAITheatre.AI_THEATRE_DISTRIBUTION_MAX_PERCENT_UNMET_DEMAND_PER_FRONT = 0.1   -- Percentage of how much fronts should request from other lower priority fronts, 0 means once a front gets hold of a unit it stays there forever until its demand is reduced, controlls shuffling of units.

			--------------------------------------
			------ Construction AI -----------
			--------------------------------------
				

			--- AI – Fuel & Trade Decisions
			NDefines.NAI.MAX_FACTORY_TO_SPARE_FOR_MISSION_FUEL_TRADE = 0.5
			NDefines.NAI.MAX_FACTORY_TO_SPARE_FOR_CRITICAL_MISSION_FUEL_TRADE = 0.5
			NDefines.NAI.MAX_FACTORY_TO_TRADE_FOR_FUEL = 0.6
			NDefines.NAI.FUEL_TRADE_PRIO_FOR_CONVOY_DEFENSE = 1
			NDefines.NAI.MAX_FACTORY_TO_SPARE_FOR_MISSION_FUEL_TRADE_IN_PEACE = 0.6
			NDefines.NAI.MAX_FACTORY_TO_SPARE_FOR_CRITICAL_MISSION_FUEL_TRADE_IN_PEACE = 0.6
			NDefines.NAI.MAX_FACTORY_TO_TRADE_FOR_FUEL_IN_PEACE = 0.6
			NDefines.NAI.FUEL_CONSUMPTION_MULT_FOR_FUEL_SAVING_MODE = 0.30
			NDefines.NAI.FUEL_CONSUMPTION_MULT_REGULAR_FUEL_MODE = 1
			NDefines.NAI.FUEL_CONSUMPTION_MULT_AGRESSIVE_FUEL_MODE = 6.0
			--NDefines.NAI.DAYS_FUEL_REMAINING_TO_ENTER_FUEL_SAVING_MODE = 60
			NDefines.NAI.DAYS_FUEL_REMAINING_TO_ENTER_FUEL_SAVING_MODE_FUEL_RATIO = 0.33
			NDefines.NAI.FUEL_RATIO_TO_EXIST_FUEL_SAVING_MODE = 0.5

			--- AI – Naval Taskforces & Priorities
			NDefines.NAI.SUB_TASKFORCE_MAX_SHIP_COUNT = 6
			NDefines.NAI.MIN_FUEL_RATIO_TO_NOT_IGNORE_STRIKE_FORCE_COST = 0.2
			NDefines.NAI.MIN_FUEL_RATIO_TO_NOT_IGNORE_INVASION_SUPPORT_COST = 0
			NDefines.NAI.NAVAL_INVADED_AREA_PRIO_DURATION = 150
			NDefines.NAI.NAVAL_INVADED_AREA_PRIO_MULT = 8.0
			NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_NAVY_TRAINING = 0.2
			NDefines.NAI.MAX_FULLY_TRAINED_SHIP_RATIO_FOR_TRAINING = 0.6

			--- AI – Lend Lease & Air Wing Requests

			NDefines.NAI.PROPOSE_LEND_LEASE_AIDESIRE_SAME_IDEOLOGY = 100
			NDefines.NAI.LENDLEASE_FRACTION_OF_PRODUCTION = 0.75
			NDefines.NAI.LENDLEASE_FRACTION_OF_STOCKPILE = 0.75
			NDefines.NAI.MINIMUM_EQUIPMENT_TO_ASK_LEND_LEASE = -100
			NDefines.NAI.MINIMUM_CONVOY_TO_ASK_LEND_LEASE = 100
			NDefines.NAI.LAND_COMBAT_CAS_PLANES_PER_ENEMY_ARMY_LIMIT = 300
			NDefines.NAI.LAND_COMBAT_BOMBERS_PER_LAND_FORT_LEVEL = 10
			NDefines.NAI.LAND_COMBAT_MIN_EXCORT_PLANES = 200
			NDefines.NAI.LAND_COMBAT_INTERCEPT_PER_PLANE = 1
			NDefines.NAI.MIN_ALLIED_DEFENSE_FACTOR_AIRWING_REQUESTS = 0.07
			NDefines.NAI.LAND_COMBAT_GUIDE_DISTANCE = 290.0
			NDefines.NAI.STR_BOMB_MIN_EXCORT_PLANES = 200
			NDefines.NAI.STR_BOMB_MIN_ENEMY_FIGHTERS_IN_AREA = 600

	-- NFocus
		-- Optimization
			NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 35

	-- NOperatives

	-- NIntel

	-- NCharacter

	-- NSupply
		NDefines.NSupply.MAX_RAILWAY_LEVEL = 5.0 -- Default 5.0

		NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_BONUS = 2.8			 -- Default 2.2
		NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_TRUCK_COST = 75.0		 -- Default 60.0
		NDefines.NSupply.SUPPLY_HUB_MOTORIZATION_MARGINAL_EFFECT_DECAY = 1.6 -- Default 1.6

		NDefines.NSupply.RAILWAY_BASE_FLOW = 15.0				-- Default 10.0
		NDefines.NSupply.RAILWAY_FLOW_PER_LEVEL = 5.0			-- Default 5.0
		NDefines.NSupply.RAILWAY_FLOW_PENALTY_PER_DAMAGED = 5.0	-- Default 5.0
		NDefines.NSupply.RAILWAY_MIN_FLOW = 1.0					-- Default 5.0

		NDefines.NSupply.NAVAL_BASE_FLOW = 5.0		-- Default 5.0
		NDefines.NSupply.NAVAL_FLOW_PER_LEVEL = 3.0	-- Default 3.0

		NDefines.NSupply.INFRA_TO_SUPPLY = 0.3					 -- Default 0.3
		NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.2				 -- Default 0.2
		NDefines.NSupply.VP_TO_SUPPLY_BONUS_CONVERSION = 0.05	 -- Default 0.05
		NDefines.NSupply.SUPPLY_FROM_DAMAGED_INFRA = 0.075		 -- Default 0.15
		NDefines.NSupply.SUPPLY_BASE_MULT = 0.2					 -- Default 0.2
		NDefines.NSupply.SUPPLY_DISRUPTION_DAILY_RECOVERY = 0.75 -- Default 1.5

		NDefines.NSupply.SUPPLY_POINTS_PER_TRAIN = 0.4	   -- Default 1.0,  Amount of supply that can fit in a train. (Trains distribute supply from capital to a supply node.)
		NDefines.NSupply.NUM_RAILWAYS_TRAIN_FACTOR = 0.075 -- Default 0.03, the train usage is scaled by railway distance between the supply node and the capital multiplied by this factor

	-- NAITheatre

	-- NIndustrialOrganisation

	-- NProject
		NDefines.NProject.RECRUIT_SCIENTIST_COST = {50, 65, 75, 80}	-- Default 25, 50, 75, 100

		NDefines.NProject.BREAKTHROUGH_DAILY_TECHNOLOGY_GAIN = 14	  -- Default 12
		NDefines.NProject.BREAKTHROUGH_DAILY_SCIENTIST_SKILL_GAIN = 7 -- Default 5
		NDefines.NProject.BREAKTHROUGH_DAILY_ROCKET_SITE_GAIN = 3	  -- Default 3
		NDefines.NProject.BREAKTHROUGH_DAILY_NUCLEAR_REACTOR_GAIN = 3 -- Default 1

	-- NRaids
		NDefines.NRaids.NUCLEAR_BOMB_PRODUCTION_SCALE = 2555.0		  -- Default 2555.0
		NDefines.NRaids.THERMONUCLEAR_BOMB_PRODUCTION_SCALE = 2255.0  -- Default 2555.0

		NDefines.NRaids.NUCLEAR_BOMB_MIN_DAMAGE_PERCENT = 0.1		  -- Default 0.1
		NDefines.NRaids.NUCLEAR_BOMB_MAX_DAMAGE_PERCENT = 0.6		  -- Default 0.9

-- VNR Naval Defines
	NDefines.NAI.MAX_SCREEN_FORCES_FOR_INVASION_SUPPORT = 0.1;

	NDefines.NNavy.HIT_PROFILE_SPEED_FACTOR = 0.3;
	NDefines.NNavy.COMBAT_BASE_HIT_CHANCE = 0.08;
	NDefines.NNavy.COMBAT_BASE_CRITICAL_CHANCE = 0.3;
	NDefines.NNavy.CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT = 0.9;
	NDefines.NNavy.CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT_FROM_AIR = 1;
	NDefines.NNavy.MIN_SHIPS_FOR_HIGHER_SHIP_RATIO_PENALTY = 66;
	NDefines.NNavy.BEST_CAPITALS_TO_SCREENS_RATIO = 0.5;
	NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CAPITALS = 2.0;
	NDefines.NNavy.ESCAPE_SPEED_PER_COMBAT_DAY = 0.15;
	NDefines.NNavy.MAX_ESCAPE_SPEED_FROM_COMBAT_DURATION = 0.60;
	NDefines.NNavy.CONVOY_ATTACK_BASE_FACTOR = 0.3;
	NDefines.NNavy.UNIT_TRANSFER_SPOTTING_SPEED_MULT = 15;
	NDefines.NNavy.NAVAL_INVASION_SPOTTING_SPEED_MULT = 30;
	NDefines.NNavy.SPOTTING_SPEED_EFFECT_FOR_INITIAL_UNIT_TRANSFER_SPOTTING = 0.5;
	NDefines.NNavy.SPOTTING_SPEED_EFFECT_FOR_INITIAL_NAVAL_INVASION_SPOTTING = 0.5;
	NDefines.NNavy.CONVOY_EFFICIENCY_MIN_VALUE = 0;
	NDefines.NNavy.CONVOY_HIT_PROFILE = 95;
	NDefines.NNavy.NAVY_PIERCING_THRESHOLDS = { 2.0, 1.0, 0.85, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.3, 0.0 }
	NDefines.NNavy.NAVY_PIERCING_THRESHOLD_CRITICAL_VALUES = { 3.0, 1.25, 1.0, 0.65, 0.55, 0.3, 0.15, 0.1, 0.05, 0.01, 0.0 }
	NDefines.NNavy.NAVY_PIERCING_THRESHOLD_DAMAGE_VALUES = { 2.0, 1.0, 0.7, 0.6, 0.45, 0.35, 0.2, 0.1, 0.05, 0.02, 0.01 }
	NDefines.NNavy.CONVOY_DEFENSE_MAX_REGION_TO_TASKFORCE_RATIO	 = 2;
	NDefines.NNavy.COMBAT_TORPEDO_CRITICAL_CHANCE = 0.4;
	NDefines.NNavy.COMBAT_MIN_DURATION = 20;
	NDefines.NNavy.CAPITAL_ONLY_COMBAT_ACTIVATE_TIME = 22;
	NDefines.NNavy.ALL_SHIPS_ACTIVATE_TIME = 30;
	NDefines.NNavy.COMBAT_CHASE_RESIGNATION_HOURS = 1;
	NDefines.NNavy.SPEED_TO_ESCAPE_SPEED = 2;
	NDefines.NNavy.SHIP_TO_FLEET_ANTI_AIR_RATIO  = 1.0;
	NDefines.NNavy.MAX_ANTI_AIR_REDUCTION_EFFECT_ON_INCOMING_AIR_DAMAGE = 0.66;
	NDefines.NNavy.NAVAL_COMBAT_AIR_LOW_AA_TARGET_SCORE = 1;
	NDefines.NNavy.ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE = 0.15;
	NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.25;
	NDefines.NNavy.TRAINING_MAX_DAILY_COUNTRY_EXP = 2;
	NDefines.NNavy.SUBMARINE_REVEAL_BASE_CHANCE = 15;
	NDefines.NNavy.SUBMARINE_BASE_TORPEDO_REVEAL_CHANCE = 0.1;
	NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_MANPOWER_FACTOR = 0.01;
	NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_PRODUCTION_COST_FACTOR = 0.04;
	NDefines.NNavy.SHORE_BOMBARDMENT_CAP = 0.5;
	NDefines.NNavy.BASE_POSITIONING = 0.5;
	NDefines.NNavy.RELATIVE_SURFACE_DETECTION_TO_POSITIONING_FACTOR = 0.05;
	NDefines.NNavy.MAX_POSITIONING_BONUS_FROM_SURFACE_DETECTION = 0.2;
	NDefines.NNavy.POSITIONING_PENALTY_FOR_SHIPS_JOINED_COMBAT_AFTER_IT_STARTS = 0.02;
	NDefines.NNavy.MAX_POSITIONING_PENALTY_FOR_NEWLY_JOINED_SHIPS = 0.2;
	NDefines.NNavy.HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR = 0.5;
	NDefines.NNavy.MAX_POSITIONING_PENALTY_FROM_HIGHER_SHIP_RATIO = 3;
	NDefines.NNavy.MAX_CARRIER_RATIO_POSITIONING_PENALTY_FACTOR = 0.2;
	NDefines.NNavy.DAMAGE_PENALTY_ON_MINIMUM_POSITIONING = 0.9;
	NDefines.NNavy.SCREENING_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 1.25;
	NDefines.NNavy.AA_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 0.75;
	NDefines.NNavy.MANPOWER_LOSS_RATIO_ON_STR_LOSS = 0.1;
	NDefines.NNavy.MANPOWER_LOSS_RATIO_ON_SUNK = 0.25;
	NDefines.NNavy.BASE_GUN_COOLDOWNS = { 1.0, 8.0, 1.0 };
	NDefines.NNavy.COMBAT_CRITICAL_DAMAGE_MULT = 8;
	NDefines.NNavy.PRIDE_OF_THE_FLEET_UNASSIGN_COST = 25;
	NDefines.NNavy.CONVOY_ATTACK_BASE_FACTOR = 0.3;
	NDefines.NNavy.EXPERIENCE_FACTOR_CONVOY_ATTACK = 0.1;
	NDefines.NNavy.TRAINING_DAILY_COUNTRY_EXP_FACTOR = 0.005;
	NDefines.NNavy.TRAINING_MAX_DAILY_COUNTRY_EXP = 1.5;
	NDefines.NNavy.NAVAL_TRANSFER_BASE_SPEED = 4;
	NDefines.NNavy.AMPHIBIOUS_INVADE_SPEED_BASE = 0.25;
	NDefines.NNavy.SUPREMACY_PER_SHIP_PER_MANPOWER = 0.001;
	NDefines.NNavy.SUPREMACY_PER_SHIP_PER_IC = 0.05;
	NDefines.NNavy.NAVAL_COMBAT_AIR_CARRIER_TARGET_SCALE = 1000;
	NDefines.NNavy.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 3;
	NDefines.NNavy.UNIT_EXPERIENCE_SCALE = 0.8;
	NDefines.NNavy.BASE_CARRIER_SORTIE_EFFICIENCY = 0.4;
	NDefines.NNavy.CARRIER_OFFENSIVE_STANCE_SORTIE_RATIO = {0.25, 0.37, 0.50, 0.62, 0.75}
	NDefines.NNavy.SHIP_SUPPORT_NEED_FACTOR = 0.25;
	NDefines.NNavy.NAVAL_DOMINANCE_STRIKE_FORCE_MULTIREGION_DECAY = 0.1;
	NDefines.NNavy.NAVAL_DOMINANCE_MINES_PLANTING_BONUS = 0.1;
	NDefines.NNavy.NAVAL_DOMINANCE_MINES_SWEEPING_BONUS = 0.1;
	NDefines.NNavy.NAVAL_DOMINANCE_SHIP_RECOVERY_CHANCE = 0.05;
	NDefines.NNavy.NAVAL_COMBAT_PLANE_MIN_STACKING_PENALTY = 150;
	NDefines.NNavy.NAVAL_COMBAT_PLANE_STACKING_PENALTY_EFFECT = 0.01;
	NDefines.NNavy.NAVAL_COMBAT_PLANE_STACKING_PENALTY_EFFECT = 0.005
	NDefines.NNavy.SHIP_SILHOUETTE_VALUE_PLANES_CARRIER = 500;
	NDefines.NNavy.COMBAT_DAMAGE_RANDOMNESS = 0.3;
	NDefines.NNavy.NAVY_VISIBILITY_BONUS_ON_RETURN_FOR_REPAIR = 0.6;
	NDefines.NNavy.SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.25;
	NDefines.NNavy.CAPITAL_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.1;
	NDefines.NNavy.GUN_HIT_PROFILES = { -- hit profiles for guns, if target ih profile is lower the gun will have lower accuracy
			75.0,	-- big guns
			105.0,	-- torpedoes
			55.0,	-- small guns
	};
	NDefines.NNavy.MISSION_DOMINANCE_RATIOS = {
			0.0, -- HOLD
			0.6, -- PATROL
			1.0, -- STRIKE FORCE
			0.15, -- CONVOY RAIDING
			0.25, -- CONVOY ESCORT
			0.2, -- MINES PLANTING
			0.1, -- MINES SWEEPING
			0.0, -- TRAIN
			0.0, -- RESERVE_FLEET
			0.85, -- NAVAL_INVASION_SUPPORT
	}

	NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 40;
	NDefines.NAir.NAVAL_STRIKE_CARRIER_MULTIPLIER = 12;
	NDefines.NAir.CARRIER_HOURS_DELAY_AFTER_EACH_COMBAT = 3;
	NDefines.NAir.DISRUPTION_FACTOR_CARRIER = 25.0;
	NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_ORG = 0.25;
	NDefines.NAir.AIR_AGILITY_TO_NAVAL_STRIKE_AGILITY = 0.06;
	--NDefines.NAir.CAPACITY_PENALTY = 3;

	NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 2;
	NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 3;
	NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 1;
	NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 1;
	NDefines.NProduction.BASE_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.1
	NDefines.NProduction.MIN_NAVAL_EQUIPMENT_CONVERSION_RESOURCE_COST_FACTOR = 0.1

	NDefines.NIntel.NAVY_SHIP_COUNT_INTEL_MIN = 0;
	NDefines.NIntel.NAVY_SHIP_COUNT_INTEL_MAX = 0.4;
	NDefines.NIntel.NAVY_MIN_INTEL_TO_SHOW_EXISTING_CATEGORY_TYPES = 0.01;
	NDefines.NIntel.NAVY_SHIP_TYPE_COUNT_INTEL_MIN = 0.01;
	NDefines.NIntel.NAVY_SHIP_TYPE_COUNT_INTEL_MAX = 0.3;
	NDefines.NIntel.NAVY_MIN_INTEL_TO_SHOW_SHIP_CLASSES = 0.15;
	NDefines.NIntel.NAVY_MIN_INTEL_TO_SHOW_SHIP_DESIGN_DETAILS = 0.5;

-- Production Defines
	--------------------------------------------------------------------------------------------------------------
	-- INDUSTRIAL PRODUCTION
	--------------------------------------------------------------------------------------------------------------

	NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 7
	NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 4
	NDefines.NProduction.BASE_FACTORY_START_EFFICIENCY_FACTOR = 6
	NDefines.NProduction.BASE_FACTORY_EFFICIENCY_GAIN = 0.6
	NDefines.NProduction.PRODUCTION_RESOURCE_LACK_PENALTY = -0.25

	--------------------------------------------------------------------------------------------------------------
	-- REPLENISHMENT and UPKEEP MECHANICS
	--------------------------------------------------------------------------------------------------------------

	NDefines.NMilitary.UNIT_UPKEEP_ATTRITION = 0.02							--Constant attrition value applied to armies.

	--------------------------------------------------------------------------------------------------------------
	-- FUEL CONSUMPTION BALANCE
	--------------------------------------------------------------------------------------------------------------

	NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 1.0
	NDefines.NCountry.BASE_FUEL_GAIN = 1.0
	---NDefines.NAir.FUEL_COST_MULT = 0.2625
	---NDefines.NMilitary.ARMY_FUEL_COST_MULT = 0.375
	---NDefines.NNavy.FUEL_COST_MULT = 0.05

-- BMCombat Defines
	--------------------------------------------------------------------------------------------------------------
	-- COUNTRY CHANGES 
	--------------------------------------------------------------------------------------------------------------

	NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.05
	NDefines.NCountry.MAX_BOMBING_WAR_SUPPORT_IMPACT = -0.70
	NDefines.NCountry.MAX_HEROES_BEING_KILLED_WAR_SUPPORT_IMPACT = -0.60
	NDefines.NCountry.MAX_CONVOYS_BEING_RAIDED_WAR_SUPPORT_IMPACT = -0.50
	NDefines.NCountry.AIR_SUPPLY_CONVERSION_SCALE = 0.075  --- Air supply is reasonable/usable now

	--------------------------------------------------------------------------------------------------------------
	-- MILITARY EXPERIENCE 
	--------------------------------------------------------------------------------------------------------------

	NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 16 -- Vanilla 20
	NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 4 -- Vanilla 5
	NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 8 -- Vanilla 10

	NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.11 --- MOD was 2.0 should half the increase

	NDefines.NMilitary.TRAINING_MAX_DAILY_COUNTRY_EXP = 0.16			-- (Def: 0.08)*2 | Maximum army XP gained per day from training
	NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.00225       -- (Def: 0.0015 *1.5 | No official documentation)
	NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.0075 	-- (Def: 0.005)*1.5 | Factor on country Air XP gained from wing training
	NDefines.NNavy.TRAINING_DAILY_COUNTRY_EXP_FACTOR = 0.0015			-- (Def: 0.001)*1.5 |Factor used to scale the Daily Country Navy XP gain

	--------------------------------------------------------------------------------------------------------------
	-- LAND COMBAT REWORK
	--------------------------------------------------------------------------------------------------------------


	NDefines.NMilitary.RECON_SKILL_IMPACT = 10
	NDefines.NMilitary.DAMAGE_SPLIT_ON_FIRST_TARGET = 0.5  -- (was 0.35) -- % of damage dealt to the first target in a combat. The rest will be split amongst subsequent targets. Modifiers can affect this up to a maximum of 0.9. That value must not be exposed as a define.	#WICHTIG

	NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_IMPACT = -0.50
	NDefines.NMilitary.ANTI_AIR_TARGETTING_TO_CHANCE = 0.10
	NDefines.NMilitary.TRAINING_MIN_STRENGTH = 0.2
	NDefines.NMilitary.AIR_SUPPORT_BASE = 0.25
	NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.02
	NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 0.35						-- Balancing value to convert equipment stat anti_air_attack to the damage reduction modifier apply to incoming air attacks against units with AA.

	NDefines.NMilitary.COMBAT_STACKING_START = 10
	NDefines.NMilitary.COMBAT_STACKING_EXTRA = 6
	NDefines.NMilitary.COMBAT_STACKING_PENALTY = -0.08

	NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.05

	NDefines.NMilitary.HOURLY_ORG_MOVEMENT_IMPACT = -0.1 

	NDefines.NMilitary.MIN_SUPPLY_CONSUMPTION = 0.01

	NDefines.NMilitary.TRAINING_ATTRITION = 0.01

	--- Speed ---
	NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_SPEED_IMPACT = -0.2 -- #MOD -- was -0.3,     -- effect on speed due to enemy air superiority
	NDefines.NMilitary.COMBAT_MOVEMENT_SPEED = 0.4 -- #MOD -- was 0.33,	               -- speed reduction base modifier in combat

	NDefines.NMilitary.FUEL_CAPACITY_DEFAULT_HOURS = 144 -- #MOD -- was 96,				-- default capacity if not specified

	--- Tactics and Recon ---
	NDefines.NMilitary.INITIATIVE_PICK_COUNTER_ADVANTAGE_FACTOR  = 0.75 -- #MOD -- was 0.35, -- advantage per leader level for picking a counter

	--- War Score ---
	NDefines.NMilitary.WAR_SCORE_AIR_IC_LOSS_FACTOR = 0.008						-- war score gained for every IC of damage done to an enemy's air mission
	NDefines.NMilitary.WAR_SCORE_LAND_DAMAGE_FACTOR = 0.01          				-- war score gained for every strengh damage done to an enemy's army
	NDefines.NMilitary.WAR_SCORE_LAND_IC_LOSS_FACTOR = 0.008         				-- war score gained for every IC damage done to an enemy's army

	NDefines.NMilitary.LAND_COMBAT_COLLATERAL_INFRA_FACTOR = 0.007

	NDefines.NMilitary.FLANKED_PROVINCES_COUNT = 2

	NDefines.NMilitary.NEW_COMMANDER_RANDOM_PERSONALITY_TRAIT_CHANCES = { 0.95, 0.50, 0.35, 0.10 };
	--------------------------------------------------------------------------------------------------------------
	-- AIR COMBAT REWORK
	--------------------------------------------------------------------------------------------------------------

	NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.03  ---0.04
	-- aNCFO -- NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 200
	-- aNCFO -- NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 200
	-- aNCFO -- NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 200
	-- aNCFO -- NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 2000
	-- aNCFO -- NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 200
	NDefines.NAir.BIGGEST_AGILITY_FACTOR_DIFF = 5.0


	NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_DAMAGE_FACTOR = 0.35
	NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRAIN_DAMAGE_FACTOR = 0.065
	NDefines.NAI.LAND_COMBAT_ANTI_LOGISTICS_PER_ENEMY_ARMY = 2.65  --5     -- Amount of CAS planes requested per enemy army for anti-logistics
	NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.35	-- 0.5			-- Anti Air Gun Damage factor
	NDefines.NAir.CAS_NIGHT_ATTACK_FACTOR = 0.35	-- #MOD 0.5 -- was 0.1,			-- CAS damaged get multiplied by this in land combats at night
	--#large buff to CAS. should result in 36% more CAS damage on average (1.5/1.1) (100% at day + 50% at night is 1.5 for mod, and 1.1 for vanilla)
	--#also, CAS was apparently utter trash at night, which means that in timeszones with bad sortie timing, CAS was way weaker than elsewhere. Eastern France, Benelux, and Indian Ocean were such zones). This should now not matter anymore. Also, Land units get -50% at night, why would CAS get -90% instead?

	NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_STR = 0.5					-- Balancing value to convert damage ( naval_strike_attack * hits ) to Strength reduction.
	NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_ORG = 0.75					-- Balancing value to convert damage ( naval_strike_attack * hits ) to Organisation reduction.
	--NDefines.NAir.NAVAL_STRIKE_CARRIER_MULTIPLIER = 30.0              -- damage bonus when planes are in naval combat where their carrier is present (and can thus sortie faster and more effectively)
	NDefines.NAir.NAVAL_STRIKE_TARGETTING_TO_AMOUNT = 0.5			-- Balancing value to convert the naval_strike_targetting equipment stats to chances of how many airplanes managed to do successfull strike.

	---NDefines.NMilitary.LAND_AIR_COMBAT_STR_DAMAGE_MODIFIER = 0.06
	---NDefines.NMilitary.LAND_AIR_COMBAT_ORG_DAMAGE_MODIFIER = 0.08

	--------------------------------------------------------------------------------------------------------------
	-- NAVAL COMBAT REWORK
	--------------------------------------------------------------------------------------------------------------

	-- NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.5		-- Balancing value to convert averaged equipment stats (anti_air_targetting and naval_strike_agility) to probability chances of airplane being hit by navies AA.
	-- VNR -- NDefines.NNavy.NAVAL_COMBAT_RESULT_TIMEOUT_YEARS = 24							-- after that many years we clear the naval combat results so they don't get stuck forever in the memory.
	-- VNR -- NDefines.NNavy.CONVOY_LOSS_HISTORY_TIMEOUT_MONTHS = 24					-- after this many months remove the history of lost convoys to not bloat savegames and memory since there is no way to see them anyway
	-- VNR -- NDefines.NNavy.NAVAL_COMBAT_AIR_CAPITAL_TARGET_SCORE = 50
	-- VNR -- NDefines.NNavy.NAVAL_COMBAT_AIR_CARRIER_TARGET_SCORE = 100
	-- VNR -- NDefines.NNavy.HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR	= 0.75 -- if one side has more ships than the other that side will get this penalty for each +100% ship ratio it has
	-- VNR -- NDefines.NNavy.SUB_DETECTION_CHANCE_BASE_SPOTTING_EFFECT = 1.0			-- effect of base spotting for initial spotting of pure submarine forces. this along with next value is added together and rolled against a random to start spotting
	-- VNR -- NDefines.NNavy.SUB_DETECTION_CHANCE_SPOTTING_SPEED_EFFECT = 4.0				-- effect of spotting speed for initial spotting of pure submarine forces. this along with prev value is added together and rolled against a random to start spotting
	-- VNR -- NDefines.NNavy.SUB_DETECTION_CHANCE_BASE_SPOTTING_POW_EFFECT = 3.0	

	-- VNR -- NDefines.NNavy.ANTI_AIR_POW_ON_INCOMING_AIR_DAMAGE = 0.25	-- received air damage is calculated using following: 1 - ( (ship_anti_air + fleet_anti_air * SHIP_TO_FLEET_ANTI_AIR_RATIO )^ANTI_AIR_POW_ON_INCOMING_AIR_DAMAGE ) * ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE
	-- VNR -- NDefines.NNavy.ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE	= 0.15
	-- VNR -- NDefines.NNavy.MAX_ANTI_AIR_REDUCTION_EFFECT_ON_INCOMING_AIR_DAMAGE = 0.75	-- damage reduction for incoming air attacks is clamped to this value at maximum.

	-- VNR -- NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_MANPOWER_FACTOR = 0.002			-- war score gained for every manpower killed when sinking a ship
	-- VNR -- NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_PRODUCTION_COST_FACTOR = 0.01		-- war score gained for every IC of the sunk ship
	-- VNR -- NDefines.NNavy.EXPERIENCE_FACTOR_CARRIER_GAIN = 0.04							-- Xp gain by carrier ships in the combat

	---NDefines.NNavy.CARRIER_STACK_PENALTY = 8 -- The most efficient is 4 carriers in combat. 5+ brings the penalty to the amount of wings in battle.
	-- VNR -- NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.07 -- Balancing value to convert averaged equipment stats (anti_air_targetting and naval_strike_agility) to probability chances of airplane being hit by navies AA.
	-- VNR -- NDefines.NNavy.ANTI_AIR_ATTACK_TO_AMOUNT = 0.005 -- Balancing value to convert equipment stat anti_air_attack to the random % value of airplanes being hit.

	NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 3.3
	NDefines.NAir.NAVAL_STRIKE_CARRIER_MULTIPLIER = 3.3
	-- VNR -- NDefines.NNavy.CARRIER_STACK_PENALTY = 10
	-- VNR -- NDefines.NNavy.CARRIER_STACK_PENALTY_EFFECT = 0.08


	-- VNR -- NDefines.NNavy.SUPREMACY_PER_SHIP_PER_MANPOWER = 0.05
	-- VNR -- NDefines.NNavy.SUPREMACY_PER_SHIP_PER_IC = 0.005
	-- VNR -- NDefines.NNavy.SUPREMACY_PER_SHIP_BASE = 0.0

	--------------------------------------------------------------------------------------------------------------
	-- ARMOUR DAMAGE REWORK
	--------------------------------------------------------------------------------------------------------------

	NDefines.NMilitary.PIERCING_THRESHOLDS = {                                            -- Our piercing / their armor must be this value to deal damage fraction equal to the index in the array below [higher number = higher penetration]. If armor is 0, 1.00 will be returned.
	    1.30,
	    1.1,
	    1.0,
	    0.9,
	    0.75,
	    0.5,
	    0.25,
	    0.00, --there isn't much point setting this higher than 0
	}

	NDefines.NMilitary.PIERCING_THRESHOLD_DAMAGE_VALUES = {                                -- 0 armor will always receive maximum damage (so add overmatching at your own peril). the system expects at least 2 values, with no upper limit.
	    1.00,
	    0.90,
	    0.80,
	    0.70,
	    0.60,
	    0.55,
	    0.40,
	    0.20,
	}

	NDefines.NMilitary.ARMOR_VS_AVERAGE = 0.2  -- 护甲和平均值的比例
	NDefines.NMilitary.PEN_VS_AVERAGE = 0.3  -- 穿透和平均值的比例
	NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_ON_SOFT_DICE_SIZE = 2  -- 金盾状态下的hp伤害骰子数
	NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 5  -- 金盾状态下的组织度伤害骰子数

	NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_DEFLECTION_FACTOR = 0.7
	NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_DEFLECTION_FACTOR = 0.9

	--------------------------------------------------------------------------------------------------------------
	-- STRATEGIC BOMBING DAMAGE REWORK
	--------------------------------------------------------------------------------------------------------------

	---NDefines.NCountry.BOMBING_WAR_SUPPORT_PENALTY_SCALE = -100.00 			-- Scaling of bomber damage to war support impact, will be added weekly as a war support penalty
	---NDefines.NCountry.MAX_BOMBING_WEEKLY_WAR_SUPPORT_PENALTY = -0.50		-- Max penalty that will gained per week from bomber's damage
	---NDefines.NCountry.BOMBING_WEEKLY_WAR_SUPPORT_PENALTY_DECAY = 0.10		-- Weekly decay of bomber damage war support penalty

	NDefines.NAir.AIR_WING_BOMB_DAMAGE_FACTOR = 6					-- Used to balance the damage done while bombing.

	NDefines.NAir.BOMBING_TARGETING_RANDOM_FACTOR = 0.15							-- % of picking the wrong target

	NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_SHIP_CHANCE = 0.1		-- Chance to hit a ship in port when it is bombed.
	NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_SHIP_DAMAGE_FACTOR = 50
	NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_PLANE_CHANCE = 0.65		-- Chance to hit a plane in airbase when it is bombed.
	NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_PLANE_DAMAGE_FACTOR = 50
	NDefines.NAir.AA_INDUSTRY_AIR_DAMAGE_FACTOR = -0.036									-- 5x levels = 60% defense from bombing

	--------------------------------------------------------------------------------------------------------------
	-- STRATEGIC NAVAL BOMBARDEMENT REWORK
	--------------------------------------------------------------------------------------------------------------

	-- VNR -- NDefines.NNavy.SHORE_BOMBARDMENT_CAP = 0.35
	-- VNR -- NDefines.NNavy.HEAVY_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.1  -- heavy gun attack value is divided by this value * 100 and added to shore bombardment modifier
	-- VNR -- NDefines.NNavy.LIGHT_GUN_ATTACK_TO_SHORE_BOMBARDMENT = 0.05 -- light gun attack value is divided by this value * 100 and added to shore bombardment modifier

	--------------------------------------------------------------------------------------------------------------
	-- EXPERIMENTAL DEFINES
	--------------------------------------------------------------------------------------------------------------

	NDefines.NMilitary.COMBAT_MINIMUM_TIME = 6
	---NDefines.NMilitary.COMBAT_VALUE_ORG_IMPORTANCE = 1.3		-- Multiplier on TotalOrganisation when determining the combat value of a division
	NDefines.NMilitary.SPOTTING_QUALITY_DROP_HOURS = 5 	-- Each X hours the intel quality drops after unit was spotted.
	---NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.040       -- global damage modifier... but some equipment is returned at end of battles see : EQUIPMENT_COMBAT_LOSS_FACTOR
	---NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.035        -- global damage modifier
	NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE_STEEPNESS = 120 -- how quickly defense approaches the max impact diminishing returns curve
	---NDefines.NMilitary.ORG_LOSS_FACTOR_ON_CONQUER = 0.3              -- percentage of (max) org loss on takign enemy province

	NDefines.NAir.COMBAT_MULTIPLANE_CAP = 2.0		-- How much bonus gives the airplanes amount advantage (2vs1) to winning the situation.
	NDefines.NAir.HOURS_DELAY_AFTER_EACH_COMBAT = 7					-- How many hours needs the wing to be ready for the next combat. Use for tweaking if combats happens too often. (generally used as double because of roundtrip)
	NDefines.NAir.CARRIER_HOURS_DELAY_AFTER_EACH_COMBAT = 8          -- how often carrier planes do battle inside naval combat
	NDefines.NAir.AA_INDUSTRY_AIR_DAMAGE_FACTOR = -0.15				-- 5x levels = 60% defense from bombing
	---NDefines.NMilitary.LAND_AIR_COMBAT_MAX_PLANES_PER_ENEMY_WIDTH = 4 -- how many CAS/TAC can enter a combat depending on enemy width there

	-- VNR -- NDefines.NNavy.COMBAT_BASE_HIT_CHANCE = 0.05									-- base chance for hit
	-- VNR -- NDefines.NNavy.COMBAT_EVASION_TO_HIT_CHANCE = 0.025							-- we take ship evasion stats, and mult by this value, so it gives hit chance reduction. So if reduction is 0.025 and ship evasion = 10, then there will be 0.25 (25%) lower hit chance. (Fe. 50% base -25% from evasion +10% bcoz it's very close).
	-- VNR -- NDefines.NNavy.COMBAT_MIN_HIT_CHANCE = 0.03									-- never less hit chance then this?
	-- VNR -- NDefines.NNavy.COMBAT_EVASION_TO_HIT_CHANCE_TORPEDO_MULT = 50.0				-- the above evasion hit chance is multiplied by 400% if shooting with torpedos. Torpedoes are slow so evasion matters more.
	-- VNR -- NDefines.NNavy.COMBAT_TORPEDO_CRITICAL_DAMAGE_MULT = 3.0						-- multiplier to damage when got critical hit from torpedo. (Critical hits are devastating as usualy torpedo_attack are pretty high base values).
	-- VNR -- NDefines.NNavy.COMBAT_DAMAGE_TO_STR_FACTOR = 0.6								-- casting damage value to ship strength multiplier. Use it ot balance the game difficulty.
	-- VNR -- NDefines.NNavy.COMBAT_CHASE_RESIGNATION_HOURS = 10								-- Before we resign chasing enemy, give them some minimum time so the combat doesn't end instantly.
	-- VNR -- NDefines.NNavy.COMBAT_MAX_GROUPS = 2										-- Max amount of "Fire Exchange" groups (FEX).
	-- VNR -- NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = 0.6								-- required naval supremacy to perform invasions on an area
	-- VNR -- NDefines.NNavy.SUBMARINE_REVEAL_BASE_CHANCE = 0.04							-- Base chance for submarine detection. It's modified by the difference of a spootter's submarines detection vs submarine visibility. Use this variable for game balancing.

	---NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION = 0.15                 -- max attrition when out of supply
	---NDefines.NMilitary.OUT_OF_SUPPLY_SPEED = -0.9                    -- max speed reduction from supply
	NDefines.NMilitary.NON_CORE_SUPPLY_SPEED = -0.7				   -- we are not running on our own VP supply so need to steal stuff along the way
	---NDefines.NMilitary.OUT_OF_SUPPLY_MORALE = -0.3                   -- max org regain reduction from supply

	NDefines.NMilitary.PARACHUTE_COMPLETE_ORG = 0.5				   -- Organisation value (in %) after unit being dropped regardless if failed disrupted or successful.

	NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.7          -- large river crossing
	NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY = -0.30           -- small river crossing
	NDefines.NMilitary.RIVER_CROSSING_SPEED_PENALTY_LARGE = -0.65     -- large river crossing
	-- aNCFO -- NDefines.NMilitary.BASE_FORT_PENALTY = -0.20 					   -- fort penalty		#HOI4TGW ::: BASE_FORT_PENALTY = -0.15
	NDefines.NMilitary.MULTIPLE_COMBATS_PENALTY = -0.35               -- defender penalty if attacked from multiple directions
	NDefines.NMilitary.ENCIRCLED_PENALTY = -0.25

	--------------------------------------------------------------------------------------------------------------
	-- ABADON'S EXPERIMENTAL DEFINES + TWEAKS
	--------------------------------------------------------------------------------------------------------------

	---NDefines.NMilitary.DIG_IN_FACTOR = 0.02  ---0.01 	Vanilla 0.02					   -- bonus factor for each dug-in level
	---NDefines.NMilitary.UNIT_DIGIN_SPEED = 0.5		-- Vanilla 1				   -- how "deep" you can dig a day.
	---NDefines.NMilitary.UNIT_DIGIN_CAP = 7             --Vanilla 5              -- how "deep" you can dig you can dig in until hitting max bonus

	NDefines.NMilitary.WITHDRAWING_SPEED_FACTOR =  0.2 -- vanilla 0.15 

	NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY = -0.6	-- #MOD -- was -1.5,			-- over combat width penalty per %.
	--#this means that exactly matching the combat width matters even less now. (1% penalty per 1% over combat width)
	NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY_MAX = -0.50	-- over combat width max (when you cant join no more).


	NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.003;			--0.002 -(NSB)> 0.0015
	NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 4;
	NDefines.NMilitary.TRAINING_EXPERIENCE_SCALE = 124.0;			--62.0

	--------------------------------------------------------------------------------------------------------------
	-- RCS Defines
	--------------------------------------------------------------------------------------------------------------

	NDefines.NMilitary.SUPPLY_GRACE = 72							   -- troops always carry 3 days of food and supply
	NDefines.NMilitary.SUPPLY_ORG_MAX_CAP = 0.50                     -- Max organization is factored by this if completely out of supply
	NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION = 0.10                 -- max attrition when out of supply
	NDefines.NMilitary.OUT_OF_SUPPLY_SPEED = -0.65                    -- max speed reduction from supply
	NDefines.NMilitary.OUT_OF_SUPPLY_MORALE = -0.5                   -- max org regain reduction from supply

	NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.05       -- global damage modifier... but some equipment is returned at end of battles see : EQUIPMENT_COMBAT_LOSS_FACTOR
	NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.05       -- global damage modifier
	NDefines.NMilitary.LAND_AIR_COMBAT_STR_DAMAGE_MODIFIER = 0.02    -- air global damage modifier
	NDefines.NMilitary.LAND_AIR_COMBAT_MAX_PLANES_PER_ENEMY_WIDTH = 2 -- how many CAS/TAC can enter a combat depending on enemy width there
		
	NDefines.NMilitary.EXILE_ORG = 0.05							   -- Amount of org to keep
		
	NDefines.NMilitary.COMBAT_SUPPLY_LACK_ATTACKER_ATTACK = -0.85     -- attack combat penalty for attacker if out of supply
	NDefines.NMilitary.COMBAT_SUPPLY_LACK_ATTACKER_DEFEND = -0.35     -- defend combat penalty for attacker if out of supply
	NDefines.NMilitary.COMBAT_SUPPLY_LACK_DEFENDER_ATTACK = -0.75     -- attack combat penalty for defender if out of supply
	NDefines.NMilitary.COMBAT_SUPPLY_LACK_DEFENDER_DEFEND = -0.25     -- defend combat penalty for defender if out of supply

-- BMT Defines
	---- Military additions
	NDefines.NMilitary.DIVISION_SIZE_FOR_XP = 4                    	-- how many battalions should a division have to count as a full divisions when calculating XP stuff
	NDefines.NMilitary.SPOTTING_QUALITY_DROP_HOURS = 3  			-- Each X hours the intel quality drops after unit was spotted.
	NDefines.NMilitary.MIN_SUPPLY_CONSUMPTION = 0.03 				-- minimum value of supply consumption that a unit can get
	NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 0.00033 
	NDefines.NMilitary.UNIT_EXPERIENCE_SCALE = 0.30 
	NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.00270 
	NDefines.NMilitary.TRAINING_MAX_LEVEL = 4 
	NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2 
	NDefines.NMilitary.TRAINING_EXPERIENCE_SCALE = 62.0 
	NDefines.NMilitary.TRAINING_ORG = 0.33 
	NDefines.NMilitary.ARMY_EXP_BASE_LEVEL = 3 
	NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.15 
	NDefines.NMilitary.UNIT_EXP_LEVELS = { 0.137,  0.225,  0.374,  0.452,  0.573,  0.681,  0.765,  0.879,  0.999 } 		-- Experience needed to progress to the next level
	NDefines.NMilitary.EXPEDITIONARY_FIELD_EXPERIENCE_SCALE = 0.66 	-- reduction factor in Xp from expeditionary forces
	NDefines.NMilitary.LEADER_EXPERIENCE_SCALE = 0.87 	
	NDefines.NMilitary.EXPERIENCE_LOSS_FACTOR = 0.17                -- percentage of experienced solders who die when manpower is removed
	NDefines.NMilitary.EQUIPMENT_COMBAT_LOSS_FACTOR = 0.8 	 	    -- % of equipment lost to strength ratio in combat  so some % is returned if below 1
	NDefines.NMilitary.TRAINING_ATTRITION = 0.033 		  			-- amount of extra attrition from being in training
	NDefines.NMilitary.REINFORCE_CHANCE = 0.033                  	-- base chance to join combat from back line when empty
	NDefines.NMilitary.SPEED_REINFORCEMENT_BONUS = 0.011            -- chance to join combat bonus by each 100% larger than infantry base (up to 200%)
	NDefines.NMilitary.FLANKED_PROVINCES_COUNT = 5 					-- Attacker has to attack from that many provinces for the attack to be considered as flanking
	NDefines.NMilitary.MIN_DIVISION_DEPLOYMENT_TRAINING = 0.30 		-- Min level of division training	
	NDefines.NMilitary.FIELD_MARSHAL_ARMY_BONUS_RATIO = 0.7         -- ratio to apply regular bonuses FM bonuses to armies
	NDefines.NMilitary.FIELD_MARSHAL_XP_RATIO = 0.7					-- xp gain ratio for army group leaders
	NDefines.NMilitary.PARACHUTE_FAILED_EQUIPMENT_DIV = 30.0		-- When the transport plane was shot down, we drop unit with almost NONE equipment
	NDefines.NMilitary.PARACHUTE_FAILED_MANPOWER_DIV = 60.0		   	-- When the transport plane was shot down, we drop unit with almost NONE manpower
	NDefines.NMilitary.PARACHUTE_FAILED_STR_DIV = 7.0			   	-- When the transport plane was shot down, we drop unit with almost NONE strenght
	NDefines.NMilitary.PARACHUTE_DISRUPTED_EQUIPMENT_DIV = 1.1   	-- When the transport plane was hit, we drop unit with reduced equipment. Penalty is higher as more hits was received (and AA guns was in the state).
	NDefines.NMilitary.PARACHUTE_DISRUPTED_MANPOWER_DIV = 1.7	    -- When the transport plane was hit, we drop unit with reduced manpower. Penalty is higher as more hits was received (and AA guns was in the state).
	NDefines.NMilitary.PARACHUTE_DISRUPTED_STR_DIV = 2.1			-- When the transport plane was hit, we drop unit with reduced strength. Penalty is higher as more hits was received (and AA guns was in the state).
	NDefines.NMilitary.PARACHUTE_PENALTY_RANDOMNESS = 0.3			-- Random factor for str,manpower,eq penalties.
	NDefines.NMilitary.PARACHUTE_DISRUPTED_AA_PENALTY = 1           -- How much the Air defence in the state (from AA buildings level * air_defence) is scaled to affect overall disruption (equipment,manpower,str).
	NDefines.NMilitary.PARACHUTE_COMPLETE_ORG = 0.8				   	-- Organisation value (in %) after unit being dropped, regardless if failed, disrupted, or successful.
	NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_DURATION = 72	-- penalty in org regain after being parachuted. Value is in hours.
	NDefines.NMilitary.PARACHUTE_ORG_REGAIN_PENALTY_MULT = -0.8	
	NDefines.NMilitary.LOW_SUPPLY = 0.8

-- ARR Defines
	--------------------------------------------------------------------------------------------------------------
	-- SUPPLY FLOW REWORK
	--------------------------------------------------------------------------------------------------------------

	NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.45 -- Bonus to supply from a VP, no matter the level (Base is 0.2)
	NDefines.NSupply.AVAILABLE_MANPOWER_STATE_SUPPLY = 0.5 --Factor for state supply from max manpower (population) (Base is 0.18, this is PER MILLION.)
	NDefines.NSupply.VP_TO_SUPPLY_BONUS_CONVERSION = 0.05 -- Bonus to supply local supplies from Victory Points, multiplied by this aspect and rounded to closest integer (Base is 0.05)
	NDefines.NSupply.CAPITAL_INITIAL_SUPPLY_FLOW = 5.0 -- starting supply from
	NDefines.NSupply.CAPITAL_STARTING_PENALTY_PER_PROVINCE = 0.5 -- starting penalty that will be added as supply moves away from its origin (modified by stuff like terrain) (Default is 0.5)
	NDefines.NSupply.CAPITAL_ADDED_PENALTY_PER_PROVINCE = 1.2 -- added penalty as we move away from origin (Default is 1.2)

	-- defines that are used for supply reach for built nodes
	NDefines.NSupply.NODE_INITIAL_SUPPLY_FLOW = 2.8
	NDefines.NSupply.NODE_STARTING_PENALTY_PER_PROVINCE = 0.30 -- default is 0.5
	NDefines.NSupply.NODE_ADDED_PENALTY_PER_PROVINCE = 0.50 -- default is 0.7

	-- defines that are used for supply reach for dockyards
	NDefines.NSupply.NAVAL_BASE_INITIAL_SUPPLY_FLOW = 3.3
	NDefines.NSupply.NAVAL_BASE_STARTING_PENALTY_PER_PROVINCE = 0.84
	NDefines.NSupply.NAVAL_BASE_ADDED_PENALTY_PER_PROVINCE = 1.1


	NDefines.NCountry.REINFORCEMENT_DELIVERY_SPEED_MIN = 0.066	 
	NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 0.066
	NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 2.6	
	NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.07					
	NDefines.NMilitary.REINFORCEMENT_REQUEST_MAX_WAITING_DAYS = 35
	NDefines.NMilitary.REINFORCEMENT_REQUEST_DAYS_FREQUENCY = 20   
	NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 70
	NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.65
	NDefines.NSupply.TRUCK_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.01
	NDefines.NSupply.NAVAL_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.06

	NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN = 12
	NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN_CORE = 8
	NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN_CIVILWAR = 4

-- Ten Support Companies Defines
	NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2;
