------Construction------
NDefines.NAI.BUILDING_TARGETS_BUILDING_PRIORITIES = {
	'air_base',
	'infrastructure',
	'nuclear_reactor',
	'nuclear_reactor_heavy_water',
	'synthetic_refinery',
	'dockyard',
	'industrial_complex',
}
NDefines.NAI.CONSTRUCTION_PRIO_SUPPLY_BUILDING = 3.50
NDefines.NAI.CONSTRUCTION_PRIO_RAILWAY = 20.0
NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_OWNED_CORE = 5.0
NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_OWNED_NONCORE = 3.0

------Production------

NDefines.NAI.INDUSTRIAL_ORG_TRAIT_UNLOCK_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_RESEARCH_ASSIGN_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_PRODUCTION_ASSIGN_RANDOMNESS = 1.0

------Navy------
NDefines.NNavy.AGGRESION_MULTIPLIER_FOR_COMBAT = 4
NDefines.NNavy.AGGRESSION_SETTINGS_VALUES = {
	0,		
	1.0,	
	1.4,	
	2.2,	
	10000,	
}

NDefines.NAI.NAVAL_BASE_RATIO_ALLOCATED_FOR_REPAIRS = 0.1
NDefines.NAI.NAVAL_BASE_RATIO_ALLOCATED_FOR_REPAIRS_IN_WAR_TIME = 0.5
NDefines.NAI.SHIP_STR_RATIO_PUT_ON_REPAIRS = 0.6
NDefines.NAI.NAVAL_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS_AT_WAR = 1000
NDefines.NAI.NAVAL_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS = 500
NDefines.NAI.AIR_BASE_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS_AT_WAR = 1000
NDefines.NAI.AIR_BASE_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS = 800

------AI Fleet Composition------
NDefines.NAI.REPAIR_TASKFORCE_SIZE = 5
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_LAYING = 0.0
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO = 0.20
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO_MIN_MINES = 225

------AI Production / Designs------
NDefines.NAI.WANTED_CARRIER_PLANES_PER_CARRIER_CAPACITY_FACTOR = 2
NDefines.NAI.WANTED_CARRIER_PLANES_PER_CARRIER_CAPACITY_IN_PRODUCTION_FACTOR = 1.5
NDefines.NAI.AI_WANTED_CARRIER_BASED_PLANES_FACTOR = 1.5

------AI Mission------
NDefines.NAI.NAVAL_MISSION_DISTANCE_BASE = 4200
NDefines.NAI.NAVAL_MISSION_ESCORT_NEAR_OWNED = 0
NDefines.NAI.NAVAL_MISSION_ESCORT_NEAR_CONTROLLED = 0
NDefines.NAI.CONVOY_ESCORT_SCORE_FROM_CONVOYS = 25
NDefines.NAI.MAX_ALLOWED_NAVAL_DANGER = 200
NDefines.NAI.DANGEROUS_ENEMY_ARMY_SIZE = 10000

------Airforce------
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP_ESCORTING = 20
