------Construction------
NDefines.NAI.BUILDING_TARGETS_BUILDING_PRIORITIES = {
	'air_base',
	'infrastructure',
	'nuclear_reactor',
	'nuclear_reactor_heavy_water',
	'synthetic_refinery',
	'dockyard',
	'industrial_complex',
}
NDefines.NAI.CONSTRUCTION_PRIO_SUPPLY_BUILDING = 3.50
NDefines.NAI.CONSTRUCTION_PRIO_RAILWAY = 20.0
NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_OWNED_CORE = 5.0
NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_OWNED_NONCORE = 3.0

------Technology------
NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 1
NDefines.NAI.RESEARCH_AHEAD_BONUS_FACTOR = 10.0
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 1.5
NDefines.NAI.MAX_AHEAD_RESEARCH_PENALTY = 7
NDefines.NAI.RESEARCH_YEARS_BEHIND_FACTOR = 0.20

------Training------
NDefines.NAI.DEPLOY_MIN_TRAINING_SURRENDER_FACTOR = 0.5
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_SURRENDER_FACTOR = 0.90 
NDefines.NAI.DEPLOY_MIN_TRAINING_PEACE_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_PEACE_FACTOR = 0.70
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 0.85
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_CAP_DEPLOY_FACTOR = 0.85
NDefines.NAI.UPGRADE_DIVISION_RELUCTANCE = 3
NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.10
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_TEMPLATE = 7
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_EQUIPMENT = 7
NDefines.NAI.STOP_TRAINING_FULLY_TRAINED_FACTOR = 0.99
NDefines.NAI.UPGRADES_DEFICIT_LIMIT_DAYS = 60
NDefines.NAI.LOW_PRIO_TEMPLATE_BONUS_FOR_GARRISONS = 300000
NDefines.NAI.LOW_PRIO_TEMPLATE_PENALTY_FOR_FRONTS = -2000

------XP related------
NDefines.NAI.DESIRE_USE_XP_TO_UPDATE_LAND_TEMPLATE = 25.0
NDefines.NAI.VARIANT_CREATION_XP_RESERVE_LAND = 10
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_LAND_DOCTRINE = 10
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_NAVAL_DOCTRINE = 0.5
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_AIR_DOCTRINE = 0.5
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_ARMY_SPIRIT = 0.4
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_LAND_EQUIPMENT = 50.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_NAVAL_EQUIPMENT = 1.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_AIR_EQUIPMENT = 15.0
NDefines.NAI.DEFAULT_LEGACY_VARIANT_CREATION_XP_CUTOFF_LAND = 20
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_LAND = 10
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_NAVY = 50
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_AIR = 25
NDefines.NAI.DEFAULT_LEGACY_VARIANT_CREATION_XP_CUTOFF_AIR = 20
NDefines.NAI.VARIANT_CREATION_XP_RESERVE_NAVY = 30
NDefines.NAI.VARIANT_CREATION_XP_RESERVE_AIR  = 30

------Production------
NDefines.NAI.PRODUCTION_EQUIPMENT_SURPLUS_FACTOR = 0.6
NDefines.NAI.PRODUCTION_LINE_SWITCH_SURPLUS_NEEDED_MODIFIER = 0.4
NDefines.NAI.RAILWAY_GUN_PRODUCTION_BASE_DIVISIONS_RATIO_PERCENT = 5
NDefines.NAI.RAILWAY_GUN_PRODUCTION_MIN_DIVISONS = 50
NDefines.NAI.RAILWAY_GUN_PRODUCTION_MIN_FACTORIES = 50

NDefines.NAI.INDUSTRIAL_ORG_TRAIT_UNLOCK_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_RESEARCH_ASSIGN_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_PRODUCTION_ASSIGN_RANDOMNESS = 1.0

------Navy------
NDefines.NNavy.AGGRESION_MULTIPLIER_FOR_COMBAT = 4
NDefines.NNavy.AGGRESSION_SETTINGS_VALUES = {
	0,		
	1.0,	
	1.4,	
	2.2,	
	10000,	
}

NDefines.NAI.NAVAL_BASE_RATIO_ALLOCATED_FOR_REPAIRS = 0.1
NDefines.NAI.NAVAL_BASE_RATIO_ALLOCATED_FOR_REPAIRS_IN_WAR_TIME = 0.5
NDefines.NAI.SHIP_STR_RATIO_PUT_ON_REPAIRS = 0.6
NDefines.NAI.NAVAL_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS_AT_WAR = 1000
NDefines.NAI.NAVAL_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS = 500
NDefines.NAI.AIR_BASE_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS_AT_WAR = 1000
NDefines.NAI.AIR_BASE_ACCESS_SCORE_PENALTY_PER_EXISTING_ACCESS = 800

------AI Fleet Composition------
NDefines.NAI.NAVY_PREFERED_MAX_SIZE = 60
NDefines.NAI.CARRIER_TASKFORCE_MAX_CARRIER_COUNT = 4
NDefines.NAI.CAPITAL_TASKFORCE_MAX_CAPITAL_COUNT = 6
NDefines.NAI.SCREEN_TASKFORCE_MAX_SHIP_COUNT = 5
NDefines.NAI.SCREENS_TO_CAPITAL_RATIO = 4
NDefines.NAI.MIN_CAPITALS_FOR_CARRIER_TASKFORCE = 4
NDefines.NAI.REPAIR_TASKFORCE_SIZE = 5
NDefines.NAI.MAIN_SHIP_RATIO_TO_SPLIT = 2.0
NDefines.NAI.MIN_MAIN_SHIP_RATIO = 0.6
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_CONVOY_DEFENSE_MIN = 0.10
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_CONVOY_DEFENSE_MAX = 0.25
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_LAYING = 0.0
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO = 0.20
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO_MIN_MINES = 225
NDefines.NAI.SUGGESTED_NUM_MAX_CARRIERS = 4

------AI Production / Designs------
NDefines.NAI.SHIPS_PRODUCTION_BASE_COST = 25000
NDefines.NAI.NAVAL_DOCKYARDS_SHIP_FACTOR = 2.5
NDefines.NAI.PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0
NDefines.NAI.PRODUCTION_WAIT_TO_FINISH_IF_EXPENSIVE = 0.02
NDefines.NAI.WANTED_CARRIER_PLANES_PER_CARRIER_CAPACITY_FACTOR = 2
NDefines.NAI.WANTED_CARRIER_PLANES_PER_CARRIER_CAPACITY_IN_PRODUCTION_FACTOR = 1.5
NDefines.NAI.AI_WANTED_CARRIER_BASED_PLANES_FACTOR = 1.5

------AI Mission------
NDefines.NAI.NAVAL_MISSION_DISTANCE_BASE = 4200
NDefines.NAI.NAVAL_MISSION_ESCORT_NEAR_OWNED = 0
NDefines.NAI.NAVAL_MISSION_ESCORT_NEAR_CONTROLLED = 0
NDefines.NAI.AI_MIN_DOMINANCE_MARGIN = 100
NDefines.NAI.MIN_NAVAL_MISSION_PRIO_TO_ASSIGN = {
	0,   -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
	150, -- PATROL
	200, -- STRIKE FORCE
	200, -- CONVOY RAIDING
	150, -- CONVOY ESCORT
	150, -- MINES PLANTING
	100, -- MINES SWEEPING
	0,   -- TRAIN
	0,   -- RESERVE_FLEET
	100, -- NAVAL INVASION SUPPORT
}

NDefines.NAI.HIGH_PRIO_NAVAL_MISSION_SCORES = {
	0,    -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
	5000, -- PATROL
	1000, -- STRIKE FORCE
	1500, -- CONVOY RAIDING
	1500, -- CONVOY ESCORT
	-1,   -- MINES PLANTING
	300,  -- MINES SWEEPING
	0,    -- TRAIN
	0,    -- RESERVE_FLEET
	1000, -- NAVAL INVASION SUPPORT
}

NDefines.NAI.MAX_MISSION_PER_TASKFORCE = {
	0, 
	2, 
	4, 
	2, 
	4, 
	2, 
	2, 
	0, 
	0, 
	6, 
}
NDefines.NAI.CONVOY_ESCORT_SCORE_FROM_CONVOYS = 25
NDefines.NAI.MAX_ALLOWED_NAVAL_DANGER = 200
NDefines.NAI.REGION_THREAT_PER_SUNK_CONVOY = 15
NDefines.NAI.REGION_CONVOY_DANGER_DAILY_DECAY = 6
NDefines.NAI.DANGEROUS_ENEMY_ARMY_SIZE = 10000

------Army------
NDefines.NAI.AI_PREFERRED_TACTIC_WEEKLY_CHANGE_CHANCE = 0.00

----Battleplanning----
NDefines.NAI.LAND_DEFENSE_SUPPLY_HUB_IMPORTANCE = 9
NDefines.NAI.ASSIGN_TANKS_TO_MOUNTAINS = -15
NDefines.NAI.ASSIGN_TANKS_TO_JUNGLE = -20
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.15
NDefines.NSupply.AI_FRONT_DIVISIONS_PER_SUPPLY_POINT = 0.85
NDefines.NAITheatre.AI_THEATRE_SUPPLY_CRISIS_LIMIT = 0.25
NDefines.NAI.PLAN_VALUE_TO_EXECUTE = -0.61
NDefines.NAI.FRONT_EVAL_UNIT_AIR_SUP_IMPACT = 2.0
NDefines.NAI.AI_FRONT_MOVEMENT_FACTOR_FOR_READY = 0.25
NDefines.NSupply.AI_FRONT_MINIMUM_UNITS_PER_PROVINCE_FOR_SUPPLY_CALCULATIONS = 0	-- Vanilla is 1
NDefines.NAI.PLAN_ACTIVATION_PLAYER_WEIGHT_FACTOR = 2
NDefines.NAI.PLAN_ATTACK_DEPTH_FACTOR = 0.5
NDefines.NAI.STATE_CONTROL_FOR_AREA_DEFENSE = 0.60
NDefines.NAI.MAX_SUPPLY_DIVISOR = 1.50
NDefines.NAI.DIVISION_SUPPLY_RATIO_TO_MOTORIZE = 1
NDefines.NAI.ENTRENCHMENT_WEIGHT = 4.0
NDefines.NAI.MIN_FIELD_STRENGTH_TO_BUILD_UNITS = 0.70
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.5
NDefines.NAI.MAX_MICRO_ATTACKS_PER_ORDER = 5
NDefines.NAI.MICRO_POCKET_SIZE = 3
NDefines.NAI.POCKET_DISTANCE_MAX = 6000
NDefines.NAI.FRONT_BULGE_RATIO_LOWER_CUTOFF = 1.2
NDefines.NAI.FRONT_BULGE_RATIO_UPPER_CUTOFF = 1.8
NDefines.NAI.FRONT_EVAL_UNIT_ACCURACY = 1.5
NDefines.NAI.VP_LEVEL_IMPORTANCE_MEDIUM = 1
NDefines.NAI.VP_LEVEL_IMPORTANCE_LOW = 1 --keep high at 30
NDefines.NAI.PLAN_MIN_SIZE_FOR_FALLBACK = 2000
NDefines.NAI.MIN_PLAN_VALUE_TO_MICRO_INACTIVE = 0.15
NDefines.NAI.UNIT_ASSIGNMENT_TERRAIN_IMPORTANCE = 10.0
NDefines.NAI.FRONT_UNITS_CAP_FACTOR = 20.0
NDefines.NAI.RAIDS_CREATE_FREQUENCY_DAYS = 20
NDefines.NAI.RAIDS_COMMAND_POWER_CAP_TO_CREATE = 150.0 
NDefines.NAI.COMMAND_POWER_BEFORE_SPEND_ON_TRAITS = 10.0
NDefines.NAI.ARMY_LEADER_ASSIGN_NR_TRAITS = 0
NDefines.NAI.LOCATION_BALANCE_TO_ADVANCE = 0.00
NDefines.NAI.MAIN_ENEMY_FRONT_IMPORTANCE = 3.0
NDefines.NAI.MIN_NUM_CONQUERED_PROVINCES_TO_DEPRIO_NAVAL_INVADED_FRONTS = 100
NDefines.NAI.MAX_INVASION_SIZE = 24

----AIFC----
NDefines.NAI.AIFC_CA_DIVISIONS_PER_PROVINCE = 2.5
NDefines.NAI.AIFC_ACTIVATE_AVG_ORG_RATIO_THRESHOLD = 0.4
NDefines.NAI.AIFC_ACTIVATE_IN_POSITION_RATIO_THRESHOLD = 0.3
NDefines.NAI.AIFC_TARGET_SUPPLY_HUB_BASE_SCORE = 30.0
NDefines.NAI.AIFC_TARGET_NAVAL_BASE_BASE_SCORE = 15.0
NDefines.NAI.AIFC_TARGET_NAVAL_BASE_SCORE_PER_LEVEL = 2.0
NDefines.NAI.AIFC_REFRESH_NEED_PER_DAY = 2.0
NDefines.NAI.AIFC_REFRESH_NEED_SUPPLY_FACTOR_PER_DAY = 1.10
NDefines.NAI.AIFC_PATH_COST_TRN_MOUNTAINS = 4.0
NDefines.NAI.AIFC_PATH_COST_TRN_MARSH = 3.0
NDefines.NAI.AIFC_PATH_COST_TRN_FOREST = 1.5
NDefines.NAI.AIFC_PATH_COST_TRN_URBAN = 0.50
NDefines.NAI.AIFC_PATH_COST_ADJ_RIVER = 1.5
NDefines.NAI.AIFC_PATH_COST_ADJ_RIVER_LARGE = 3.25
NDefines.NAI.AIFC_FRESHNESS_ADD_ON_PROGRESS = 22.0
NDefines.NAI.AIFC_PATH_COST_RAILWAY_CONNECTION = 0.80
NDefines.NAI.AIFC_PATH_COST_HAS_SUPPLY_HUB = 0.50
NDefines.NAI.AIFC_TARGET_SHORT_PATH_PENALTY_FACTOR = 0 --short path more ideal now?
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_HARDNESS = 800.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_EXPERIENCE = 500.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_ARMOR = 80.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_SOFT_ATTACK = 12.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_HARD_ATTACK = 16.0
NDefines.NAI.AIFC_UNIT_NUDGE_FREQUENCY_DAYS = 10.0
NDefines.NAI.AIFC_UPDATE_FREQUENCY_DAYS = 4

------Airforce------
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP = 50
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP_ESCORTING = 20
NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_ESCORTING = 15
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_AIR_TRAINING = 3.00
NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_AIR_MAX_CONSUMPTION  = 2
NDefines.NAI.LAND_COMBAT_FIGHTERS_PER_PLANE = 3.0
NDefines.NAI.LAND_COMBAT_FRIEND_ARMIES_AIR_IMPORTANCE = 2.0
NDefines.NAI.LAND_COMBAT_OUR_ARMIES_AIR_IMPORTANCE = 8.0
NDefines.NAI.LAND_COMBAT_FRIEND_COMBATS_AIR_IMPORTANCE = 5.0
NDefines.NAI.LAND_COMBAT_OUR_COMBATS_AIR_IMPORTANCE = 500
NDefines.NAI.LAND_COMBAT_ENEMY_COASTAL_FORTS_AIR_IMPORTANCE = 20.0
NDefines.NAI.AI_AIR_MISSION_COVERAGE_TO_STAY_PUT = 0.75
NDefines.NAI.AIR_SCORE_DISTANCE_IMPACT = 0.0
NDefines.NAI.DAYS_BETWEEN_AIR_PRIORITIES_UPDATE = 7
NDefines.NAI.LAND_DEFENSE_FIGHERS_PER_PLANE = 2.5
