"""
Compute the country-to-country land-border graph from state ownership.

Answers one question only: which countries physically border which other
countries, where "border" means two states with DIFFERENT `owner` tags (read
from history/states) touch by land. Ownership is the only thing that turns a
state border into a country border -- unowned states never contribute an edge.

Land adjacency is built the same way as the other map tools here: from
map/provinces.bmp pixel borders, edited by map/adjacencies.csv (adjacencies.csv
holds ONLY straits / canal / tunnel crossings and impassable borders, never
standard land borders). Every strait crossing bridges, so two countries that
touch only across a sea strait count as bordering -- matching how the other
tools in this folder treat crossings, and how HOI4 land adjacency itself works.

Output country_borders.json is written into the tools/ folder alongside this
script (not the current working directory): an envelope with provenance plus a
`countries` array, one record per country tag
that owns at least one state:
  { tag, neighbor_count, neighbors[], isolated }
`neighbors` is the sorted list of tags this country shares a land border with;
`isolated` is true when it borders no other country (island nation or fully
surrounded by unowned territory). An `edges` array lists every undirected
country border once, with the touching state pair(s) that create it, so a
surprising adjacency can be traced back to specific states without the game.

This script lives in the mod's root-level tools/ folder and resolves both its
input files and its output file from its own location (mod root = the parent of
tools/), so it runs from any working directory and always writes to the same
place. It assumes only standard HOI4 map / history structure and is portable to
any mod as-is.

Usage (from anywhere):

    python /path/to/mod/tools/_check_country_borders.py [--tag TAG] [--conn 4|8]

or from the tools/ folder:

    python _check_country_borders.py [--tag TAG] [--conn 4|8]

--tag limits the console report (not the JSON) to one country's neighbours.

Requires: Pillow, numpy.

Generated by claude.
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

from _map_common import (
    ADJACENCIES_FILE,
    DEFINITION_FILE,
    MOD_ROOT,
    PROVINCES_BMP,
    STATES_DIR,
    apply_adjacency_exceptions,
    extract_pixel_adjacency,
    parse_definition,
    parse_states,
    verify_mod_root,
)

# Written next to this script inside tools/, not the current working directory,
# so the output lands in a predictable place no matter where it is invoked from.
OUTPUT_FILE = Path(__file__).resolve().parent / "country_borders.json"


def main():
    ap = argparse.ArgumentParser(
        description="Compute the country-to-country land-border graph from "
        "state ownership and write country_borders.json."
    )
    ap.add_argument(
        "--tag",
        help="Limit the console report to one country's neighbours "
        "(the JSON always contains every country).",
    )
    ap.add_argument(
        "--conn",
        type=int,
        choices=(4, 8),
        default=4,
        help="Pixel connectivity: 4 = orthogonal (default), 8 = include diagonals",
    )
    args = ap.parse_args()
    focus_tag = args.tag.strip().upper() if args.tag else None

    # Confirm the script can reliably locate the mod root before doing any work.
    root_problems = verify_mod_root(MOD_ROOT)
    if root_problems:
        print("ERROR: could not confirm the mod root from the script location.")
        print(f"  Script:   {Path(__file__).resolve()}")
        print(f"  Expected mod root: {MOD_ROOT}")
        for prob in root_problems:
            print(f"  - {prob}")
        print(
            "  This script must stay inside <mod_root>/tools/. Move it back or "
            "adjust MOD_ROOT."
        )
        sys.exit(1)

    for p in (DEFINITION_FILE, PROVINCES_BMP, ADJACENCIES_FILE):
        if not p.exists():
            print(f"ERROR: cannot find {p}")
            sys.exit(1)

    # --- Land adjacency (province level) ---
    print(f"Parsing {DEFINITION_FILE.name} ...")
    code2id, land_ids = parse_definition(DEFINITION_FILE)
    print(f"  {len(code2id)} provinces defined, {len(land_ids)} land provinces.")

    print(f"Extracting pixel adjacency from {PROVINCES_BMP.name} (conn={args.conn}) ...")
    land_adj = extract_pixel_adjacency(PROVINCES_BMP, code2id, land_ids, args.conn)
    print(f"  {len(land_adj)} land-land pixel borders.")

    added, removed = apply_adjacency_exceptions(land_adj, ADJACENCIES_FILE, land_ids)
    print(
        f"Applied {ADJACENCIES_FILE.name}: +{added} crossing(s), -{removed} impassable; "
        f"{len(land_adj)} edges total."
    )

    # --- States: province -> state, and state -> owner ---
    print(f"Parsing states in {STATES_DIR} ...")
    states = parse_states(STATES_DIR)
    prov2state = {}
    owner_of = {}
    for st in states:
        owner_of[st["id"]] = st["owner"]
        for pid in st["provinces"]:
            prov2state[pid] = st["id"]
    print(f"  {len(states)} states, {len(prov2state)} provinces assigned.")

    # --- Country border graph ---
    # Walk every land province border. Resolve both endpoints to states, then to
    # owner tags. A DIFFERING pair of owned tags is a country border. Unowned
    # states (owner is None) never form an edge -- they cannot "border" anyone.
    # Keep, per country pair, the set of touching state pairs for traceability.
    neighbors = defaultdict(set)  # tag -> set of neighbour tags
    edge_states = defaultdict(set)  # frozenset(tagA, tagB) -> {(stateLo, stateHi)}
    owners_seen = set()

    for pair in land_adj:
        a, b = tuple(pair)
        sa = prov2state.get(a)
        sb = prov2state.get(b)
        if sa is None or sb is None or sa == sb:
            continue
        oa = owner_of.get(sa)
        ob = owner_of.get(sb)
        if oa is None or ob is None or oa == ob:
            continue
        neighbors[oa].add(ob)
        neighbors[ob].add(oa)
        key = frozenset((oa, ob))
        edge_states[key].add((min(sa, sb), max(sa, sb)))

    # Every country that owns at least one state is a node, so a landlocked-by-
    # -unowned-land or island country still appears (with no neighbours).
    for tag in owner_of.values():
        if tag is not None:
            owners_seen.add(tag)

    # --- Assemble per-country records ---
    country_records = []
    for tag in sorted(owners_seen):
        nbrs = sorted(neighbors.get(tag, ()))
        country_records.append(
            {
                "tag": tag,
                "neighbor_count": len(nbrs),
                "neighbors": nbrs,
                "isolated": len(nbrs) == 0,
            }
        )

    # --- Assemble undirected edge list with the states that create each border ---
    edge_records = []
    for key, pairs in edge_states.items():
        ta, tb = sorted(key)
        edge_records.append(
            {
                "a": ta,
                "b": tb,
                "via_state_pairs": sorted(list(p) for p in pairs),
            }
        )
    edge_records.sort(key=lambda e: (e["a"], e["b"]))

    payload = {
        "map": MOD_ROOT.name,
        "generated_by": Path(__file__).name,
        "pixel_connectivity": args.conn,
        "sea_crossings": "all_strait_crossings_bridge",
        "border_definition": "states with different owner tags touching by land",
        "country_count": len(country_records),
        "border_count": len(edge_records),
        "countries": country_records,
        "edges": edge_records,
    }
    out_path = OUTPUT_FILE
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    # --- Console summary ---
    print("\n" + "=" * 60)
    print("Country border graph (by state owner)")
    print("=" * 60)
    print(f"Countries owning >=1 state : {len(country_records)}")
    print(f"Country borders (undirected): {len(edge_records)}")

    isolated = [r["tag"] for r in country_records if r["isolated"]]
    if isolated:
        print(
            f"\n{len(isolated)} country(ies) border no other country "
            "(island / surrounded by unowned land):"
        )
        print("  " + ", ".join(isolated))

    if focus_tag:
        rec = next((r for r in country_records if r["tag"] == focus_tag), None)
        print("\n" + "-" * 60)
        if rec is None:
            print(f"{focus_tag} owns no states (not in the graph).")
        elif rec["isolated"]:
            print(f"{focus_tag} borders no other country.")
        else:
            print(f"{focus_tag} borders {rec['neighbor_count']} country(ies):")
            print("  " + ", ".join(rec["neighbors"]))
    else:
        print("\nNeighbour count per country:")
        for r in sorted(
            country_records, key=lambda r: (-r["neighbor_count"], r["tag"])
        ):
            print(f"  {r['tag']}  {r['neighbor_count']:>3} neighbour(s)")

    print(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
