#!/usr/bin/env python3
"""Resolved equipment/module/tech database for a HOI4 mod (via ModFS).

Nothing here hardcodes slot names, module categories, or type lists -- all
of it is derived from whatever `common/units/equipment/*.txt`,
`.../modules/*.txt`, and `common/technologies/*.txt` are actually visible
for the given mod (through ModFS's replace_path-aware layering). That is
what lets this run correctly, unmodified, against any mod on this root.

Generated by claude. Part of the equipment-variant-audit tooling
(.global_tools/equipment_variant_audit.py). No CLI of its own.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from _hoi4_modfs import Block, ModFS, parse_blocks

MAX_INHERIT_DEPTH = 20


@dataclass
class Slot:
    name: str
    required: bool
    allowed_categories: tuple[str, ...]
    origin_type: str  # which type in the chain first declared this slot


@dataclass
class CountLimit:
    conditions: frozenset  # frozenset of ("module", x) / ("category", x)
    op: str  # "<" | ">" | "=" | "any"
    count: int | None
    title: str | None
    origin_type: str


@dataclass
class EquipDef:
    name: str
    block: Block
    is_archetype: bool
    archetype: str | None
    parent: str | None
    equip_type: tuple[str, ...]  # the `type = ...` set, e.g. (screen_ship,) or (armor, anti_air)


@dataclass
class ModuleDef:
    name: str
    block: Block
    category: str | None
    parent: str | None
    forbid_module_categories: tuple[str, ...]


class EquipmentDB:
    def __init__(self, modfs: ModFS):
        self.modfs = modfs
        self.types: dict[str, EquipDef] = {}
        self.modules: dict[str, ModuleDef] = {}
        self.duplicates: list[tuple[str, list[str]]] = []  # (id, [files]) seen in >1 loaded file
        self._load_equipment()
        self._load_modules()

    # ---- loading ----------------------------------------------------

    def _load_equipment(self) -> None:
        seen_in: dict[str, list[str]] = {}
        for path, origin in self.modfs.list_dir("common/units/equipment"):
            text = self.modfs.read(path)
            for name, block in parse_blocks(text, unwrap="equipments", origin_file=path, origin=origin).items():
                seen_in.setdefault(name, []).append(path.name)
                is_arch = block.get("is_archetype") == "yes"
                archetype = block.get("archetype")
                parent = block.get("parent")
                type_set = tuple(block.set_list("type")) or ((block.get("type"),) if block.get("type") else ())
                self.types[name] = EquipDef(name, block, is_arch, archetype, parent, type_set)
        self.duplicates.extend((n, fs) for n, fs in seen_in.items() if len(fs) > 1)

    def _load_modules(self) -> None:
        for path, origin in self.modfs.list_dir("common/units/equipment/modules"):
            text = self.modfs.read(path)
            for name, block in parse_blocks(text, unwrap="equipment_modules", origin_file=path, origin=origin).items():
                category = block.get("category")
                parent = block.get("parent")
                forbid = tuple(block.set_list("forbid_module_categories"))
                self.modules[name] = ModuleDef(name, block, category, parent, forbid)

    # ---- inheritance chain --------------------------------------------

    def chain(self, type_name: str) -> list[str]:
        """[type_name, ..., root_archetype], following archetype then parent."""
        out = []
        cur = type_name
        seen = set()
        for _ in range(MAX_INHERIT_DEPTH):
            if cur is None or cur in seen or cur not in self.types:
                break
            out.append(cur)
            seen.add(cur)
            d = self.types[cur]
            nxt = d.archetype or d.parent
            if d.is_archetype:
                break
            cur = nxt
        return out

    def is_archetype(self, type_name: str) -> bool:
        d = self.types.get(type_name)
        return bool(d and d.is_archetype)

    # ---- slot resolution -----------------------------------------------

    def resolve_slots(self, type_name: str) -> dict[str, Slot]:
        """Resolve the full slot dict for `type_name`, root-to-leaf.

        Assumption (flagged for verification against real data): a type's
        own explicit `module_slots = { ... }` block REPLACES the parent's
        slot set rather than merging with it -- this matches vanilla's habit
        of re-listing every slot with `<slot> = inherit` even when only one
        slot actually changed. `module_slots = inherit` (the bare keyword,
        no block) is the wholesale-copy case.
        """
        chain = list(reversed(self.chain(type_name)))  # root archetype first
        resolved: dict[str, Slot] = {}
        for tname in chain:
            d = self.types[tname]
            raw = _extract_module_slots_raw(d.block)
            if raw is None:
                continue  # this type doesn't touch module_slots; keep inherited as-is
            if raw == "inherit":
                continue  # wholesale inherit: resolved already holds the parent's slots
            # raw is a dict of slot_name -> ("block", Block) | ("ref", str)
            new_resolved: dict[str, Slot] = {}
            for slot_name, (kind, val) in raw.items():
                if kind == "inherit":
                    if slot_name in resolved:
                        new_resolved[slot_name] = resolved[slot_name]
                    # else: inherit of a slot the parent never had -- leave unresolved,
                    # the validator will report this as a real problem upstream.
                elif kind == "ref":
                    target = val
                    if target in new_resolved:
                        new_resolved[slot_name] = new_resolved[target]
                    elif target in resolved:
                        new_resolved[slot_name] = resolved[target]
                elif kind == "block":
                    b: Block = val
                    required = b.get("required") == "yes"
                    cats = tuple(b.set_list("allowed_module_categories"))
                    new_resolved[slot_name] = Slot(slot_name, required, cats, tname)
            resolved = new_resolved
        return resolved

    def resolve_count_limits(self, type_name: str) -> list[CountLimit]:
        chain = list(reversed(self.chain(type_name)))
        limits: list[CountLimit] = []
        for tname in chain:
            d = self.types[tname]
            for lim_block in d.block.get_all_blocks("module_count_limit"):
                conditions = set()
                for m in lim_block.get_all_scalars("module"):
                    conditions.add(("module", m))
                for c in lim_block.get_all_scalars("category"):
                    conditions.add(("category", c))
                cond_fs = frozenset(conditions)
                # `count < 2` is a bare comparison, not a `key = value` assignment
                # -- Block.get()/get_all_scalars() require an '=' and won't match it.
                op, count = "<", None
                cm = re.search(r"\bcount\s*(<|>|=)\s*(any|\d+)", lim_block.body)
                if cm:
                    op = cm.group(1)
                    count = None if cm.group(2) == "any" else int(cm.group(2))
                # remove any limit inherited from an ancestor with the exact same conditions
                limits = [l for l in limits if l.conditions != cond_fs]
                limits.append(CountLimit(cond_fs, op, count, lim_block.get("title"), tname))
        return limits

    def resolve_defaults(self, type_name: str) -> dict[str, str]:
        chain = list(reversed(self.chain(type_name)))
        defaults: dict[str, str] = {}
        for tname in chain:
            d = self.types[tname]
            dm = _find_block(d.block, "default_modules")
            if dm is None:
                continue
            for line in dm.body.splitlines():
                m = re.match(r"\s*([A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_]+)\s*$", line)
                if m:
                    defaults[m.group(1)] = m.group(2)
        # A child's own (possibly narrower) module_slots block can drop a slot
        # the root archetype has -- e.g. vnr_ship_hull_pre_dreadnought's
        # module_slots omits mid_2_custom_slot/front_2_custom_slot/etc. that
        # ship_hull_heavy declares. A stale default_modules entry inherited
        # for a slot that no longer exists on this type must not survive, or
        # `installed` in the create_equipment_variant validator ends up
        # believing a slot exists when it doesn't (false V004).
        valid_slots = self.resolve_slots(type_name)
        return {k: v for k, v in defaults.items() if k in valid_slots}


# ---- helpers ------------------------------------------------------------

def _find_block(parent: Block, key: str) -> Block | None:
    children = parent.children()
    return children.get(key)


def _extract_module_slots_raw(block: Block):
    """Return None (no module_slots key at all), "inherit" (bare keyword),
    or a dict {slot_name: ("block", Block) | ("ref", target) | ("inherit", None)}.
    """
    body = block.body
    m = re.search(r"(?m)^\s*module_slots\s*=\s*(\S.*)$", body)
    if not m:
        return None
    rest = m.group(1).strip()
    if rest.startswith("inherit"):
        return "inherit"
    if not rest.startswith("{"):
        return None
    ms_block = block.children().get("module_slots")
    if ms_block is None:
        return None
    out = {}
    # slot -> block children first
    for slot_name, sub in ms_block.children().items():
        out[slot_name] = ("block", sub)
    # then catch bare `slot = inherit` / `slot = other_slot` scalar forms,
    # which parse_blocks' children() won't find (they aren't `{ }` blocks).
    for line in _iter_top_level_scalars(ms_block.body):
        key, val = line
        if key in out:
            continue
        if val == "inherit":
            out[key] = ("inherit", None)
        else:
            out[key] = ("ref", val)
    return out


def _iter_top_level_scalars(body: str):
    for m in re.finditer(r"(?m)^\s*([A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_]+)\s*(#.*)?$", body):
        yield m.group(1), m.group(2)


def _to_int(s: str) -> int | None:
    m = re.search(r"-?\d+", s)
    return int(m.group()) if m else None


# ---- technology gating ---------------------------------------------------

@dataclass
class TechGate:
    equip_enabled_by: dict[str, set[str]] = field(default_factory=dict)
    module_enabled_by: dict[str, set[str]] = field(default_factory=dict)

    def status(self, name: str, kind: str, researched: set[str], uncertain: set[str] = frozenset()) -> tuple[str, set[str]]:
        """kind: 'equip' | 'module'. Returns (status, gating_techs).

        Four states, not three. `uncertain` is the resolver's CONDITIONAL set
        (a tech behind a condition this tool can't evaluate statically, e.g.
        `any_owned_state = { is_coastal = yes }` -- common in this mod's
        starting-tech chain). A gate satisfied only by an uncertain tech is
        genuinely unknown, not locked: the tool cannot prove the nation lacks
        it, so reporting a hard ERROR would be a guess dressed as a fact.
        """
        gates = (self.equip_enabled_by if kind == "equip" else self.module_enabled_by).get(name)
        if not gates:
            return "UNGATED", set()
        if gates & researched:
            return "ENABLED", gates
        if gates & uncertain:
            return "UNCERTAIN", gates
        return "LOCKED", gates


def load_tech_gate(modfs: ModFS) -> TechGate:
    gate = TechGate()
    for path, origin in modfs.list_dir("common/technologies"):
        text = modfs.read(path)
        techs = parse_blocks(text, unwrap="technologies", origin_file=path, origin=origin)
        if not techs:
            # some tech files aren't wrapped in `technologies = {}` -- try raw top level
            techs = parse_blocks(text, origin_file=path, origin=origin)
        for tech_name, block in techs.items():
            for e in block.set_list("enable_equipments"):
                gate.equip_enabled_by.setdefault(e, set()).add(tech_name)
            for e in block.set_list("enable_equipment_modules"):
                gate.module_enabled_by.setdefault(e, set()).add(tech_name)
    return gate


DEFAULT_ASSUME_DLC = {
    "Man the Guns", "No Step Back", "By Blood Alone", "Arms Against Tyranny",
    "Battle for the Bosporus", "Battle for the Bosphorus", "La Resistance",
    "Together for Victory", "Waking the Tiger", "Death or Dishonor",
    "Fuhrer's Fury",
}


@dataclass
class TechResolution:
    certain: set[str] = field(default_factory=set)
    conditional: dict[str, str] = field(default_factory=dict)
    bonus_only: set[str] = field(default_factory=set)
    trace: list[str] = field(default_factory=list)


def resolve_country_techs(modfs: ModFS, tag: str, *, assume_dlc: set[str] | None = None,
                           extra_effects: list[str] | None = None) -> TechResolution:
    """Walk history/countries/<TAG> -> scripted effects -> set_technology,
    branch-aware over IF/ELSE (case-insensitive) and has_dlc conditions.
    """
    assume_dlc = assume_dlc if assume_dlc is not None else DEFAULT_ASSUME_DLC
    res = TechResolution()

    hist_path = modfs.find_country_history(tag)
    if hist_path is None:
        res.trace.append(f"no history/countries file found for tag {tag!r}")
        return res
    res.trace.append(f"history file: {hist_path}")

    effects: dict[str, str] = {}
    for path, origin in modfs.list_dir("common/scripted_effects"):
        effects[path.name] = modfs.read(path)
    combined_effects_text = "\n".join(effects.values())
    effect_blocks = parse_blocks(combined_effects_text, origin_file=Path("<scripted_effects>"), origin="mod")

    visited: set[str] = set()

    def _walk_body(body: str, depth: int) -> None:
        """Process `body` top-level-only: set_technology / add_tech_bonus grants,
        an if/else_if.../else chain taking EXACTLY ONE branch (mutually
        exclusive -- this is the whole point), and bare `effect = yes` calls.
        Never regexes the raw text for set_technology/add_tech_bonus, because
        that would blindly pick up grants sitting inside an untaken branch
        (e.g. the legacy-naval ELSE branch of a `has_dlc = "Man the Guns"`
        check) nested anywhere in this same body.
        """
        if depth > 12:
            res.trace.append("max recursion depth reached, stopping")
            return

        items = list(_iter_top_level(body))
        i, n = 0, len(items)
        while i < n:
            name, kind, content = items[i]
            klow = name.lower()

            if kind == "scalar":
                if content == "yes" and name in effect_blocks and name not in visited:
                    visited.add(name)
                    res.trace.append(f"{'  ' * depth}-> {name}")
                    _walk_body(effect_blocks[name].body, depth + 1)
                i += 1
                continue

            if klow == "set_technology":
                for line in content.splitlines():
                    mm = re.match(r"\s*([A-Za-z0-9_]+)\s*=\s*(\d+)", line)
                    if mm and mm.group(2) != "0":
                        res.certain.add(mm.group(1))
                i += 1
            elif klow == "add_tech_bonus":
                tm = re.search(r"technology\s*=\s*([A-Za-z0-9_]+)", content)
                if tm:
                    res.bonus_only.add(tm.group(1))
                i += 1
            elif klow in ("if", "else_if", "elseif"):
                chain = [(name, content)]
                j = i + 1
                while j < n and items[j][1] == "block" and items[j][0].lower() in ("else_if", "elseif"):
                    chain.append((items[j][0], items[j][2]))
                    j += 1
                else_content = None
                if j < n and items[j][1] == "block" and items[j][0].lower() == "else":
                    else_content = items[j][2]
                    j += 1
                taken = False
                for cname, cbody in chain:
                    limit_text = _extract_limit(cbody)
                    take = _evaluate_limit(limit_text, assume_dlc) if limit_text is not None else None
                    if take is True:
                        _walk_body(cbody, depth + 1)
                        taken = True
                        break
                    if take is None:
                        # can't evaluate the condition -- descend anyway so we
                        # don't silently miss techs, but anything found here
                        # is CONDITIONAL, not certain (unlike a definite branch).
                        before = set(res.certain)
                        res.trace.append(f"{'  ' * depth}(conditional branch, condition undetermined: {cname})")
                        _walk_body(cbody, depth + 1)
                        for t in res.certain - before:
                            res.certain.discard(t)
                            res.conditional[t] = f"inside {cname} with an unevaluated limit"
                        taken = True
                        break
                    # take is False: fall through to the next chain member
                if not taken and else_content is not None:
                    _walk_body(else_content, depth + 1)
                i = j
            elif klow == "limit":
                i += 1
            elif klow in ("else", "else_if", "elseif"):
                # Reached one of these WITHOUT it being the start of a fresh
                # if/else_if/else scan above -- i.e. it's nested INSIDE the if
                # block we already resolved and are currently walking the body
                # of (aNCFO's `IF = { limit = {...} ... ELSE = {...} }` shape,
                # as opposed to the sibling if/else_if/else chain shape). We
                # are, by construction, only ever walking the branch that WAS
                # taken, so this leftover partner must be skipped, never walked.
                i += 1
            else:
                # an intermediate named wrapper block, not a control block --
                # descend in case it groups other effects.
                _walk_body(content, depth + 1)
                i += 1

    hist_text = modfs.read(hist_path)
    _walk_body(hist_text, 0)

    for eff_name in extra_effects or []:
        if eff_name in effect_blocks and eff_name not in visited:
            visited.add(eff_name)
            res.trace.append(f"(extra entrypoint) -> {eff_name}")
            _walk_body(effect_blocks[eff_name].body, 1)

    res.certain -= res.bonus_only
    return res


_TOP_LEVEL_RE = re.compile(r"(?m)^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\{|\S+)")


def _iter_top_level(text: str):
    """Yield (name, kind, content) for each top-level statement in `text`, in
    order, WITHOUT descending into nested blocks -- kind is 'block' (content
    is the body between braces) or 'scalar' (content is the trimmed value up
    to end of line, comment stripped). This is what lets the tech walker
    process an if/else_if/else chain's branches individually instead of
    regexing the whole raw body at once.
    """
    pos = 0
    while pos < len(text):
        m = _TOP_LEVEL_RE.search(text, pos)
        if not m:
            break
        name = m.group(1)
        if m.group(2) == "{":
            open_idx = m.end() - 1
            end = _match_brace_local(text, open_idx)
            if end is None:
                pos = m.end()
                continue
            yield name, "block", text[m.end():end - 1]  # end-1 excludes the closing '}'
            pos = end
        else:
            line_end = text.find("\n", m.end())
            if line_end == -1:
                line_end = len(text)
            value = text[m.end() - len(m.group(2)):line_end]
            value = value.split("#", 1)[0].strip()
            yield name, "scalar", value
            pos = line_end


def _match_brace_local(text: str, open_idx: int) -> int | None:
    depth = 0
    for i in range(open_idx, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i + 1
    return None


def _extract_limit(body: str) -> str | None:
    """Return the raw content of a top-level `limit = { ... }` in `body`, if any."""
    for name, kind, content in _iter_top_level(body):
        if kind == "block" and name.lower() == "limit":
            return content
    return None


def _evaluate_limit(limit_text: str, assume_dlc: set[str]) -> bool | None:
    """True = take branch, False = skip branch, None = can't tell.
    Only understands `has_dlc = "X"` and `NOT = { has_dlc = "X" }` -- the two
    forms actually used to gate tech grants in this mod's effect files.
    Anything else (has_country_flag, random_list, ...) returns None so the
    caller marks its contents conditional rather than silently guessing.
    """
    m = re.search(r'has_dlc\s*=\s*"([^"]+)"', limit_text)
    not_m = re.search(r'NOT\s*=\s*\{\s*has_dlc\s*=\s*"([^"]+)"\s*\}', limit_text, re.IGNORECASE)
    if not_m:
        return not_m.group(1) not in assume_dlc
    if m:
        return m.group(1) in assume_dlc
    return None
