#!/usr/bin/env python3
"""Layered filesystem + brace-block parser for HOI4 mod trees.

Resolves how a mod's files layer over the base game via `replace_path`
declarations in descriptor.mod, and parses PDX-script `name = { ... }` blocks
without a full grammar (brace counting, comment-aware).

`replace_path` is exact-directory and non-recursive: a mod that replaces
`common/units` does NOT suppress vanilla `common/units/equipment/modules`
unless that exact subdirectory is also listed. This is why aNCFO_cco can
replace `common/units/equipment` wholesale while `common/units/equipment/modules`
still merges by filename with vanilla (aNCFO ships a deliberately-blank
`00_ship_modules.txt` there specifically to shadow vanilla's copy).

Generated by claude. Part of the equipment-variant-audit tooling
(.global_tools/equipment_variant_audit.py). No CLI of its own.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path


def _norm_rel(rel: str) -> str:
    """Normalize a mod-relative path: forward slashes, no leading/trailing slash."""
    return rel.strip().replace("\\", "/").strip("/")


@dataclass
class Block:
    """A single parsed `name = { ... }` entry."""

    name: str
    body: str  # raw text between (and not including) the braces
    origin_file: Path
    origin: str  # "mod" | "vanilla"
    line: int  # 1-indexed line of the opening `name = {`
    _children: dict | None = field(default=None, repr=False, compare=False)
    _children_list: list | None = field(default=None, repr=False, compare=False)

    def children(self) -> dict[str, "Block"]:
        """Lazily parse this block's own direct children as blocks, LAST
        duplicate wins (matches HOI4 override semantics for equipment/module
        IDs). For repeated sibling blocks of the same name that are each
        meaningful on their own (module_count_limit, can_convert_from, ...),
        use get_all_blocks() / children_all() instead -- this dict silently
        drops all but the last occurrence."""
        if self._children is None:
            self._children = {b.name: b for b in self.children_all()}
        return self._children

    def children_all(self) -> list["Block"]:
        """All direct child blocks, IN ORDER, duplicates included."""
        if self._children_list is None:
            self._children_list = parse_blocks_list(self.body, origin_file=self.origin_file, origin=self.origin, base_line=self.line)
        return self._children_list

    def get(self, key: str) -> str | None:
        """First scalar `key = value` at this block's top level (not nested)."""
        m = re.search(rf"(?m)^\s*{re.escape(key)}\s*=\s*(\S.*?)\s*(#.*)?$", _strip_comments_keep_lines(self.body))
        if not m:
            return None
        v = m.group(1).strip()
        if v.startswith("{"):
            return None  # it's a block, not a scalar; use children()/get_all()
        return v.strip('"')

    def get_all_scalars(self, key: str) -> list[str]:
        """All scalar `key = value` occurrences at this block's top level."""
        out = []
        for m in re.finditer(rf"(?m)^\s*{re.escape(key)}\s*=\s*(\S.*?)\s*(#.*)?$", _strip_comments_keep_lines(self.body)):
            v = m.group(1).strip()
            if not v.startswith("{"):
                out.append(v.strip('"'))
        return out

    def get_all_blocks(self, key: str) -> list["Block"]:
        """All child blocks literally named `key`, duplicates included
        (module_count_limit repeats, multiple can_convert_from, etc.)."""
        return [b for b in self.children_all() if b.name == key]

    def set_list(self, key: str) -> list[str]:
        """`key = { a b c }` -- a bare identifier list, not a block of sub-blocks."""
        m = re.search(rf"{re.escape(key)}\s*=\s*\{{([^{{}}]*)\}}", _strip_comments_keep_lines(self.body))
        if not m:
            return []
        return [tok.strip('"') for tok in m.group(1).split() if tok.strip('"')]


def strip_comments_keep_lines(text: str) -> str:
    """Public wrapper: remove `# ...` comments while preserving line count and
    column offsets elsewhere on each line. Callers scanning raw file text for
    a specific construct (e.g. `create_equipment_variant = {`) should run this
    first, or a commented-out example block gets matched as if it were live."""
    return _strip_comments_keep_lines(text)


def _strip_comments_keep_lines(text: str) -> str:
    """Remove `# ...` comments while preserving line count (for line-number accuracy)."""
    out_lines = []
    for line in text.split("\n"):
        # Don't strip '#' inside quoted strings.
        i = 0
        in_quotes = False
        cut = len(line)
        while i < len(line):
            c = line[i]
            if c == '"':
                in_quotes = not in_quotes
            elif c == "#" and not in_quotes:
                cut = i
                break
            i += 1
        out_lines.append(line[:cut])
    return "\n".join(out_lines)


def parse_blocks(
    text: str,
    *,
    unwrap: str | None = None,
    origin_file: Path | None = None,
    origin: str = "mod",
    base_line: int = 1,
) -> dict[str, Block]:
    """Parse top-level `name = { ... }` entries out of `text`, collapsed to a
    dict keyed by name, LAST duplicate wins -- matches HOI4's load-order-wins
    semantics for equipment and module IDs. For repeated meaningful siblings
    (module_count_limit, can_convert_from, ...) use parse_blocks_list or
    Block.get_all_blocks() instead; this dict silently drops repeats.

    If `unwrap` is given (e.g. "equipments"), first locate `unwrap = { ... }`
    and parse *its* direct children instead of the whole file's. See
    parse_blocks_list for the unwrap/comment/nesting details.
    """
    out: dict[str, Block] = {}
    for b in parse_blocks_list(text, unwrap=unwrap, origin_file=origin_file, origin=origin, base_line=base_line):
        out[b.name] = b
    return out


def parse_blocks_list(
    text: str,
    *,
    unwrap: str | None = None,
    origin_file: Path | None = None,
    origin: str = "mod",
    base_line: int = 1,
) -> list[Block]:
    """Parse top-level `name = { ... }` entries out of `text`, IN ORDER,
    keeping every duplicate.

    If `unwrap` is given (e.g. "equipments"), first locate `unwrap = { ... }`
    and parse *its* direct children instead of the whole file's. Handles the
    vanilla `equipment_modules = { limit = {...} mod1 = {...} mod2 = {...} }`
    wrapper shape, and files with multiple sibling wrapper blocks (e.g. two
    separate `equipment_modules = {}` blocks in one file). Skips a top-level
    `limit = { ... }` key when unwrapping -- it is DLC-gating metadata for
    the whole wrapper, not a module.

    Comments are stripped before brace counting so a stray '#' in a comment
    never desyncs the brace count. The scan advances past each matched
    block's closing brace before continuing (not re.finditer over the whole
    text), so a nested block (e.g. a slot name inside a hull's module_slots)
    is never mistaken for a sibling top-level entry.
    """
    clean = _strip_comments_keep_lines(text)

    if unwrap is not None:
        wrappers = []
        for m in re.finditer(rf"\b{re.escape(unwrap)}\s*=\s*\{{", clean):
            start = m.end() - 1
            end = _match_brace(clean, start)
            if end is not None:
                wrap_line = clean.count("\n", 0, m.start())
                wrappers.append((clean[m.end():end - 1], wrap_line))  # end-1 excludes the closing '}'
        out: list[Block] = []
        for body, wrap_line in wrappers:
            out.extend(
                b for b in parse_blocks_list(body, origin_file=origin_file, origin=origin, base_line=base_line + wrap_line)
                if b.name != "limit"
            )
        return out

    blocks: list[Block] = []
    pattern = re.compile(r"(?m)^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{")
    pos = 0
    while pos < len(clean):
        m = pattern.search(clean, pos)
        if not m:
            break
        name = m.group(1)
        start = m.end() - 1
        end = _match_brace(clean, start)
        if end is None:
            pos = m.end()
            continue
        body = clean[m.end():end - 1]  # end-1 excludes the closing '}' itself
        line_no = base_line + clean.count("\n", 0, m.start())
        blocks.append(Block(name=name, body=body, origin_file=origin_file or Path("<string>"), origin=origin, line=line_no))
        pos = end
    return blocks


def _match_brace(text: str, open_idx: int) -> int | None:
    """Return the index AFTER the matching '}' for the '{' at open_idx, or None."""
    depth = 0
    for i in range(open_idx, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i + 1
    return None


class ModFS:
    """Layered view of a mod's files over the base game install."""

    def __init__(self, mod_root: Path, vanilla_root: Path):
        self.mod_root = Path(mod_root)
        self.vanilla_root = Path(vanilla_root)
        self.replace_paths: set[str] = self._load_replace_paths()

    def _load_replace_paths(self) -> set[str]:
        descriptor = self.mod_root / "descriptor.mod"
        if not descriptor.is_file():
            raise SystemExit(f"error: no descriptor.mod at {self.mod_root} -- is this a mod root?")
        text = descriptor.read_text(encoding="utf-8", errors="replace")
        paths = set()
        for m in re.finditer(r'replace_path\s*=\s*"([^"]+)"', text):
            rp = _norm_rel(m.group(1))
            # A replace_path naming a bare file (e.g. "common/achievements.txt")
            # has no directory-listing meaning for us; ignore it here.
            if "." in rp.rsplit("/", 1)[-1]:
                continue
            paths.add(rp)
        return paths

    def list_dir(self, rel: str, pattern: str = "*.txt") -> list[tuple[Path, str]]:
        """Return [(path, origin)] for every matching file visible at `rel`,
        mod files first (by name), then vanilla files not shadowed by a
        same-named mod file -- UNLESS `rel` is under a replace_path, in
        which case vanilla contributes nothing at all for this directory.
        """
        rel = _norm_rel(rel)
        seen: dict[str, tuple[Path, str]] = {}

        mod_dir = self.mod_root / rel
        if mod_dir.is_dir():
            for p in sorted(mod_dir.glob(pattern)):
                if p.is_file():
                    seen[p.name] = (p, "mod")

        if rel not in self.replace_paths:
            vanilla_dir = self.vanilla_root / rel
            if vanilla_dir.is_dir():
                for p in sorted(vanilla_dir.glob(pattern)):
                    if p.is_file() and p.name not in seen:
                        seen[p.name] = (p, "vanilla")

        return [seen[k] for k in sorted(seen)]

    def read(self, path: Path) -> str:
        return path.read_text(encoding="utf-8", errors="replace")

    def find_country_history(self, tag: str) -> Path | None:
        """Locate `history/countries/<TAG> - *.txt` or `<TAG>*.txt`, mod first.

        More than one file can match the glob -- e.g. aNCFO_cco ships both
        `LSM - Linsongese Shidai Mandate.txt` (the real country file) AND
        `LSM - Linsongese Nations.txt` (an `every_country = { limit = {...} }`
        cosmetic-ideas file that happens to share the "LSM " filename prefix
        by coincidence, not by tag ownership). Filesystem glob order is not
        guaranteed, so picking match[0] blindly can silently resolve to the
        wrong file. Disambiguate by requiring a `capital = <num>` line near
        the top, which every real country history file has and a shared
        every_country wrapper file does not.
        """
        def is_real_country_file(p: Path) -> bool:
            try:
                head = p.read_text(encoding="utf-8", errors="replace")[:2000]
            except OSError:
                return False
            return bool(re.search(r"(?m)^\s*capital\s*=\s*\d+", head))

        for base in (
            self.mod_root,
            self.vanilla_root if "history/countries" not in self.replace_paths else None,
        ):
            if base is None:
                continue
            d = base / "history" / "countries"
            if not d.is_dir():
                continue
            for pattern in (f"{tag} - *.txt", f"{tag}*.txt"):
                matches = sorted(d.glob(pattern))
                if not matches:
                    continue
                real = [p for p in matches if is_real_country_file(p)]
                return real[0] if real else matches[0]
        return None
