#!/usr/bin/env python3
"""Audit and scaffold `create_equipment_variant` blocks for any HOI4 mod on
this root -- naval, tank, and plane equipment alike.

Why this exists: a `create_equipment_variant` block fails SILENTLY when it
references a slot the hull doesn't have, a module category the slot
disallows, or a module/type the target nation hasn't researched -- the
ship/tank/plane just never appears, usually with no error.log entry at all.
Getting this right by reading source means holding a multi-thousand-line
module file, a hull file, and the tech tree in context at once. This tool
answers "what can legally go in this slot for this nation" directly.

Behavior is fully derived per-mod from descriptor.mod's replace_path
declarations plus the mod's actual file tree -- nothing about aNCFO_cco,
CrC_antarctica, or any other mod is hardcoded here. See _hoi4_modfs.py for
the layering rule and _hoi4_equipment_db.py for slot/tech resolution.

Generated by claude. Part of the shared-naval-equipment / shared-tank-equipment
/ shared-plane-equipment agents' mandatory tool workflow -- see
.claude/docs/equipment-variant-rules.md.

Usage (run from a mod's tools/ directory, or pass --mod explicitly):
    python equipment_variant_audit.py types --domain naval --concrete
    python equipment_variant_audit.py slots --type vnr_ship_hull_heavy_1
    python equipment_variant_audit.py modules --type vnr_ship_hull_heavy_1 --tag EPY
    python equipment_variant_audit.py techs --tag EPY
    python equipment_variant_audit.py scaffold --type vnr_ship_hull_heavy_1 --tag EPY --name "Kirin Class"
    python equipment_variant_audit.py check --tag EPY
    python equipment_variant_audit.py check --json
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _hoi4_modfs import Block, ModFS, parse_blocks, strip_comments_keep_lines
from _hoi4_equipment_db import (
    EquipmentDB, TechGate, TechResolution, DEFAULT_ASSUME_DLC,
    load_tech_gate, resolve_country_techs,
)

DEFAULT_VANILLA = r"D:\Program Files\SteamLibrary\steamapps\common\Hearts of Iron IV"

SCAN_DIRS = [
    "history/countries", "common/scripted_effects", "common/national_focus",
    "common/decisions", "common/technologies", "common/special_projects",
    "events",
]

DOMAIN_HINTS = {
    "naval": ("ship_", "naval"),
    "land": ("tank_", "armor", "chassis", "mekhani"),
    "air": ("plane_", "air", "fighter", "bomber"),
}


# ---- setup ----------------------------------------------------------------

def load_config(mod_root: Path) -> dict:
    cfg_path = mod_root / "tools" / "equipment_variant.config.json"
    if cfg_path.is_file():
        try:
            return json.loads(cfg_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as e:
            print(f"warning: could not read {cfg_path}: {e}", file=sys.stderr)
    return {}


def build_env(args) -> tuple[ModFS, EquipmentDB, TechGate, dict]:
    mod_root = Path(args.mod).resolve() if args.mod else Path(__file__).resolve().parents[1]
    if not (mod_root / "descriptor.mod").is_file():
        raise SystemExit(f"error: {mod_root} has no descriptor.mod -- pass --mod <mod root>")
    cfg = load_config(mod_root)
    vanilla_root = Path(args.vanilla or cfg.get("vanilla_root") or os.environ.get("HOI4_PATH") or DEFAULT_VANILLA)
    modfs = ModFS(mod_root, vanilla_root)
    db = EquipmentDB(modfs)
    gate = load_tech_gate(modfs)
    return modfs, db, gate, cfg


def assume_dlc_from(cfg: dict) -> set[str]:
    dlc = cfg.get("assume_dlc")
    return set(dlc) if dlc else set(DEFAULT_ASSUME_DLC)


def guess_domain(type_name: str, db: EquipmentDB) -> str:
    """Best-effort classification for filtering `types` output. Based on the
    root archetype's own name and origin filename only -- NOT the `type =`
    value list, which for planes includes naval-sounding tags like
    naval_bomber that would otherwise misclassify aircraft as naval."""
    chain = db.chain(type_name)
    root = chain[-1] if chain else type_name
    fname = db.types[root].block.origin_file.name.lower() if root in db.types else ""
    hay = f"{type_name} {root} {fname}".lower()
    for domain, hints in DOMAIN_HINTS.items():
        if any(h in hay for h in hints):
            return domain
    return "unknown"


# ---- command: types ---------------------------------------------------

def cmd_types(args, modfs, db, gate, cfg):
    rows = []
    for name, d in sorted(db.types.items()):
        domain = guess_domain(name, db)
        if args.domain and domain != args.domain:
            continue
        if args.concrete and d.is_archetype:
            continue
        rows.append((name, "archetype" if d.is_archetype else "type", domain,
                      ",".join(d.equip_type) or "-", d.block.origin_file.name))
    if not rows:
        print("(no matching types)")
        return
    w = max(len(r[0]) for r in rows)
    for name, kind, domain, etype, fname in rows:
        print(f"{name:<{w}}  {kind:<9} {domain:<7} type={etype:<20} <- {fname}")


# ---- command: slots ---------------------------------------------------

def cmd_slots(args, modfs, db, gate, cfg):
    if args.type not in db.types:
        raise SystemExit(f"error: unknown type {args.type!r} (run `types` to list what's visible)")
    if db.is_archetype(args.type):
        print(f"NOTE: {args.type} is an archetype -- not directly usable as a variant `type`. "
              f"Showing its slots anyway since concrete children inherit them.")
    slots = db.resolve_slots(args.type)
    if not slots:
        print(f"(no module_slots resolved for {args.type} -- check its archetype chain: "
              f"{' -> '.join(db.chain(args.type))})")
    else:
        w = max(len(s) for s in slots)
        for name, slot in slots.items():
            req = "required" if slot.required else "optional"
            cats = ", ".join(slot.allowed_categories) or "(none declared)"
            print(f"{name:<{w}}  {req:<8} from={slot.origin_type:<28} categories: {cats}")

    limits = db.resolve_count_limits(args.type)
    if limits:
        print("\nmodule_count_limit:")
        for lim in limits:
            conds = ", ".join(f"{k}={v}" for k, v in sorted(lim.conditions)) or "(none)"
            cnt = "any" if lim.count is None and lim.op == "any" else lim.count
            print(f"  {conds}: count {lim.op} {cnt}  (from {lim.origin_type})")

    defaults = db.resolve_defaults(args.type)
    if defaults:
        print("\ndefault_modules:")
        for slot, mod in defaults.items():
            print(f"  {slot} = {mod}")


# ---- command: modules ---------------------------------------------------

def cmd_modules(args, modfs, db, gate, cfg):
    if args.type not in db.types:
        raise SystemExit(f"error: unknown type {args.type!r}")
    slots = db.resolve_slots(args.type)
    if not slots:
        raise SystemExit(f"error: no slots resolved for {args.type} -- run `slots --type {args.type}` first")

    researched: set[str] = set()
    uncertain: set[str] = set()
    trace_note = ""
    if args.tag:
        assume_dlc = assume_dlc_from(cfg)
        res = resolve_country_techs(modfs, args.tag, assume_dlc=assume_dlc,
                                     extra_effects=cfg.get("extra_tech_effect_entrypoints"))
        researched = res.certain
        uncertain = set(res.conditional)
        trace_note = f"  (techs resolved for {args.tag}: {len(researched)} certain, " \
                     f"{len(res.conditional)} conditional, {len(res.bonus_only)} bonus-only -- run `techs --tag {args.tag}` for detail)"

    by_category: dict[str, list[str]] = {}
    for mname, mdef in db.modules.items():
        if mdef.category:
            by_category.setdefault(mdef.category, []).append(mname)

    for slot_name, slot in slots.items():
        print(f"\n[{slot_name}] required={slot.required}")
        if trace_note and slot_name == next(iter(slots)):
            print(trace_note)
        any_shown = False
        for cat in slot.allowed_categories:
            for mname in sorted(by_category.get(cat, [])):
                any_shown = True
                if args.tag:
                    status, gating = gate.status(mname, "module", researched, uncertain)
                    tag_str = f"needs one of: {', '.join(sorted(gating))}" if status in ("LOCKED", "UNCERTAIN") else ""
                    print(f"  {status:<9} {mname:<32} (category={cat}) {tag_str}")
                else:
                    print(f"  {mname:<32} (category={cat})")
        if not any_shown:
            print("  (no modules found with an allowed category -- category name may be a typo, "
                  "or this slot's modules live in a file this tool hasn't loaded)")


# ---- command: techs ---------------------------------------------------

def cmd_techs(args, modfs, db, gate, cfg):
    assume_dlc = assume_dlc_from(cfg)
    res = resolve_country_techs(modfs, args.tag, assume_dlc=assume_dlc,
                                 extra_effects=cfg.get("extra_tech_effect_entrypoints"))
    print(f"CERTAIN ({len(res.certain)}):")
    for t in sorted(res.certain):
        print(f"  {t}")
    print(f"\nCONDITIONAL ({len(res.conditional)}):")
    for t, cond in sorted(res.conditional.items()):
        print(f"  {t}  [{cond}]")
    print(f"\nBONUS-ONLY, not researched ({len(res.bonus_only)}):")
    for t in sorted(res.bonus_only):
        print(f"  {t}")
    print("\ntrace:")
    for line in res.trace:
        print(f"  {line}")


# ---- command: scaffold ---------------------------------------------------

def cmd_scaffold(args, modfs, db, gate, cfg):
    if args.type not in db.types:
        raise SystemExit(f"error: unknown type {args.type!r}")
    if db.is_archetype(args.type):
        raise SystemExit(f"error: {args.type} is an archetype, not a concrete type (V003). "
                          f"Run `types --concrete` for valid choices.")

    slots = db.resolve_slots(args.type)
    researched: set[str] = set()
    if args.tag:
        assume_dlc = assume_dlc_from(cfg)
        res = resolve_country_techs(modfs, args.tag, assume_dlc=assume_dlc,
                                     extra_effects=cfg.get("extra_tech_effect_entrypoints"))
        researched = res.certain

    by_category: dict[str, list[str]] = {}
    for mname, mdef in db.modules.items():
        if mdef.category:
            by_category.setdefault(mdef.category, []).append(mname)

    def pick(slot) -> str:
        if not slot.required:
            return "empty"
        best, best_depth = None, -1
        for cat in slot.allowed_categories:
            for mname in by_category.get(cat, []):
                if args.tag:
                    status, _ = gate.status(mname, "module", researched)
                    if status != "ENABLED":
                        continue
                depth = 0
                cur = mname
                seen = set()
                while cur in db.modules and db.modules[cur].parent and cur not in seen:
                    seen.add(cur)
                    cur = db.modules[cur].parent
                    depth += 1
                if depth > best_depth:
                    best, best_depth = mname, depth
        return best or "empty"

    modules = {name: pick(slot) for name, slot in slots.items()}
    unfilled_required = [n for n, s in slots.items() if s.required and modules[n] == "empty"]

    lines = ["create_equipment_variant = {"]
    if args.name:
        lines.append(f'\tname = "{args.name}"')
    lines.append(f"\ttype = {args.type}")
    if args.parent_version is not None:
        lines.append(f"\tparent_version = {args.parent_version}")
    if args.role_icon is not None:
        lines.append(f"\trole_icon_index = {args.role_icon}")
    lines.append("\tmodules = {")
    for slot_name, mod in modules.items():
        lines.append(f"\t\t{slot_name} = {mod}")
    lines.append("\t}")
    lines.append("}")
    block_text = "\n".join(lines)

    if unfilled_required:
        print(f"error: cannot scaffold a valid block -- no ENABLED module found for required slot(s): "
              f"{', '.join(unfilled_required)}", file=sys.stderr)
        if args.tag:
            print("hint: the nation may not have researched anything for this slot yet, "
                  "or pass a different --type.", file=sys.stderr)
        raise SystemExit(1)

    print(block_text)


# ---- command: check ---------------------------------------------------

def cmd_check(args, modfs, db, gate, cfg):
    _TECH_CACHE.clear()
    global _env_modfs
    _env_modfs = modfs

    naming_stubs = None
    stub_rel = cfg.get("naming_stub_file")
    if stub_rel:
        naming_stubs = set()
        stub_path = modfs.mod_root / stub_rel
        if stub_path.is_file():
            stub_text = modfs.read(stub_path)
            naming_stubs = set(parse_blocks(stub_text, unwrap="equipments", origin_file=stub_path, origin="mod").keys())
        else:
            print(f"warning: configured naming_stub_file {stub_rel} not found", file=sys.stderr)

    findings = []
    files_scanned = 0
    if args.file:
        # Validate an arbitrary path directly -- e.g. a scratch file holding a
        # scaffolded block not yet pasted anywhere -- rather than requiring it
        # already live under one of SCAN_DIRS.
        fpath = Path(args.file).resolve()
        if not fpath.is_file():
            raise SystemExit(f"error: {fpath} not found")
        files_scanned = 1
        # best-effort scan_dir context, for the history-vs-elsewhere ERROR/WARN split
        scan_dir = next((d for d in SCAN_DIRS if d.replace("/", os.sep) in str(fpath)), "")
        findings.extend(_check_file(fpath, modfs.read(fpath), scan_dir, args.tag, db, gate, cfg, naming_stubs))
    else:
        for scan_dir in SCAN_DIRS:
            for path, origin in modfs.list_dir(scan_dir):
                if origin != "mod":
                    continue  # never flag vanilla content
                files_scanned += 1
                text = modfs.read(path)
                findings.extend(_check_file(path, text, scan_dir, args.tag, db, gate, cfg, naming_stubs))

    for dup_id, files in db.duplicates:
        findings.append({"file": str(modfs.mod_root), "line": 0, "severity": "WARN", "rule": "V016",
                          "message": f"equipment id {dup_id!r} defined in {len(files)} loaded files "
                                     f"({', '.join(files)}) -- last-loaded wins"})

    if args.json:
        print(json.dumps([f.__dict__ if hasattr(f, "__dict__") else f for f in findings], default=str, indent=2))
    else:
        for f in findings:
            print(f"{f['file']}:{f['line']}: [{f['severity']}] {f['rule']} {f['message']}")
        errors = sum(1 for f in findings if f["severity"] == "ERROR")
        warns = sum(1 for f in findings if f["severity"] == "WARN")
        print(f"\n{files_scanned} file(s) scanned, {len(findings)} finding(s): {errors} error(s), {warns} warning(s)")

    if any(f["severity"] == "ERROR" for f in findings):
        sys.exit(1)


def _tag_for_context(path: Path, scan_dir: str, block: Block) -> str | None:
    if scan_dir == "history/countries":
        m = re.match(r"([A-Z0-9]{3})\s*-", path.name)
        if m:
            return m.group(1)
    return None


def _check_file(path, text, scan_dir, cli_tag, db, gate, cfg, naming_stubs):
    out = []
    seen_names: dict[str, list[int]] = {}

    def emit(line, severity, rule, message):
        out.append({"file": str(path), "line": line, "severity": severity, "rule": rule, "message": message})

    # Strip comments first (preserving line count) so a commented-out example
    # block (e.g. `#create_equipment_variant = { ... }` left in a history
    # file as reference) is never mistaken for a live one.
    text = strip_comments_keep_lines(text)

    # find every create_equipment_variant occurrence anywhere in the file,
    # including nested inside history/scripted-effect wrappers.
    for m in re.finditer(r"create_equipment_variant\s*=\s*\{", text):
        line_no = text.count("\n", 0, m.start()) + 1
        end = m.end() - 1
        depth = 0
        close = None
        for i in range(end, len(text)):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    close = i + 1
                    break
        if close is None:
            continue
        body = text[m.end():close - 1]  # close-1 excludes the closing '}'
        blk = Block("create_equipment_variant", body, path, "mod", line_no)

        tname = blk.get("type")
        if not tname:
            emit(line_no, "ERROR", "V001", "create_equipment_variant has no `type`")
            continue
        if tname not in db.types:
            emit(line_no, "ERROR", "V002", f"type={tname} is not a known equipment type visible to this mod")
            continue
        if db.is_archetype(tname):
            emit(line_no, "ERROR", "V003", f"type={tname} is an archetype, not a concrete type")
            continue

        slots = db.resolve_slots(tname)
        defaults = db.resolve_defaults(tname)
        mods_block = blk.children().get("modules")
        installed: dict[str, str] = dict(defaults)
        if mods_block is not None:
            for line in mods_block.body.splitlines():
                mm = re.match(r"\s*([A-Za-z0-9_]+)\s*=\s*([A-Za-z0-9_]+)", line)
                if mm:
                    installed[mm.group(1)] = mm.group(2)

        for slot_name, mod_name in installed.items():
            if slot_name not in slots:
                emit(line_no, "ERROR", "V004", f"slot={slot_name} does not exist on type={tname}")
                continue
            if mod_name == "empty":
                continue
            if mod_name not in db.modules:
                emit(line_no, "ERROR", "V005", f"module={mod_name} in slot={slot_name} is unknown")
                continue
            slot = slots[slot_name]
            mcat = db.modules[mod_name].category
            if slot.allowed_categories and mcat not in slot.allowed_categories:
                emit(line_no, "ERROR", "V006",
                     f"module={mod_name} (category={mcat}) not allowed in slot={slot_name} "
                     f"(allows: {', '.join(slot.allowed_categories)})")

        for slot_name, slot in slots.items():
            if slot.required and installed.get(slot_name, "empty") == "empty":
                emit(line_no, "ERROR", "V007", f"required slot={slot_name} is unfilled")

        for lim in db.resolve_count_limits(tname):
            count = 0
            for slot_name, mod_name in installed.items():
                if mod_name == "empty":
                    continue
                mdef = db.modules.get(mod_name)
                if ("module", mod_name) in lim.conditions:
                    count += 1
                elif mdef and ("category", mdef.category) in lim.conditions:
                    count += 1
            if lim.op == "<" and lim.count is not None and count >= lim.count:
                emit(line_no, "ERROR", "V008", f"module_count_limit violated: {count} >= {lim.count} for "
                     f"{', '.join(f'{k}={v}' for k, v in sorted(lim.conditions))}")
            elif lim.op == ">" and lim.count is not None and count <= lim.count:
                emit(line_no, "ERROR", "V008", f"module_count_limit violated: {count} <= {lim.count} for "
                     f"{', '.join(f'{k}={v}' for k, v in sorted(lim.conditions))}")
            elif lim.op == "=" and lim.count is not None and count != lim.count:
                emit(line_no, "ERROR", "V008", f"module_count_limit violated: {count} != {lim.count} for "
                     f"{', '.join(f'{k}={v}' for k, v in sorted(lim.conditions))}")

        installed_cats = {db.modules[m].category for m in installed.values() if m in db.modules and db.modules[m].category}
        for mod_name in installed.values():
            mdef = db.modules.get(mod_name)
            if mdef and mdef.forbid_module_categories:
                hit = installed_cats & set(mdef.forbid_module_categories)
                if hit:
                    emit(line_no, "ERROR", "V009",
                         f"module={mod_name} forbids categories {sorted(hit)} which are also installed")

        allow_without_tech = blk.get("allow_without_tech") == "yes"
        tag = cli_tag or _tag_for_context(path, scan_dir, blk)
        if allow_without_tech:
            emit(line_no, "WARN", "V010",
                 f"type={tname}: allow_without_tech = yes -- tech gating for this variant is intentionally skipped")
        elif tag:
            severity = "ERROR" if scan_dir == "history/countries" else "WARN"
            researched, uncertain = _tech_cache(cfg, tag, db)
            status, gating = gate.status(tname, "equip", researched, uncertain)
            if status == "LOCKED":
                emit(line_no, severity, "V010", f"type={tname} is locked for {tag} "
                     f"(needs one of: {', '.join(sorted(gating))}) and allow_without_tech is not set")
            elif status == "UNCERTAIN":
                # A gating tech exists only behind a condition this tool can't
                # evaluate statically (e.g. any_owned_state = is_coastal) --
                # genuinely unknown, not provably locked, so always WARN
                # regardless of scan_dir, never the history-dir hard ERROR.
                emit(line_no, "WARN", "V010", f"type={tname}'s tech gate for {tag} could not be "
                     f"statically resolved (needs one of: {', '.join(sorted(gating))}, "
                     f"behind an unevaluated condition -- verify manually)")
            for slot_name, mod_name in installed.items():
                if mod_name == "empty" or mod_name not in db.modules:
                    continue
                mstatus, mgating = gate.status(mod_name, "module", researched, uncertain)
                if mstatus == "LOCKED":
                    emit(line_no, severity, "V011", f"module={mod_name} in slot={slot_name} is locked for {tag} "
                         f"(needs one of: {', '.join(sorted(mgating))})")
                elif mstatus == "UNCERTAIN":
                    emit(line_no, "WARN", "V011", f"module={mod_name} in slot={slot_name}: tech gate for {tag} "
                         f"could not be statically resolved (needs one of: {', '.join(sorted(mgating))}, "
                         f"behind an unevaluated condition -- verify manually)")

        name = blk.get("name")
        if name:
            key = f"{tag or '?'}::{name}"
            seen_names.setdefault(key, []).append(line_no)

        if naming_stubs is not None:
            dvn = blk.get("derived_variant_name")
            if dvn and dvn not in naming_stubs:
                emit(line_no, "WARN", "V015",
                     f"derived_variant_name={dvn} has no matching stub in the configured naming_stub_file")

    for key, lines_ in seen_names.items():
        if len(lines_) > 1:
            for ln in lines_[1:]:
                emit(ln, "WARN", "V013", f"duplicate variant name for {key.split('::', 1)[1]!r} "
                     f"(also at line {lines_[0]})")

    return out


_TECH_CACHE: dict[tuple[int, str], tuple[set, set]] = {}


def _tech_cache(cfg, tag, db) -> tuple[set, set]:
    """Returns (researched, uncertain) for `tag`, memoized per (db, tag) since
    `check` calls this once per variant block and re-resolving a country's
    full tech chain every time would be needlessly expensive."""
    key = (id(db), tag)
    if key not in _TECH_CACHE:
        assume_dlc = assume_dlc_from(cfg)
        res = resolve_country_techs(_env_modfs, tag, assume_dlc=assume_dlc,
                                     extra_effects=cfg.get("extra_tech_effect_entrypoints"))
        _TECH_CACHE[key] = (res.certain, set(res.conditional))
    return _TECH_CACHE[key]


_env_modfs: ModFS | None = None


# ---- main ---------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--mod", help="mod root (default: parent of this script's tools/ dir)")
    p.add_argument("--vanilla", help="base game install root (default: $HOI4_PATH or the hardcoded Steam path)")
    sub = p.add_subparsers(dest="command", required=True)

    sp = sub.add_parser("types", help="list resolved equipment types")
    sp.add_argument("--domain", choices=["naval", "land", "air"])
    sp.add_argument("--concrete", action="store_true", help="exclude archetypes")

    sp = sub.add_parser("slots", help="resolved module_slots / count limits / defaults for a type")
    sp.add_argument("--type", required=True)

    sp = sub.add_parser("modules", help="legal modules per slot, optionally tech-gated for a tag")
    sp.add_argument("--type", required=True)
    sp.add_argument("--tag")

    sp = sub.add_parser("techs", help="resolve a country's researched tech set")
    sp.add_argument("--tag", required=True)

    sp = sub.add_parser("scaffold", help="emit a paste-ready, pre-validated create_equipment_variant block")
    sp.add_argument("--type", required=True)
    sp.add_argument("--tag")
    sp.add_argument("--name")
    sp.add_argument("--parent-version", type=int, dest="parent_version")
    sp.add_argument("--role-icon", type=int, dest="role_icon")

    sp = sub.add_parser("check", help="validate existing create_equipment_variant blocks in mod-owned files")
    sp.add_argument("--tag", help="assume this tag's tech set for blocks outside history/countries")
    sp.add_argument("--file", help="limit to one file")
    sp.add_argument("--json", action="store_true")

    args = p.parse_args()
    modfs, db, gate, cfg = build_env(args)
    global _env_modfs
    _env_modfs = modfs

    {
        "types": cmd_types, "slots": cmd_slots, "modules": cmd_modules,
        "techs": cmd_techs, "scaffold": cmd_scaffold, "check": cmd_check,
    }[args.command](args, modfs, db, gate, cfg)


if __name__ == "__main__":
    main()
