#!/usr/bin/env python3
"""Query and validate HOI4 events for any mod on this root.

Checks EVENT STRUCTURE (namespace/ID validity, loc key presence, a few
provably-safe contradictions) -- not event CONTENT (what an option should
do, its prose, its scoping design). That stays the model's job.

One design constraint confirmed directly, not assumed: `MRC.12`
(events/MRC.Merchant_Republic.txt:811) is `is_triggered_only = yes` with NO
discoverable caller anywhere in the codebase -- it's a pure dispatcher, each
option firing another event by ID. An event needing no caller is completely
normal. This tool NEVER reports "no caller found" as a finding, on purpose
-- there is no liveness/reachability check here at all, and none should be
added later without re-confirming this is still the right call.

Also confirmed: effect/trigger SCOPE validity inside an option (is this
reference actually legal from the event's declared scope) is not checked --
would need a real scope-tracker, out of scope for this tool. Treat this the
same way the equipment tool's `duplicate_archetypes` gap was treated: a
known, stated limitation, not silently pretended away.

Generated by claude. Backs aNCFO_cco-event-builder's workflow -- see that
agent file and .claude/docs/tooling-reference.md.

Usage (run from a mod's tools/ directory, or pass --mod explicitly):
    python event_audit.py list --namespace MRC
    python event_audit.py check --file events/MRC.Merchant_Republic.txt
    python event_audit.py check
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _hoi4_modfs import Block, ModFS, parse_blocks_list, strip_comments_keep_lines

DEFAULT_VANILLA = r"D:\Program Files\SteamLibrary\steamapps\common\Hearts of Iron IV"
EVENT_KINDS = ("country_event", "news_event", "state_event", "operative_leader_event")


def build_env(args):
    mod_root = Path(args.mod).resolve() if args.mod else Path(__file__).resolve().parents[1]
    if not (mod_root / "descriptor.mod").is_file():
        raise SystemExit(f"error: {mod_root} has no descriptor.mod -- pass --mod <mod root>")
    vanilla_root = Path(args.vanilla or os.environ.get("HOI4_PATH") or DEFAULT_VANILLA)
    return ModFS(mod_root, vanilla_root)


class EventFile:
    def __init__(self, path: Path, namespaces: list[tuple[int, str]], events: list[Block]):
        self.path = path
        self.namespaces = namespaces  # [(line, ns), ...] in file order
        self.events = events  # Block per top-level event kind

    def namespaces_for_line(self, line: int) -> list[str]:
        """A file can declare MULTIPLE `add_namespace` values -- confirmed:
        aNCFO_cco/events/MRC.Merchant_Republic.txt has three
        (MRC_election, MRC, MRC_state at lines 1/300/1238). Per
        Wiki_Event.txt: 'a namespace must be first created before defining
        any events that use it' -- namespaces ACCUMULATE, they do not
        replace each other. An event at line 1239 (after MRC_state is
        declared at 1238) can still validly use the MRC namespace declared
        far earlier at line 300; it is not restricted to the most recently
        declared one. So this returns every namespace declared before
        `line`, not a single "current" one."""
        return [ns for ns_line, ns in self.namespaces if ns_line <= line]

    def best_namespace_match(self, eid: str, line: int) -> str | None:
        """Longest declared-namespace prefix that `eid` starts with, since a
        namespace can itself contain dots (Wiki_Event.txt:
        `add_namespace = my_event.subtopic`), so a naive last-dot split
        would misattribute a dotted namespace. None if no declared
        namespace matches."""
        candidates = [ns for ns in self.namespaces_for_line(line) if eid.startswith(f"{ns}.")]
        return max(candidates, key=len) if candidates else None


def load_all_events(modfs: ModFS) -> list[EventFile]:
    files: list[EventFile] = []
    for path, origin in modfs.list_dir("events"):
        if origin != "mod":
            continue
        text = modfs.read(path)
        clean = strip_comments_keep_lines(text)
        namespaces = [
            (clean.count("\n", 0, m.start()) + 1, m.group(1))
            for m in re.finditer(r"(?m)^\s*add_namespace\s*=\s*(\S+)", clean)
        ]
        events = [b for b in parse_blocks_list(text, origin_file=path, origin=origin) if b.name in EVENT_KINDS]
        files.append(EventFile(path, namespaces, events))
    return files


# ---- command: list ---------------------------------------------------

def cmd_list(args, modfs):
    files = load_all_events(modfs)
    if args.file:
        files = [f for f in files if f.path.name == args.file or str(f.path).endswith(args.file)]
    any_shown = False
    for ef in files:
        # A file can declare multiple add_namespace values (confirmed:
        # MRC.Merchant_Republic.txt has three) -- filter per event's own
        # resolved namespace, not the whole file, or --namespace would miss
        # (or over-include) events in a multi-namespace file.
        rows = []
        for ev in ef.events:
            eid = ev.get("id") or ""
            ns = ef.best_namespace_match(eid, ev.line)
            if args.namespace and ns != args.namespace:
                continue
            rows.append((ev, ns))
        if not rows:
            continue
        any_shown = True
        print(f"\n{ef.path.name}")
        for ev, ns in rows:
            eid = ev.get("id") or "?"
            triggered = ev.get("is_triggered_only") == "yes"
            opts = ev.get_all_blocks("option")
            title = ev.get("title") or "?"
            print(f"  [{ns or '?'}] {eid:<20} is_triggered_only={triggered!s:<5} options={len(opts):<3} title={title}")
    if not any_shown:
        print("(no matching events)")


# ---- command: check ---------------------------------------------------

def cmd_check(args, modfs):
    files = load_all_events(modfs)
    if args.file:
        files = [f for f in files if f.path.name == args.file or str(f.path).endswith(args.file)]

    loc_keys = _load_loc_keys(modfs)

    findings = []

    def emit(path, line, severity, rule, message):
        findings.append({"file": str(path), "line": line, "severity": severity, "rule": rule, "message": message})

    seen_ids: dict[str, list[tuple[Path, int]]] = {}

    for ef in files:
        for ev in ef.events:
            eid = ev.get("id")
            if not eid:
                emit(ef.path, ev.line, "ERROR", "E001", "event has no `id`")
                continue

            # E001 namespace mismatch -- eid must match ONE of the namespaces
            # declared anywhere earlier in the file (they accumulate, see
            # EventFile.namespaces_for_line's docstring), not just the latest
            declared = ef.namespaces_for_line(ev.line)
            if declared and ef.best_namespace_match(eid, ev.line) is None:
                emit(ef.path, ev.line, "ERROR", "E001",
                     f"{eid}: does not match any namespace declared earlier in this file ({', '.join(declared)})")
            seen_ids.setdefault(eid, []).append((ef.path, ev.line))

            # E003 is_triggered_only + mean_time_to_happen both present
            triggered = ev.get("is_triggered_only") == "yes"
            mtth = ev.children().get("mean_time_to_happen")
            if triggered and mtth is not None and strip_comments_keep_lines(mtth.body).strip():
                emit(ef.path, ev.line, "ERROR", "E003",
                     f"{eid}: is_triggered_only = yes but also has a non-empty mean_time_to_happen -- contradictory")

            # E005 title/desc loc keys
            if loc_keys is not None:
                title_key = ev.get("title")
                desc_key = ev.get("desc")
                if title_key and title_key not in loc_keys:
                    emit(ef.path, ev.line, "ERROR", "E005", f"{eid}: title={title_key} has no matching localisation key")
                if desc_key and desc_key not in loc_keys:
                    emit(ef.path, ev.line, "ERROR", "E005", f"{eid}: desc={desc_key} has no matching localisation key")

            # E004 / E006 option name keys
            opts = ev.get_all_blocks("option")
            opt_names = [o.get("name") for o in opts]
            pattern_counts = Counter(_key_pattern(n, eid) for n in opt_names if n)
            majority_pattern = pattern_counts.most_common(1)[0][0] if pattern_counts else None
            for o in opts:
                name = o.get("name")
                if not name:
                    continue
                if loc_keys is not None and name not in loc_keys:
                    emit(ef.path, o.line, "ERROR", "E004", f"{eid}: option name={name} has no matching localisation key")
                pat = _key_pattern(name, eid)
                if majority_pattern and pat != majority_pattern and len(opts) > 1:
                    emit(ef.path, o.line, "WARN", "E006",
                         f"{eid}: option name={name} differs from this file's own established option-key "
                         f"pattern ({majority_pattern}) -- verify this is deliberate (e.g. an AI-only option "
                         f"intentionally reusing another event's key), not a copy-paste mistake")

    # E002 duplicate event id within a namespace, across all loaded files
    for eid, locs in seen_ids.items():
        if len(locs) > 1:
            for path, line in locs[1:]:
                emit(path, line, "ERROR", "E002", f"{eid}: duplicate event id (also defined at {locs[0][0].name}:{locs[0][1]})")

    if args.json:
        print(json.dumps(findings, indent=2))
    else:
        for f in findings:
            print(f"{f['file']}:{f['line']}: [{f['severity']}] {f['rule']} {f['message']}")
        errors = sum(1 for f in findings if f["severity"] == "ERROR")
        warns = sum(1 for f in findings if f["severity"] == "WARN")
        print(f"\n{len(findings)} finding(s): {errors} error(s), {warns} warning(s)")

    if any(f["severity"] == "ERROR" for f in findings):
        sys.exit(1)


def _key_pattern(name: str, eid: str) -> str:
    """Reduce an option's `name =` key to a comparable shape, e.g.
    'MRC.12.OptA' -> 'SAMEID.OptX', 'MRC.13.OptB' -> 'OTHERID.OptX' -- lets
    check see when an option reuses a DIFFERENT event's key pattern (the
    MRC.12 case) without needing to know the "correct" pattern in advance.
    """
    prefix = name.rsplit(".", 1)[0] if "." in name else name
    same = prefix == eid
    suffix = name[len(prefix):]
    suffix = re.sub(r"[A-Za-z]$", "X", suffix)  # OptA/OptB/OptC -> OptX; .a/.b -> .X
    return f"{'SAMEID' if same else 'OTHERID'}{suffix}"


def _load_loc_keys(modfs: ModFS) -> set[str] | None:
    """All English loc keys under the mod's localisation/english/ tree,
    recursive -- see focus_tree_audit.py's _load_loc_keys for why this can't
    be a single-level glob (confirmed: most of aNCFO_cco's .yml files live in
    per-nation subfolders, not directly in localisation/english/)."""
    root = modfs.mod_root / "localisation" / "english"
    if not root.is_dir():
        return None
    keys = set()
    for path in root.rglob("*.yml"):
        text = modfs.read(path)
        for m in re.finditer(r"(?m)^\s*([A-Za-z0-9_.\-]+):\d*\s+\"", text):
            keys.add(m.group(1))
    return keys


# ---- main ---------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--mod", help="mod root (default: parent of this script's tools/ dir)")
    p.add_argument("--vanilla", help="base game install root (default: $HOI4_PATH or the hardcoded Steam path)")
    sub = p.add_subparsers(dest="command", required=True)

    sp = sub.add_parser("list", help="list events in scope")
    sp.add_argument("--namespace")
    sp.add_argument("--file")

    sp = sub.add_parser("check", help="validate events")
    sp.add_argument("--file")
    sp.add_argument("--json", action="store_true")

    args = p.parse_args()
    modfs = build_env(args)
    {"list": cmd_list, "check": cmd_check}[args.command](args, modfs)


if __name__ == "__main__":
    main()
