#!/usr/bin/env python3
"""Query and validate HOI4 national focus trees for any mod on this root.

Focus TREE STRUCTURE is what this tool checks -- ID collisions, dangling
prerequisite/relative_position_id references, position overlaps, missing
loc -- not focus CONTENT (what a focus should do, its prose, its design).
That stays the model's job; this tool exists so it doesn't have to hold a
14,000-line file in context to answer "does this ID already exist" or "what
are this focus's neighbors."

Two things confirmed by reading real files before writing this, not assumed:
- A single file can hold MULTIPLE `focus_tree` blocks (aNCFO's HHE.national_
  branches.txt has seven). Every command operates per-tree, not per-file.
- `shared_focus`/`joint_focus`/`prerequisite` can reference a focus ID defined
  in a DIFFERENT country's file entirely (confirmed: COA's tree references
  `aritifcers_focus_new_year_new_state`, which is defined inside OAK's own
  file). ID resolution searches every loaded national_focus file, never just
  the one being edited.
- `relative_position_id` is different: per Wiki_NationalFocus.txt, it must
  target a focus in the SAME tree, and a cycle "may cause a game crash since
  it is impossible to determine the exact position of the focus" -- the
  wiki's own words, not a guess.

Generated by claude. Backs aNCFO_cco-focus-tree-builder's workflow -- see
that agent file and .claude/docs/tooling-reference.md.

Usage (run from a mod's tools/ directory, or pass --mod explicitly):
    python focus_tree_audit.py trees
    python focus_tree_audit.py list --tree HHE_warmonger_focus
    python focus_tree_audit.py pacing --tree HHE_warmonger_focus
    python focus_tree_audit.py check --tree HHE_warmonger_focus
    python focus_tree_audit.py check
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _hoi4_modfs import Block, ModFS, parse_blocks_list, strip_comments_keep_lines

DEFAULT_VANILLA = r"D:\Program Files\SteamLibrary\steamapps\common\Hearts of Iron IV"
DEFAULT_FOCUS_POINT_DAYS = 7

FOCUS_KINDS = ("focus", "joint_focus", "shared_focus")


# ---- setup ----------------------------------------------------------------

def build_env(args):
    mod_root = Path(args.mod).resolve() if args.mod else Path(__file__).resolve().parents[1]
    if not (mod_root / "descriptor.mod").is_file():
        raise SystemExit(f"error: {mod_root} has no descriptor.mod -- pass --mod <mod root>")
    vanilla_root = Path(args.vanilla or os.environ.get("HOI4_PATH") or DEFAULT_VANILLA)
    modfs = ModFS(mod_root, vanilla_root)
    return modfs


def focus_point_days(modfs: ModFS) -> int:
    """FOCUS_POINT_DAYS if the mod overrides it in common/defines, else the
    vanilla default (7) -- confirmed via Wiki_NationalFocus.txt: 'a cost of 1
    represents a week by default.' Never hardcode 7 without checking; a mod
    CAN override this define."""
    for path, origin in modfs.list_dir("common/defines"):
        text = modfs.read(path)
        m = re.search(r"FOCUS_POINT_DAYS\s*=\s*(\d+)", text)
        if m:
            return int(m.group(1))
    return DEFAULT_FOCUS_POINT_DAYS


class Tree:
    """A focus_tree, OR a synthetic grouping of top-level `shared_focus = {}`
    library blocks from one file (HOI4 has no `focus_tree` wrapper for these,
    but they use the same id/x/y/relative_position_id/prerequisite schema and
    chain relative_position_id against each other within their own file --
    confirmed: army_effort's siblings in generic.military.txt use
    `relative_position_id = army_effort`. Treating each file's shared_focus
    set as its own pseudo-tree is what makes that chain resolvable at all."""

    def __init__(self, blocks: list[Block], tree_id: str, path: Path, block: Block | None = None):
        self.block = block
        self.id = tree_id
        self.path = path
        self.focuses: dict[str, Block] = {}
        self.kinds: dict[str, str] = {}  # focus_id -> "focus" | "joint_focus" | "shared_focus"
        for child in blocks:
            if child.name in FOCUS_KINDS:
                fid = child.get("id")
                if fid:
                    self.focuses[fid] = child
                    self.kinds[fid] = child.name


def load_all_trees(modfs: ModFS) -> tuple[list[Tree], dict[str, Tree]]:
    """Every focus_tree block, PLUS every file's top-level shared_focus library
    blocks (grouped as one synthetic tree per file -- see Tree's docstring),
    across every loaded national_focus file. Also returns a global focus_id ->
    owning-Tree index for cross-file/cross-tree reference resolution (a
    focus_tree's `prerequisite`/`shared_focus` list commonly points at a
    shared_focus block, or even a focus defined in a DIFFERENT nation's own
    tree -- confirmed: COA references `aritifcers_focus_new_year_new_state`,
    defined inside OAK's file, not a shared_focus block at all).
    """
    trees: list[Tree] = []
    global_index: dict[str, Tree] = {}
    for path, origin in modfs.list_dir("common/national_focus"):
        if origin != "mod":
            continue  # never treat vanilla focus trees as part of a mod's own set
        text = modfs.read(path)
        top_level = parse_blocks_list(text, origin_file=path, origin=origin)

        shared_blocks = [b for b in top_level if b.name == "shared_focus"]
        if shared_blocks:
            t = Tree(shared_blocks, f"<shared_focus:{path.name}>", path)
            trees.append(t)
            for fid in t.focuses:
                global_index.setdefault(fid, t)

        for block in top_level:
            if block.name != "focus_tree":
                continue
            tree_id = block.get("id") or f"<unnamed:{path.name}:{block.line}>"
            t = Tree(block.children_all(), tree_id, path, block=block)
            trees.append(t)
            for fid in t.focuses:
                global_index.setdefault(fid, t)  # first-defined wins for display; dup checked separately
    return trees, global_index


def find_tree(trees: list[Tree], tree_id: str) -> Tree:
    for t in trees:
        if t.id == tree_id:
            return t
    raise SystemExit(f"error: no focus_tree with id {tree_id!r} found (run `trees` to list what's visible)")


# ---- position resolution ---------------------------------------------------

def resolve_position(tree: Tree, focus_id: str) -> tuple[int, int, str] | tuple[None, None, str]:
    """Absolute (x, y) for a focus within its own tree, walking the
    relative_position_id chain. Per Wiki_NationalFocus.txt: relative_position_id
    targets must be in the SAME tree, and a cycle can crash the game -- both
    checked here, not just assumed impossible.

    Returns (x, y, "ok") normally, or (None, None, "cycle") /
    (None, None, "missing:<target_id>") on failure.
    """
    seen = set()
    total_x = total_y = 0
    cur = focus_id
    while True:
        if cur in seen:
            return None, None, "cycle"
        seen.add(cur)
        block = tree.focuses.get(cur)
        if block is None:
            return None, None, f"missing:{cur}"
        x = _to_int(block.get("x")) or 0
        y = _to_int(block.get("y")) or 0
        total_x += x
        total_y += y
        rel = block.get("relative_position_id")
        if not rel:
            return total_x, total_y, "ok"
        cur = rel


def _has_real_content(block: Block | None) -> bool:
    """True if `block` exists and isn't just an empty `{ }` (i.e. present but
    unused, e.g. `allow_branch = { }`)."""
    return block is not None and bool(strip_comments_keep_lines(block.body).strip())


def _to_int(s: str | None) -> int | None:
    if s is None:
        return None
    m = re.search(r"-?\d+", s)
    return int(m.group()) if m else None


# ---- command: trees ---------------------------------------------------

def cmd_trees(args, modfs):
    trees, _ = load_all_trees(modfs)
    if args.file:
        trees = [t for t in trees if t.path.name == args.file]
    if not trees:
        print("(no focus_tree blocks found)")
        return
    w = max(len(t.id) for t in trees)
    for t in trees:
        line = t.block.line if t.block is not None else 1
        print(f"{t.id:<{w}}  {len(t.focuses):>4} focuses  <- {t.path.name}:{line}")


# ---- command: list ---------------------------------------------------

def cmd_list(args, modfs):
    trees, _ = load_all_trees(modfs)
    tree = find_tree(trees, args.tree)
    if not tree.focuses:
        print(f"(no focus/joint_focus entries found in {tree.id})")
        return
    for fid, block in tree.focuses.items():
        kind = tree.kinds[fid]
        x, y, status = resolve_position(tree, fid)
        pos = f"({x},{y})" if status == "ok" else f"INVALID:{status}"
        prereqs = [b.set_list("focus") for b in block.get_all_blocks("prerequisite")]
        prereqs_flat = [p for group in prereqs for p in group]
        mutex = [b.set_list("focus") for b in block.get_all_blocks("mutually_exclusive")]
        mutex_flat = [p for group in mutex for p in group]
        rel = block.get("relative_position_id") or "-"
        cost = block.get("cost") or "(default)"
        print(f"[{kind}] {fid}  pos={pos}  cost={cost}  relative_position_id={rel}")
        if prereqs_flat:
            print(f"    prerequisite: {', '.join(prereqs_flat)}")
        if mutex_flat:
            print(f"    mutually_exclusive: {', '.join(mutex_flat)}")


# ---- command: pacing ---------------------------------------------------

def cmd_pacing(args, modfs):
    trees, global_index = load_all_trees(modfs)
    tree = find_tree(trees, args.tree)
    fpd = focus_point_days(modfs)

    # cost-to-reach = longest path (in cost units) through required prerequisites,
    # since ALL prerequisite groups must be satisfied (AND across groups; each
    # group's own focus list is OR'd per HOI4 semantics -- but for a pacing
    # upper bound we take the max over the whole flattened set, which is the
    # conservative "worst case you had to wait" reading).
    memo: dict[str, float] = {}

    def cost_of(fid: str) -> float:
        block = tree.focuses.get(fid)
        if block is None:
            return 0.0
        c = block.get("cost")
        # No engine-documented default for a missing `cost` was found (not in
        # common/defines, not stated in Wiki_NationalFocus.txt) -- rather than
        # assert an unverified number, treat it as 0 for the pacing sum and
        # let `check`'s F011 surface the missing field explicitly.
        if c is None:
            return 0.0
        try:
            return float(c)
        except ValueError:
            return 0.0

    def reach(fid: str, stack: frozenset) -> float:
        if fid in memo:
            return memo[fid]
        if fid in stack:
            return 0.0  # cycle guard; prerequisite cycles are pathological, don't infinite-loop
        block = tree.focuses.get(fid)
        own_cost = cost_of(fid)
        if block is None:
            return own_cost
        prereq_groups = [b.set_list("focus") for b in block.get_all_blocks("prerequisite")]
        best_prereq = 0.0
        for group in prereq_groups:
            in_tree = [p for p in group if p in tree.focuses]
            if not in_tree:
                continue
            best_prereq = max(best_prereq, max(reach(p, stack | {fid}) for p in in_tree))
        total = best_prereq + own_cost
        memo[fid] = total
        return total

    all_ids = list(tree.focuses)
    has_dependent = set()
    for fid in all_ids:
        block = tree.focuses[fid]
        for grp in block.get_all_blocks("prerequisite"):
            for p in grp.set_list("focus"):
                has_dependent.add(p)
    leaves = [fid for fid in all_ids if fid not in has_dependent]

    rows = sorted(((reach(fid, frozenset()), fid) for fid in leaves), reverse=True)
    print(f"FOCUS_POINT_DAYS = {fpd} (from common/defines, or vanilla default)\n")
    print(f"{'leaf focus':<45} {'cost units':>10} {'~days':>8} {'~years':>7}")
    for total, fid in rows:
        days = total * fpd
        print(f"{fid:<45} {total:>10.1f} {days:>8.0f} {days/365:>7.2f}")


# ---- command: check ---------------------------------------------------

def cmd_check(args, modfs):
    trees, global_index = load_all_trees(modfs)
    if args.tree:
        trees = [find_tree(trees, args.tree)]
    elif args.file:
        trees = [t for t in trees if t.path.name == args.file]

    country_tags = _load_country_tags(modfs)
    loc_keys = _load_loc_keys(modfs)

    findings = []

    def emit(path, line, severity, rule, message):
        findings.append({"file": str(path), "line": line, "severity": severity, "rule": rule, "message": message})

    for tree in trees:
        seen_pos: dict[tuple[int, int], tuple[str, Block]] = {}
        for fid, block in tree.focuses.items():
            kind = tree.kinds[fid]
            x, y, status = resolve_position(tree, fid)

            # F009 relative_position_id cycle
            if status == "cycle":
                emit(tree.path, block.line, "ERROR", "F009",
                     f"{fid}: relative_position_id cycle -- per Wiki_NationalFocus.txt this can crash the game")
                continue
            # F010 relative_position_id target not in the same tree
            if status.startswith("missing:"):
                target = status.split(":", 1)[1]
                if target in global_index:
                    emit(tree.path, block.line, "ERROR", "F010",
                         f"{fid}: relative_position_id={target} exists but is in a different tree "
                         f"({global_index[target].id}) -- must be in the same tree")
                else:
                    emit(tree.path, block.line, "ERROR", "F010",
                         f"{fid}: relative_position_id={target} does not exist anywhere")
                continue

            # F002 / F003 position collisions (only meaningful once position resolved)
            key = (x, y)
            if key in seen_pos:
                other_fid, other_block = seen_pos[key]
                own_gated = _has_real_content(block.children().get("allow_branch"))
                other_gated = _has_real_content(other_block.children().get("allow_branch"))
                if own_gated and other_gated:
                    # Confirmed real pattern (HHE_subjects "victor_*" successor focuses):
                    # each gated to a different original_tag/flag via allow_branch, so
                    # they never coexist in one playthrough despite sharing a slot --
                    # cannot prove the conditions are truly exclusive without a real
                    # trigger evaluator, so this is a WARN to verify, not an ERROR.
                    emit(tree.path, block.line, "WARN", "F002",
                         f"{fid}: same position ({x},{y}) as {other_fid} -- both have allow_branch "
                         f"conditions, likely deliberate alternate-outcome focuses; verify the "
                         f"conditions are actually mutually exclusive")
                else:
                    emit(tree.path, block.line, "ERROR", "F002",
                         f"{fid}: exact position collision at ({x},{y}) with {other_fid}")
            else:
                for (ox, oy), (other_fid, _other_block) in seen_pos.items():
                    if oy == y and abs(ox - x) < 2:
                        emit(tree.path, block.line, "WARN", "F003",
                             f"{fid}: less than 2 x-units from {other_fid} at the same y={y} "
                             f"(project spacing convention, not an engine rule)")
                seen_pos[key] = (fid, block)

            # F001 prerequisite / mutually_exclusive reference existence (cross-file OK)
            for rule_key, block_name in (("prerequisite", "prerequisite"), ("mutually_exclusive", "mutually_exclusive")):
                for grp in block.get_all_blocks(block_name):
                    for ref in grp.set_list("focus"):
                        if ref not in global_index:
                            emit(tree.path, block.line, "ERROR", "F001",
                                 f"{fid}: {block_name} references focus={ref} which does not exist in any loaded national_focus file")

            # F005 bypass with no bypass_effect while completion_reward has real content
            bypass = block.children().get("bypass")
            reward = block.children().get("completion_reward")
            if bypass is not None and reward is not None and reward.body.strip():
                if block.children().get("bypass_effect") is None:
                    emit(tree.path, block.line, "INFO", "F005",
                         f"{fid}: has bypass with no bypass_effect -- completion_reward effects won't apply on bypass "
                         f"(per the wiki this may be intentional)")

            # F006 missing search_filters
            if block.children().get("search_filters") is None:
                emit(tree.path, block.line, "WARN", "F006", f"{fid}: no search_filters set (recommended, not required)")

            # F011 missing cost -- affects both in-game pacing and this tool's `pacing` command
            if block.get("cost") is None:
                emit(tree.path, block.line, "WARN", "F011",
                     f"{fid}: no cost set -- no verified engine default was found, `pacing` treats it as 0")

            # F007 loc keys
            if loc_keys is not None:
                if fid not in loc_keys:
                    emit(tree.path, block.line, "ERROR", "F007", f"{fid}: no matching localisation key found")
                if f"{fid}_desc" not in loc_keys:
                    emit(tree.path, block.line, "ERROR", "F007", f"{fid}_desc: no matching localisation key found")

            # F008 joint_focus cross-tag TAG validity
            if kind == "joint_focus" and country_tags is not None:
                avail = block.children().get("available")
                if avail is not None:
                    for m in re.finditer(r"(?m)^\s*([A-Z]{2,4})\s*=\s*\{", strip_comments_keep_lines(avail.body)):
                        tag = m.group(1)
                        if tag not in ("AND", "OR", "NOT", "NOR") and tag not in country_tags:
                            emit(tree.path, block.line, "ERROR", "F008",
                                 f"{fid}: available references TAG={tag} which is not in common/country_tags")

    # F004 global focus id collisions (across ALL trees, all files)
    seen_globally: dict[str, list[tuple[Path, int]]] = {}
    all_trees_for_dup, _ = load_all_trees(modfs)
    for t in all_trees_for_dup:
        for fid, block in t.focuses.items():
            seen_globally.setdefault(fid, []).append((t.path, block.line))
    for fid, locs in seen_globally.items():
        if len(locs) > 1:
            for path, line in locs[1:]:
                emit(path, line, "ERROR", "F004", f"{fid}: duplicate focus/joint_focus id (also defined at {locs[0][0].name}:{locs[0][1]})")

    if args.json:
        print(json.dumps(findings, indent=2))
    else:
        for f in findings:
            print(f"{f['file']}:{f['line']}: [{f['severity']}] {f['rule']} {f['message']}")
        errors = sum(1 for f in findings if f["severity"] == "ERROR")
        warns = sum(1 for f in findings if f["severity"] == "WARN")
        infos = sum(1 for f in findings if f["severity"] == "INFO")
        print(f"\n{len(findings)} finding(s): {errors} error(s), {warns} warning(s), {infos} info")

    if any(f["severity"] == "ERROR" for f in findings):
        sys.exit(1)


def _load_country_tags(modfs: ModFS) -> set[str] | None:
    tags = set()
    found = False
    for path, origin in modfs.list_dir("common/country_tags"):
        if origin != "mod":
            continue
        found = True
        text = strip_comments_keep_lines(modfs.read(path))
        for m in re.finditer(r"(?m)^\s*([A-Z0-9]{2,4})\s*=", text):
            tags.add(m.group(1))
    return tags if found else None


def _load_loc_keys(modfs: ModFS) -> set[str] | None:
    """All English loc keys defined anywhere under the mod's own
    localisation/english/ tree -- RECURSIVE, not a single-level glob.
    Confirmed necessary: aNCFO_cco alone has 209 .yml files but only 15 sit
    directly in localisation/english/ -- the rest are in per-nation
    subfolders (localisation/english/aNCFO.<Nation>/*.yml) plus a `replace/`
    override folder. ModFS.list_dir() is intentionally single-level (matches
    how equipment/common dirs are organized), so this walks the tree itself
    rather than reusing it.
    """
    root = modfs.mod_root / "localisation" / "english"
    if not root.is_dir():
        return None
    keys = set()
    for path in root.rglob("*.yml"):
        text = modfs.read(path)
        for m in re.finditer(r"(?m)^\s*([A-Za-z0-9_.\-]+):\d*\s+\"", text):
            keys.add(m.group(1))
    return keys


# ---- main ---------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--mod", help="mod root (default: parent of this script's tools/ dir)")
    p.add_argument("--vanilla", help="base game install root (default: $HOI4_PATH or the hardcoded Steam path)")
    sub = p.add_subparsers(dest="command", required=True)

    sp = sub.add_parser("trees", help="list every focus_tree found")
    sp.add_argument("--file", help="limit to one national_focus filename")

    sp = sub.add_parser("list", help="every focus/joint_focus in a tree with position/prereqs")
    sp.add_argument("--tree", required=True)

    sp = sub.add_parser("pacing", help="cost-to-reach (days/years) for every leaf focus")
    sp.add_argument("--tree", required=True)

    sp = sub.add_parser("check", help="validate focus trees")
    sp.add_argument("--tree")
    sp.add_argument("--file")
    sp.add_argument("--json", action="store_true")

    args = p.parse_args()
    modfs = build_env(args)

    {"trees": cmd_trees, "list": cmd_list, "pacing": cmd_pacing, "check": cmd_check}[args.command](args, modfs)


if __name__ == "__main__":
    main()
