#!/usr/bin/env python3
"""Find dangling cross-references in any HOI4 mod on this root: named things
that get *referenced* somewhere in script but were never actually *defined*
anywhere the engine will load.

Why this exists: this class of bug is invisible by reading either end in
isolation -- the reference reads as plausible script, and the definition
(if it exists at all, under a slightly different name, or in a shadowed
file) looks fine on its own. It only becomes visible by cross-checking the
whole mod+vanilla tree at once, which is exactly the kind of thing that's
easy to miss by hand once a mod has hundreds of files, and easy for a
grep-hunt to get lost in. Two real, previously-unnoticed instances of this
found and fixed New-Horizons's `MAIN-+-SEA-rework` branch:

  1. `map/strategicregions/253-Iwo Jima.txt` declared `id=253` for a
     region the mod repurposed from a deprecated vanilla region -- but
     vanilla's own `map/strategicregions/253-Vindhyachal.txt` still ships
     on disk with that same id (province list commented out). HOI4 only
     overrides a vanilla file by exact filename match, not by `id=`, so
     both loaded and the vanilla (empty) definition won, silently
     orphaning the mod's 5 intended provinces ("MAP_ERROR: no strategic
     region assigned" -> the AI's map-dependent code eventually hit a
     null/invalid region and access-violated).
  2. `common/national_focus/soviet.txt` had two `mio:SOV_sevastopol_
     marine_plant_organization = { ... }` effect blocks, but no
     `SOV_sevastopol_marine_plant_organization` was ever defined in
     `common/military_industrial_organization/organizations/` -- only a
     similarly-scoped `SOV_black_sea_shipyard_organization` was. The
     effect silently no-ops against a scope that "does not match any MIO
     in database", which correlated with an `ai_military_minister.cpp`
     "Failed to find enabled target template" assertion (a hard crash
     under -debug) once the USSR's southern/Black-Sea naval-base focuses
     actually completed -- i.e. only once the AI (or a player) controlled
     the right coastal states to reach that point in the tree.

Both classes generalize past this one mod: a strategic-region id collision
with vanilla can happen to any mod that renumbers/renames regions, and a
dangling `mio:` scope reference can happen to any mod using Man the Guns
military-industrial-organization content. Neither is covered by the
existing equipment/focus-tree/event audit tools, which validate their own
narrower domains.

Reuses `_hoi4_modfs.py`'s ModFS (mod-over-vanilla layering, exact-filename
replace semantics) and brace-block parser -- nothing mod-specific is
hardcoded here.

Generated by claude.

Usage (run from a mod's tools/ directory, or pass --mod explicitly):
    python reference_audit.py regions --mod "New-Horizons" --json
    python reference_audit.py mio --mod "New-Horizons"
    python reference_audit.py all --mod "New-Horizons"
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _hoi4_modfs import ModFS, parse_blocks_list, strip_comments_keep_lines

DEFAULT_VANILLA = r"D:\Program Files\SteamLibrary\steamapps\common\Hearts of Iron IV"

# Directories skipped when walking a mod tree for reference-scanning --
# dev artifacts, not script the engine loads.
SKIP_DIR_NAMES = {".git", "tools", "documentation", "gfx", "sound", "music", "portraits", "thumbnail.png"}

MIO_REF_RE = re.compile(r"\bmio:([A-Za-z0-9_]+)")


# ---- setup ------------------------------------------------------------

def resolve_mod_root(arg_mod: str | None) -> Path:
    mod_root = Path(arg_mod).resolve() if arg_mod else Path(__file__).resolve().parents[1]
    if not (mod_root / "descriptor.mod").is_file():
        raise SystemExit(f"error: {mod_root} has no descriptor.mod -- pass --mod <mod root>")
    return mod_root


def build_modfs(args) -> ModFS:
    mod_root = resolve_mod_root(args.mod)
    vanilla_root = Path(args.vanilla or os.environ.get("HOI4_PATH") or DEFAULT_VANILLA)
    return ModFS(mod_root, vanilla_root)


def iter_mod_txt_files(mod_root: Path):
    """All *.txt under mod_root, skipping dev-artifact directories. Mod-only
    (not vanilla) -- a dangling reference is a mod-authoring bug, and a
    mod-added name obviously only appears in mod-authored files."""
    for dirpath, dirnames, filenames in os.walk(mod_root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIR_NAMES and not d.startswith(".")]
        for fn in filenames:
            if fn.endswith(".txt"):
                yield Path(dirpath) / fn


# ---- strategic region integrity ----------------------------------------

def load_definition_provinces(modfs: ModFS) -> dict[str, str]:
    """id -> type (land/sea/lake/...) from the winning map/definition.csv,
    mod copy if present else vanilla's (single-file exact-path override,
    same winner rule ModFS.list_dir uses for a directory listing)."""
    matches = modfs.list_dir("map", pattern="definition.csv")
    if not matches:
        raise SystemExit("error: no map/definition.csv found in mod or vanilla")
    path, _origin = matches[0]
    out: dict[str, str] = {}
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        parts = line.strip().split(";")
        if len(parts) < 5 or not parts[0].isdigit():
            continue
        out[parts[0]] = parts[4]
    # id 0 is the reserved "no province" entry -- never expected in a region.
    out.pop("0", None)
    return out


def load_strategic_regions(modfs: ModFS):
    """Returns (id_to_files: {id: [(path, origin), ...]}, id_to_provinces:
    {id: set[str]}) across every file the engine would actually load for
    map/strategicregions (mod files, plus vanilla files not shadowed by an
    identically-NAMED mod file -- a differently-named mod file does NOT
    shadow a same-id vanilla file, which is exactly the trap this catches)."""
    id_to_files: dict[str, list[tuple[Path, str]]] = {}
    id_to_provinces: dict[str, set[str]] = {}
    for path, origin in modfs.list_dir("map/strategicregions"):
        text = strip_comments_keep_lines(path.read_text(encoding="utf-8", errors="replace"))
        for block in parse_blocks_list(text, origin_file=path, origin=origin):
            if block.name != "strategic_region":
                continue
            rid = block.get("id")
            if rid is None:
                continue
            id_to_files.setdefault(rid, []).append((path, origin))
            id_to_provinces.setdefault(rid, set()).update(block.set_list("provinces"))
    return id_to_files, id_to_provinces


def check_regions(modfs: ModFS) -> dict:
    id_to_files, id_to_provinces = load_strategic_regions(modfs)
    def_provinces = load_definition_provinces(modfs)

    collisions = []
    for rid, files in sorted(id_to_files.items(), key=lambda kv: int(kv[0])):
        if len(files) > 1:
            collisions.append({
                "id": rid,
                "files": [{"path": str(p), "origin": o} for p, o in files],
            })

    covered: set[str] = set()
    for provs in id_to_provinces.values():
        covered |= provs

    orphaned = [
        {"province": pid, "type": ptype}
        for pid, ptype in sorted(def_provinces.items(), key=lambda kv: int(kv[0]))
        if pid not in covered
    ]

    return {"collisions": collisions, "orphaned_provinces": orphaned}


# ---- MIO reference integrity --------------------------------------------

def load_defined_mios(modfs: ModFS) -> set[str]:
    names: set[str] = set()
    for path, origin in modfs.list_dir("common/military_industrial_organization/organizations"):
        text = strip_comments_keep_lines(path.read_text(encoding="utf-8", errors="replace"))
        for block in parse_blocks_list(text, origin_file=path, origin=origin):
            names.add(block.name)
    return names


def check_mio(modfs: ModFS) -> dict:
    defined = load_defined_mios(modfs)
    dangling: list[dict] = []
    for path in iter_mod_txt_files(modfs.mod_root):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        clean = strip_comments_keep_lines(text)
        for lineno, line in enumerate(clean.splitlines(), start=1):
            for m in MIO_REF_RE.finditer(line):
                name = m.group(1)
                if name not in defined:
                    dangling.append({
                        "file": str(path.relative_to(modfs.mod_root)),
                        "line": lineno,
                        "referenced": name,
                    })
    return {"defined_count": len(defined), "dangling": dangling}


# ---- reporting ------------------------------------------------------------

def report_regions(result: dict, as_json: bool):
    if as_json:
        print(json.dumps(result, indent=2))
        return
    collisions = result["collisions"]
    orphaned = result["orphaned_provinces"]
    print(f"=== strategic region id collisions ({len(collisions)}) ===")
    for c in collisions:
        print(f"  id={c['id']}:")
        for f in c["files"]:
            print(f"    [{f['origin']}] {f['path']}")
    print(f"\n=== provinces with no strategic region assigned ({len(orphaned)}) ===")
    for o in orphaned:
        print(f"  {o['province']} ({o['type']})")
    if not collisions and not orphaned:
        print("(clean)")


def report_mio(result: dict, as_json: bool):
    if as_json:
        print(json.dumps(result, indent=2))
        return
    dangling = result["dangling"]
    print(f"defined MIOs found: {result['defined_count']}")
    print(f"=== dangling mio: references ({len(dangling)}) ===")
    for d in dangling:
        print(f"  {d['file']}:{d['line']}  mio:{d['referenced']}")
    if not dangling:
        print("(clean)")


# ---- CLI --------------------------------------------------------------

def main():
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--mod", help="mod root (default: parent of this script's directory -- pass explicitly when invoking from .global_tools for any other mod)")
    common.add_argument("--vanilla", help=f"HOI4 install dir (default: {DEFAULT_VANILLA})")
    common.add_argument("--json", action="store_true")

    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter, parents=[common])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("regions", parents=[common], help="strategic-region id collisions (incl. vs vanilla) + provinces missing a region")
    sub.add_parser("mio", parents=[common], help="mio:<name> references with no matching organization definition")
    sub.add_parser("all", parents=[common], help="run both checks")
    args = ap.parse_args()

    modfs = build_modfs(args)

    ran_any_dangling = False
    if args.cmd in ("regions", "all"):
        result = check_regions(modfs)
        report_regions(result, args.json)
        ran_any_dangling = ran_any_dangling or bool(result["collisions"]) or bool(result["orphaned_provinces"])
    if args.cmd in ("mio", "all"):
        if args.cmd == "all" and not args.json:
            print()
        result = check_mio(modfs)
        report_mio(result, args.json)
        ran_any_dangling = ran_any_dangling or bool(result["dangling"])

    sys.exit(1 if ran_any_dangling else 0)


if __name__ == "__main__":
    main()
