#!/usr/bin/env python3
"""Keep .global_tools mirrored into each mod's own tools/ directory.

Per .claude/CLAUDE.md: ".global_tools is for global tools that work for all
mods. A local copy of these tools must be placed among all mods in this
list: aNCFO_cco, CrC_antarctica." This script is that mirroring step, made
repeatable instead of a one-time manual copy -- .global_tools had already
drifted from both mirrors once (aNCFO_cco/tools carries several map-analysis
scripts, CrC_antarctica/tools carries a different subset again) before this
existed.

Only files that ALREADY live in .global_tools are mirrored -- this script
pushes outward, it never pulls a mod-local file into .global_tools or
invents which files belong here.

No argparse (IRP-style): paths are hardcoded relative to this file, so the
invocation stays `python .global_tools/sync_global_tools.py [--check|--apply]`.

Generated by claude.
"""
from __future__ import annotations

import filecmp
import shutil
import sys
from pathlib import Path

GLOBAL_TOOLS_DIR = Path(__file__).resolve().parent
MOD_ROOT = GLOBAL_TOOLS_DIR.parent
MOD_LIST = ["aNCFO_cco", "CrC_antarctica"]


def global_tool_files() -> list[Path]:
    return sorted(p for p in GLOBAL_TOOLS_DIR.glob("*.py") if p.is_file())


def check() -> int:
    """Print drift, one line per (file, mod) pair that's missing or differs.
    Returns a process exit code (0 = in sync, 1 = drift found)."""
    drift = 0
    for src in global_tool_files():
        for mod in MOD_LIST:
            dst = MOD_ROOT / mod / "tools" / src.name
            if not dst.is_file():
                print(f"MISSING  {mod}/tools/{src.name}")
                drift += 1
            elif not filecmp.cmp(src, dst, shallow=False):
                print(f"DIFFERS  {mod}/tools/{src.name}")
                drift += 1
    if not drift:
        print("in sync: all .global_tools files match every mod's tools/ mirror")
    return 1 if drift else 0


def apply() -> int:
    for src in global_tool_files():
        for mod in MOD_LIST:
            dst_dir = MOD_ROOT / mod / "tools"
            dst_dir.mkdir(parents=True, exist_ok=True)
            dst = dst_dir / src.name
            if dst.is_file() and filecmp.cmp(src, dst, shallow=False):
                continue
            shutil.copy2(src, dst)
            print(f"copied   {mod}/tools/{src.name}")
    return 0


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode == "--check":
        sys.exit(check())
    elif mode == "--apply":
        sys.exit(apply())
    else:
        sys.exit("usage: sync_global_tools.py [--check|--apply]")
